### ISSUE TITLE
Tell user to switch network/switch automatically on deeplink

### ISSUE THREAD

**Issue by etharner** [superhero-com/superhero-wallet#1113]
E.g. if you comment a tip, open deeplink and have wrong network it will raise an error `Unexpected token in JSON...`. It will be good to automatically switch network (encode it in deeplink or parse deeplink tx) or tell user to do so.

**Comment by CedrikNikita** [comment]
fixed in #1524

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. The user is already informed with a modal in such cases.
