### ISSUE TITLE
Deeplink issue on Android app

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#1270]
I can't connect to Superhero Meet using the Android app (commit 5666c2a / v.0.8.2). UI does not detect the app and redirects the user to the web wallet:
https://user-images.githubusercontent.com/69896204/131855182-d3ee6743-1c56-4052-8322-16c20da900c9.mov

**Comment by Liubov-crypto** [comment]
reproducible for me with the latest android app

**Comment by CedrikNikita** [comment]
I think this issue is on Superhero Meet side and should be fixed there. I will close this issue, feel free to reopen if something is missed.
