### ISSUE TITLE
Remove workarounds from #1240

### ISSUE THREAD

**Issue by etharner** [superhero-com/superhero-wallet#1278]
Let's remove 3 workarounds introduced in #1240 after corresponding PR's/issue will be resolved in SDK:
1) https://github.com/aeternity/aepp-sdk-js/pull/1249
2) https://github.com/aeternity/aepp-sdk-js/issues/1261
3) https://github.com/aeternity/aepp-sdk-js/issues/1266

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
