### ISSUE TITLE
Middlware should not impact transactions

### ISSUE THREAD

**Issue by kenodressel** [superhero-com/superhero-wallet#1443]
At the moment a normal tx can not be send when the mdw is down (can be reproduced by changing the mdw url in the settings to a broken one). The middleware should not impact our wallet like this.

**Comment by benhus** [comment]
It looks like the wallet is trying to calculate the transaction fee, which can not be retrieved and because of the missing data the transaction can not be executed. In case of not responding MDW the fee if possible should be retrieved from the node, otherwise omitted.

**Comment by CedrikNikita** [comment]
The current version of the wallet is capable of sending transactions when the mdw is unavailable or if it does not respond.
