### ISSUE TITLE
Infinite redirect to DEX after signing a transaction

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#1465]
On mob browser: 
After I sign the transaction in the wallet (app), there is a redirect to dex and again I need to connect the wallet and dex:
https://user-images.githubusercontent.com/69896204/172427233-9c00d110-ea9b-4e9f-8dcd-fac9d44c3018.MP4

**Comment by Liubov-crypto** [comment]
Reproducible on my side

**Comment by Liubov-crypto** [comment]
Reproducible on the current product branch 810fdfc

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
