### ISSUE TITLE
Superhero endless loop (saturates one CPU core)

### ISSUE THREAD

**Issue by loxs** [superhero-com/superhero-wallet#1799]
**Describe the bug**
Superhero seems to repeatedly go into some endless loop where it saturates one of my CPU cores.
I get a process (on Macbook Pro M1) called “Brave Browser Helper (Renderer)” that uses 100-150% CPU and drains my battery.
If I kill that process I get a notification from Brave saying that Superhero has been killed and an option to click there to reload it. I do that and for some time it’s fine, but after some period of normal usage, this thing happens again.

**To Reproduce**
I don't have a clear reproduction path and I have no idea when it happens.
My usage is just connecting and disconnecting to some daepp which uses the SDK (I am developing it at the moment). Haven’t even started to sign transactions yet. Sometimes I switch networks (mainnet/testnet).
Granted, I do that a lot (connecting and disconnecting) as I am currently developing this part.
This may have something to do with the permission `Don't ask for login requests`. Still not sure though, as I am experimenting with having the option on or off... and not sure that it does not happen when it's off

**Expected behavior**
Superhero shouldn't go into this endless loop

**Desktop (please complete the following information):**
- OS: Mac OS 12.6.3 on an M1 Pro, 32 GB RAM
- Browser: Brave and Chrome
- Version: 
 * Brave: Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (arm64)
 * Chrome:  Version 109.0.5414.119 (Official Build) (arm64)

**Comment by CedrikNikita** [comment]
Hi, @loxs. Thank you for a report, I think I've seen this problem too. Was going to report it with a better investigation. For me it looked like that
![image](https://user-images.githubusercontent.com/9008074/215793140-f0c6bc7d-00cc-48fc-ad6d-121deff4cb79.png)

**Comment by CedrikNikita** [comment]
This commit might be one of the issues that is related to a problem you have raised 
https://github.com/aeternity/superhero-wallet/pull/1863/commits/93bf9a312f71b9b131c52b053b56f764f7c6f5b3

**Comment by davidyuk** [comment]
Can you check is this issue persist using https://github.com/aeternity/aepp-sdk-js/tree/develop/examples/browser/wallet-web-extension?
its built version https://docs.aeternity.com/aepp-sdk-js/develop/examples/browser/wallet-web-extension.zip

**Comment by loxs** [comment]
I am not sure if I can reproduce my work/test setup with this. For example can I use another account?
Otherwise, I played around with it a little (connected to aepp, triggered GA upgrade without signing/confirmation, etc..) and it doesn't seem to trigger the problem, but it's not at all representative.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
