### ISSUE TITLE
Warn if words in mnemonic phrase missed in wordlist, don't block recovery

### ISSUE THREAD

**Issue by davidyuk** [superhero-com/superhero-wallet#2065]
> Please remember to allow recovery from mnemonic phrases that have invalid checksums (or that you don't have the wordlist)
When a checksum is invalid, warn the user that the phrase is not something generated by your app, and ask if they would like to use it anyway. This way, your app only needs to hold the wordlists for your supported languages, but you can recover phrases made by other apps in other languages.
However, there should be other checks in place, such as checking to make sure the user is inputting 12 words or more separated by a space. ie. phrase.trim().split(/\s+/g).length >= 12

https://www.npmjs.com/package/bip39

Actually, do we validate the checksum of the mnemonic phrase? I've swapped two last words in my mnemonic phrase and it got accepted.

**Comment by davidyuk** [comment]
I've used "eye quarter chapter suit cruel scrub verify stuff volume control learn dust" and appears that if I swap two last words the mnemonic phrase would be correct indeed. Doing different swaps I've got the error "Account not found. Please check again your seed phrase.".

> Account not found

Sounds confusing

**Comment by davidyuk** [comment]
You may reject this feature considering users may lose their funds because of a typo in a mnemonic phrase if they ignore a warning. The original issue was raised while discussing mnemonic security with @zxq9

**Comment by CedrikNikita** [comment]
We thought about it and decided it might bring more risk than benefit. Will close it.  Feel free to open the issue back up if there are any unresolved issues or additional questions.
