### ISSUE TITLE
support PayingForTx (meta transaction) scenarios

### ISSUE THREAD

**Issue by marc0olo** [superhero-com/superhero-wallet#2159]
please introduce support for this 🙏 

scenarios I can imagine:
- pasting a signed inner tx into the wallet to wrap into a PayingForTx and signing it
- aepp that requests a signed inner tx which is prepared to be wrapped into a payingfortx where the aepp receives the signed inner tx and broadcasts it to a specific node (alternatively the aepp directly tells the wallet where to send the signed inner tx to
- configuration of a dedicated payingfortx service url in the wallet where the user sends signed inner tx's to

maybe some protocol needs to be defined for the aepp <-> wallet communication (our lovely topic 🙈)

feedback of @thepiwo @kenodressel @davidyuk and @CedrikNikita is appreciated, especially for the scenario where an aepp potentially covers the fee (which can be important for newcomers)

**Comment by davidyuk** [comment]
> maybe some protocol needs to be defined for the aepp <-> wallet communication

It is implemented. AeSdkWallet would call Account's `signTransaction` with `innerTx` option. You can check it in aepp example https://docs.aeternity.com/aepp-sdk-js/v13.1.0/examples/browser/wallet-iframe/

> the scenario where an aepp potentially covers the fee

This is ready on sdk side (aepp can request wallet to sign an inner tx).

> pasting a signed inner tx into the wallet to wrap into a PayingForTx and signing it

Not sure in wich case it would be copied as a string

> configuration of a dedicated payingfortx service url in the wallet where the user sends signed inner tx's to

This sounds like an overkill, maybe the wallet by itself can cover five first cheap transactions for new users 🙃

**Comment by marc0olo** [comment]
> This is ready on sdk side (aepp can request wallet to sign an inner tx).
> 
> >

perfect, hope to see it supported by Superhero Wallet 🔜 

> Not sure in wich case it would be copied as a string
> 
> >

could be relevant for some developers. this way I could easily produce a `ContractCreateTx` with a throw-away keypair and cover the fee with my wallet account.


> This sounds like an overkill, maybe the wallet by itself can cover five first cheap transactions for new users 🙃

we would anyway need a wallet-specific backend service to cover the fee then which sounds like even more overkill to me, especially if it should be limited to first X transactions. but I think we should define an interface for the backend service first in case we'd like to support this.

**Comment by davidyuk** [comment]
as for df91a42dced0a8c29635827949e1d549cbb0f481 this seems to be not working (sdk already updated to 13.0.1)
https://docs.aeternity.com/aepp-sdk-js/develop/examples/browser/aepp/ fails with
> InvalidTxError: Transaction verification errors: Signature cannot be verified, please ensure that you transaction have the correct prefix and the correct private key for the sender address

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
