### ISSUE TITLE
Add icon for LAEX (Lexon.org) token

### ISSUE THREAD

**Issue by marc0olo** [superhero-com/superhero-wallet#2224]
### Describe the solution you'd like
I want to see the LAEX token (contractId: `ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt`) displayed with its token

### Additional context

Please use following icon for the token:

![lexon-logo-black-with-white-stroke](https://github.com/aeternity/superhero-wallet/assets/8124114/b746e0fe-d52d-4afe-be01-12003fec0ed2)

**Comment by Liubov-crypto** [comment]
LGTM. 

I have a question, colours looks a lil bit reverted (I mean black inside instead of white), is it ok? 


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/5014d684-e589-4ddc-823f-08ecacb4b042)

**Comment by martinkaintas** [comment]
The icon is only the outside part (black circle with white stroke). The center is transparent, and since the background is black it looks like this.
@marc0olo @onvisions Should we make the center of the icon white?

**Comment by onvisions** [comment]
This is how the icon looks like on dark background on their own website: https://www.lexon.org/
I wouldn't touch or modify the icon/logo without permission or request from their owners. It seems that the icon provided is a bit different... May be we can request updated graphic resource. I can edit it if needed to  match the vision on their web page but please provide me the SVG icon and sync with the brand owner.
![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b7d6f104-e7a4-4262-9d0b-a07869ae2f48)

**Comment by onvisions** [comment]
@marc0olo The icon resource provided was not properly vectorized so I checked for reference  on https://www.lexon.org/ and fixed the icon accordingly. I think the result is excellent so here is the updated vector resource and the side by side comparison with the image on their website:
![Side by side comparison](https://github.com/superhero-com/superhero-wallet/assets/12225410/b8691f38-492a-4cbb-b05b-1d8d8d74eacc)
![laex](https://github.com/superhero-com/superhero-wallet/assets/12225410/8f482184-08ec-483f-a977-61578b588811)
