### ISSUE TITLE
After reset the wallet iOS app is showing a black screen

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2411]
https://aeternity-blockchain.atlassian.net/browse/SW-1372

**Bug Description**

After reset the wallet iOS app is showing a black screen. I have to close or reset the app. 
The same behaviour when the wallet is connected to dapp and I’m refreshing the page. 

**Steps to reproduce**
1. Reset the wallet
2. Observe

**Environment selector**
iOS

**Comment by Liubov-crypto** [comment]
Can be closed.

**Comment by CedrikNikita** [comment]
fixed in #2208
