### ISSUE TITLE
Test if BTC node inavailablity breaks AE wallet use

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2413]
https://aeternity-blockchain.atlassian.net/browse/SW-1177

**Description**

- temporarily change BTC endpoint to a broken one
- check how that affects the wallet use of aeternity accounts

**Odo's comment:**
After broken the BTC endpoint address, then i tested AE functionality. App works correctly for AE accounts. I can sent tokens, claim a name, fetch transaction list, create multisig account and create proposal transaction. LGTM
But when we want send BTC, then we get error about "Failed to fetch".  I think we should disable the BTC send button when Network is broken.

**Comment by paolomolo** [comment]
LGTM, I have created a separate issue to disable send buttons for each network
https://github.com/superhero-com/superhero-wallet/issues/2528
