### ISSUE TITLE
Move fungible tokens from Vuex to composable

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2418]
https://aeternity-blockchain.atlassian.net/browse/SW-1298

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/19412414-da2f-4877-9464-5d2780797862)
https://github.com/superhero-com/superhero-wallet/assets/147718725/bb22462a-faaa-4b8f-ac66-732e35254299
https://github.com/superhero-com/superhero-wallet/assets/147718725/56f6c543-04c9-4191-b79f-e5830479e30a

**Comment by dvdbak** [comment]
LGTM

on Web and Extension
