### ISSUE TITLE
Move permissions from Vuex to composable

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2419]
https://aeternity-blockchain.atlassian.net/browse/SW-1347

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/7d6f9785-1603-463d-aa38-64e8efbbc6c5)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/1e410cf9-fe90-41bc-96dc-f31bd129f4e5)
https://github.com/superhero-com/superhero-wallet/assets/147718725/36ac7cdd-0d18-4828-846a-0b3ebcf5842f
https://github.com/superhero-com/superhero-wallet/assets/147718725/4a59c134-4ea9-4681-91e6-5f992c285784

**Comment by peronczyk** [comment]
I know that initially you already tested this task but @subhod-i and @CedrikNikita suggested to make full regression testing for this one. I'm not sure if full regression is a good idea, but I'm sure that every aspect of the app that is related to signing should be tested thoroughly.

**Comment by Liubov-crypto** [comment]
LGTM

**Comment by CedrikNikita** [comment]
fixed by #2369
