### ISSUE TITLE
Move the account signing methods from Vuex to composable

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2425]
https://aeternity-blockchain.atlassian.net/browse/SW-1378

**Comment by Liubov-crypto** [comment]
During my testing I've constantly got this issue in console, and I think it might be affect all errors that I listed below:

Error: pubkey cannot be null or undefined.

![err1](https://github.com/superhero-com/superhero-wallet/assets/69896204/63afaff2-623a-4fce-b1a3-34cabb50197c)

1. Can't send ae and Fungible tokens: 
2. Verify an amount and Max button isn't working for FT:

https://github.com/superhero-com/superhero-wallet/assets/69896204/d5f810e3-e958-43ed-a1cb-6ff8d2b44828

3. Set name pointer: 
![set pointer ](https://github.com/superhero-com/superhero-wallet/assets/69896204/225f1552-a009-475e-a2cd-0eb8d8514f95)

4. Register a name:
![reg](https://github.com/superhero-com/superhero-wallet/assets/69896204/f6e33d4b-1888-4a24-8374-619bf03a21e9)

5. Multisig creation
6. Generate Gift card
7. Bid on name
8. Transactions on DEX:
![swap](https://github.com/superhero-com/superhero-wallet/assets/69896204/e467fe79-015f-4927-8f67-4841a4736657)
9. Interactions with superhero.com  - I can connect my wallet but there is no popup for signing Txs.

@peronczyk please check it.

**Comment by peronczyk** [comment]
@Liubov-crypto I updated the PR with some fixes. Can you please see if all problems are fixed?

**Comment by Liubov-crypto** [comment]
Sometimes I get an error with multisig creation when I'm using 2nd account or 3,4,5 accounts as 1st Signer (this issue isn't reproducible on dev):

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/7ad19c2a-e179-4c82-9ed9-0ef0d36b41e7)
![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/b61e8c43-047d-4f1f-9337-afb8c16fe53a)


@peronczyk could you please check it?

**Comment by Liubov-crypto** [comment]
Now the issue with multisig creation is happening on dev too. We already have such issue in our backlog. 
I think we can proceed with this PR or should I recheck it again?

**Comment by Liubov-crypto** [comment]
I have retested and issue with multisig is reproducible again in the testnet. maybe I have to wait until backend will work properly and then recheck it again. 


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/571c9d48-6672-445b-abe5-a419a54c520d)



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/f638df12-d9b1-4a80-888f-e2573a14efc5)
