### ISSUE TITLE
If user enter random URL address into the in-app browser, it will open as a black page

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2436]
https://aeternity-blockchain.atlassian.net/browse/SW-1201

**Describe the bug**

If user enter random URL address into the in-app browser, it will open as a black page. 

**Expected result**

It should open it or show 404 page. 

**Steps to reproduce**
1. enter an URL address into the in-app browser
2. Observe an empty black page. 

**Environment selector**
- iOS

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/f53838a0-75f4-43d3-9574-1018152a952b)

**Comment by dvdbak** [comment]
As per discussion it is not able to fetch the information that the URL is invalid or any other information from the web view.

**Comment by smaroudasunicorn** [comment]
closing this as a technical limitation
