### ISSUE TITLE
Revisit Extension Implementation

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2437]
https://aeternity-blockchain.atlassian.net/browse/SW-1174

Description

extension: resolve/research "read and change all your data on all websites" (same in metamask)

extension: resolve/research "modify data you copy and paste" (same in metamask)

apply to everything that is needed to push our app on top when you search superhero (extension example [Apply for Established Publisher and Featured badges in Chrome Web Store · Issue #1966 · superhero-com/superhero-wallet](https://github.com/aeternity/superhero-wallet/issues/1966) )

**Comment by olszewskimar** [comment]
We excluded Manifest 3 from this scope

**Comment by martinkaintas** [comment]
_"read and change all your data on all websites”:_ We are injecting code into all pages the user visits to check for aepps. If we remove the permission the user will have to first open the extension on the page he wants to interact with some aepp and give it permission to inject code to the specific page.

_"modify data you copy and paste”:_ Copy and paste seems to be working even without the `clipboardWrite` permission

**Comment by martinkaintas** [comment]
Closing in favor of #1966 & #2938
