### ISSUE TITLE
TIP IN transactions present different data in transaction details after refreshing

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2438]
https://aeternity-blockchain.atlassian.net/browse/SW-558

*Describe the bug*
Presented data changes after page refresh - transaction object fetched after refresh is lacking `amount` field

*Expected result*
Data should be the same after refreshing

*Steps to reproduce*
1. Go to TIP IN transaction from the transaction list
2. Refresh page

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/691d8403-6fc1-449b-b050-4838244f02fb)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/1570b501-eace-4877-aa2e-4c11e770959a)

**Comment by Liubov-crypto** [comment]
Reproducible for me on the latest dev branch, commit f5c8e2c:

https://github.com/superhero-com/superhero-wallet/assets/69896204/ce8d10ff-ae6e-455a-8ba5-e0e6b22735e7

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
