### ISSUE TITLE
Display placeholder when device has no camera on the QR Scanner

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2439]
https://aeternity-blockchain.atlassian.net/browse/SW-897

The problem:
Currently if the device has no camera or the camera is temporarily unavailable we are displaying empty space on the QR Scan modal:

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/48a612de-94b3-4cc2-a214-ee778638345d)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/71330c40-fb08-4d78-8f52-da8cf078f68e)

The solution:
Proposing some textual/visual information about the lack of camera access. Or  maybe reusing the message displayed when user denies the access to the camera but with a different text. @Tsvetan Kolev can you propose something?

Refactoring the component to TypeScript and Composition API.

Probably replacing the handleUnknownError with a logic that would display designed information.

**Comment by Liubov-crypto** [comment]
I tried to connect my Mac to external monitor and disabled camera permissions in Settings, but wallet detects that device has a camera. Idk if there is a different way to test it.
