### ISSUE TITLE
Active account is not preserved on migration

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2442]
https://aeternity-blockchain.atlassian.net/browse/SW-1306

Steps to reproduce:
1) Go to the develop branch
2) Create several account including bitcoin
3) Choose an active account not the first (0) one
4) Copy the state localStorage.getItem('state')
5) Pass the copied state into [feat-composables-migrations.wallet.z52da5wt.xyz](https://feat-composables-migrations.wallet.z52da5wt.xyz/) state by doing localStorage.setItem('state', copiedState) and press refresh

**Comment by peronczyk** [comment]
@paolomolo do we really need the migration for this? I feel that it's not a big deal if user will be switched to the 1st account after updating the app.
