### ISSUE TITLE
Find UI solution to sign RAW data

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2444]
https://aeternity-blockchain.atlassian.net/browse/SW-1270

@Tsvetan Kolev and @CedrikNikita  will work on this

@CedrikNikita After our sync call regarding template to serve 3 specific types of transactions I worked on the following design suggestion: 
https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=28407-145730&mode=design&t=BMAAtgwEtgrjaLZ6-0Connect your Figma account 

Do you think this will work or we have to sync to further precise it? Let me know if I have to update or change anything in the template.

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/4b00c185-d236-4151-9141-400201b7e0ad)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/2894e83e-bf2e-448b-a55e-5d500d846581)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/d6f7b883-70c2-4bf8-804d-ed74b3e8ed06)

**Comment by smaroudasunicorn** [comment]
No need to implement now.
