### ISSUE TITLE
Wallet modals fixed to top instead being fixed to bottom.

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2445]
https://aeternity-blockchain.atlassian.net/browse/SW-594

Wallet modals fixed to top instead being fixed to bottom. See the screenshots.

Expected result
Wallet modals should be displayed at the bottom of the screen.

Steps to reproduce

Open Superhero wallet on Android device.

Open some of the modals shown above on the screenshots.

Bug Description

**Describe the bug**
Wallet modals fixed to top instead being fixed to bottom. See the screenshots.

**Expected result**
Wallet modals should be displayed at the bottom of the screen.

**Steps to reproduce**
1. Open Superhero wallet on Android device.
2. Open some of the modals shown above on the screenshots.

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/2c758082-88ff-41cd-aa71-1a3d05243f99)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/4fbb5413-c62f-4deb-9d52-101c813cb392)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/d7fcbff1-dc42-41fd-b16d-af80fe128de2)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/b70a6662-72a9-427b-bdc5-cb11dcd6ebff)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/a525828a-35ee-4c90-8453-34fe166d4cf4)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/b5381981-0eb1-448e-ae37-11094313f748)

Expected result
Wallet modals should be displayed at the bottom of the screen.

Steps to reproduce

Open Superhero wallet on Android device.

Open some of the modals shown above on the screenshots.

Bug Description

**Describe the bug**
Wallet modals fixed to top instead being fixed to bottom. See the screenshots.

**Expected result**
Wallet modals should be displayed at the bottom of the screen.

**Steps to reproduce**
1. Open Superhero wallet on Android device.
2. Open some of the modals shown above on the screenshots.

Environment

Device: Huwawei P40 Lite
Android version: 12.0.0.259
Superhero wallet version:

**Comment by onvisions** [comment]
I confirm that the bug still can be reproduced on my device. Probably the scope of affected users is very limited as no one else from the team could reproduce the bug on their devices. 

Device: Huwawei P40 Lite
Android version: 12.0.0.259
Superhero wallet version:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/670a97fe-690d-4ceb-8a74-4f20c185ce18)

**Comment by smaroudasunicorn** [comment]
Closing as edge case, cannot repro
