### ISSUE TITLE
Device offline Mode - Display proper messages according to wallet connection status. Design reference.

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2449]
https://aeternity-blockchain.atlassian.net/browse/SW-722

Story: Display more informative messages replacing the missing data when SH wallet is offline. Note that this proposed design is a placeholder for offline status messages that can be used in different places according to actual needs. It might be the case that some of the suggested cases are not needed because SH wallet can actually fetch the data or display last available data. Currently the wallet is displaying .chain names, assets and balance even if the device is not connected to the Internet. We should discuss and decide whether we want to keep it this way. @Paolo 

Acceptance criteria: 

Messages (displayed at the bottom of screen) according to wallet connect status:

You are offline. Go online to get real time data.

Unable to connect to the chosen node.

Middleware is offline.

  2. Not connected icon + message to be displayed at the place of missing data such as balance, transactions history, assets or .chain names owned by the account:

Unable to load balance.

Assets list is not available offline.

Transactions history is not available offline.

Names list is not available offline.

  3. “Unable to load balance.” message for the account card.

Design:

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/186d01fd-8135-40d4-884a-e90590a1d574)
https://github.com/superhero-com/superhero-wallet/assets/147718725/9a4882cd-7194-426b-a3d8-fa31f99b8102
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/19ecfe21-89aa-4399-9509-288d9006007b)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/4e519c5c-b26c-48fc-9b3d-a41ca12c2f3b)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/f30192b2-ce71-45ca-affe-30f52209e0f8)

Figma Reference: https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=22724%3A314628&t=mBfGnff3xvTQWXRa-0Connect your Figma account

**Comment by davidyuk** [comment]
I would remove "list" from wording as it is too technical: "Assets list" => "Assets", "Names list" => "Names"
