### ISSUE TITLE
Sorting pending tx in multisig is on bottom, should be on top

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2450]
https://aeternity-blockchain.atlassian.net/browse/SW-1373

Describe the bug

Sorting pending tx in multisig is on bottom, should be on top. Reproducible on the release branch. 

Expected result

Steps to reproduce
1. Initiate multisig tx
2. Check the Tx list 

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/47434fb2-b175-43ef-bb1f-6a5c9248c5f1)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/7ed992b4-7731-44bc-b211-76d15e626c4b)

Environment selector

MacOS
iOS
Web wallet

**Comment by Liubov-crypto** [comment]
More context: 
I sent multisig Tx to one of the multisig vault addresses and the transaction was visible as incoming, not outgoing
and as a result it was hanging somewhere below. 

 If I send it to a third address, then the pending transaction will be at the top in Tx list, as it should be.
