### ISSUE TITLE
Move notification settings from Vuex to composable

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2451]
This task covers the migration of the Notifications Settings from Vuex to a composable. It affects the notification settings page and also the notifications list. Migration of data should be included.

To test the migration we can copy the `state` entry of the current develop version of the app to the PR's app Local Storage.

https://aeternity-blockchain.atlassian.net/browse/SW-1377

**Comment by Liubov-crypto** [comment]
Migration is working good for me. 

I have turned off all notifications in extension and continue to receive notifications:


https://github.com/superhero-com/superhero-wallet/assets/69896204/8fa3f670-967b-47d3-b4d3-bf86e44e45fe

**Comment by Liubov-crypto** [comment]
Fixed, LGTM.
