### ISSUE TITLE
Fix updating DAPP first account change

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2461]
Currently DAPPs that connects to our extension wallet only detects account change if the change does not involve the 1st account. So changing from 1 to 2 or from 2 to 1 does not trigger the update in the DAPP.

The easiest way to test this is to use this tool: https://docs.aeternity.com/aepp-sdk-js/develop/examples/browser/aepp/#

**Comment by dvdbak** [comment]
LGTM
Tested on Chrome and FF extension
