### ISSUE TITLE
Bid history is broken on dev branch

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2483]
**Describe the bug**
Bid history is broken on dev branch. The account address isn't displaying. 

**To Reproduce**
1. Go to Auctions
2. Click on name
3. Choose bid history

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: FF

**Additional context**
Bid history is broken in general. Now it's not displaying an account address. 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/9b057577-df85-4bef-b9bf-2eb13827db3b)
![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/342d4873-3ed3-45e2-b5e5-34a88ec13089)

**Comment by CedrikNikita** [comment]
This issue should be resolved first https://github.com/aeternity/ae_mdw/issues/1590, because none of the mdw endpoints are returning such info right now.

**Comment by Liubov-crypto** [comment]
Not reproducible on the current dev branch. Can be closed.
