### ISSUE TITLE
Move veeValidate rules from Vuex module to separate plugin file

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2484]
This task covers the move of every VeeValidate (library used to validate form fields) rule from the Vuex module to separate file.
To test the task every form input needs to be checked if it validates correctly.

**Comment by peronczyk** [comment]
During the development some rules was removed (for example we had 2 similar rules to validate URLs). Some rules was renamed to maintain consistency. So during the testing the console needs to be checked if there is no error similar to "Missing validation rule: XXX" when opening any form.

The task is ready to be tested @Liubov-crypto

**Comment by Liubov-crypto** [comment]
I tried different forms and found that validation is broken when I'm trying to propose multisig Tx: 


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/159feeaf-08ce-4e00-b4e6-37cbcecd0aab)

@peronczyk please check it

**Comment by peronczyk** [comment]
Fixed. Please retest @Liubov-crypto

**Comment by Liubov-crypto** [comment]
The issue has been fixed, LGTM.
