### ISSUE TITLE
Display unread notifications when first opening the notifications page

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2490]
Currently our notifications logic is written in a way, that the notifications page displays only the already read messages. So when first opening the notifications page some notifications can be hidden (for example the seed backed up message). After closing and opening the page again it will be visible.

The fix should cause the new notifications be visible at first opening the notifications page.

**Comment by Liubov-crypto** [comment]
It works good with superhero(.)com and the main wallet account. 
I tried to receive some new notifications when switched between wallet subaccounts, and it seems not updating properly. When I'm leaving some comments I will not receive any notifications. @peronczyk could you please check it?

**Comment by CedrikNikita** [comment]
fixed in https://github.com/superhero-com/superhero-wallet/pull/2715
