### ISSUE TITLE
Id tag for prefix bc not found

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2495]
**Describe the bug**
I got this popup message "Id tag for prefix bc not found" when I was moving to BTC accounts in my wallet.

**To Reproduce**
1. Open wallet
2. Swipe to btc account in mainnet
3. See error

**Expected behavior**
User shouldn't receive such popup. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: FF 
 - Version: 119.0

**Additional context**
Reproducible on the development branch. 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/42a45003-dc1d-4127-b758-8f476ecdf24c)

**Comment by dvdbak** [comment]
@CedrikNikita Can you check if it is reproducible?

**Comment by smaroudasunicorn** [comment]
@Liubov-crypto check and if it is there assign it to Nikita

**Comment by Liubov-crypto** [comment]
Not reproducible for me on dev branch. Can be closed.
