### ISSUE TITLE
Move the account address validation to the protocol adapter

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2499]
Currently each protocol has its own file for some random utilities. There is no schema for those files, but all protocols needs the account address validation function.

### The task is about:

1. Making the account address validation utility function required for each protocol adapter so we have clear schema for this
2. Creating a method within the `ProtocolAdapterFactory` that would return protocol adapter based on the account address passed as an argument.
3. Fixing the `NaN` balances for the mocked up ETH accounts

### Testing

There are 2 things to test within the task:
1. If all protocol specific views (besides ETH as this will be added in next task) are loading properly: account details, all subpages and send/receive modals.
2. Account address validation when sending coins for every protocol

**Comment by peronczyk** [comment]
The task is ready to be tested @Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM
