### ISSUE TITLE
ui: support ERC-20 in asset list on account detail screen

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2532]
This task covers only the list of the tokens for the Ethereum protocol. The details page will be covered by separate task.
Also this task does not cover the logic of retrieving the real ETH fungible tokens. SO only dummy data is displayed for the ETH protocol.

**Comment by peronczyk** [comment]
This task required extensive changes in the architecture of the fungible tokens. For now we are displaying only one dummy token within the ETH accounts. But whole app logic that is using the fungible tokens should be tested.

**Comment by Liubov-crypto** [comment]
Idk, if it was touched, but  I've send 0.1 WAE/WTT, but I see the amount in Tx details as 0 WAE/WTT, Tx: https://aescan.io/transactions/th_2whz7TCFjN4UbP6xW7dQh9i35u4AvPpJxmn45i4qY6YpQo4Nq5

also Tx marked with tags as Spend In but should be Spend Out. 


https://github.com/superhero-com/superhero-wallet/assets/69896204/39dbfe98-267e-4a92-9b52-6c20c82febb3


Here I have send 1 WTT but see it as 0 WTT: https://aescan.io/transactions/th_2fw6HGHSdk2neTZ9R5xn3jYafuRc2h6tPFpHyxzPfZHoWSvuRa

(as I understand explorer also displays wrong FT amount)

@peronczyk please check it.

**Comment by Liubov-crypto** [comment]
LGTM
