### ISSUE TITLE
ui: support ERC-20 in the QR scanner

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#2535]

**Comment by Liubov-crypto** [comment]
I've found that QR scanner doesn't work normally in Safari browser (mobile and web) it shows broken screen in mob browser and grey screen in web. 
@martinkaintas please check it: 


https://github.com/superhero-com/superhero-wallet/assets/69896204/39779883-47b5-4cc2-91cc-ab5d617bc8ed



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/eac63608-c31c-4cf6-8f8c-bee2376275ff)



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/aa9c9318-533c-41d1-ad43-61ca0310f6ab)

**Comment by Liubov-crypto** [comment]
> I've found that QR scanner doesn't work normally in Safari browser (mobile and web) it shows broken screen in mob browser and grey screen in web. @martinkaintas please check it:
> 
>  2023-12-12.12.04.57.mp4 
> ![Image](https://private-user-images.githubusercontent.com/69896204/289821654-eac63608-c31c-4cf6-8f8c-bee2376275ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzQ1ODIsIm5iZiI6MTcwMjQ3NDI4MiwicGF0aCI6Ii82OTg5NjIwNC8yODk4MjE2NTQtZWFjNjM2MDgtYzMxYy00Y2Y2LThmOGMtYmVlMjM3NjI3NWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDEzMzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZTg3MWQzODA2NDMwZjRmOGEyZjQ0OTA4MzI0N2QzOGNmYzY3NzRlZGY2YWJkNDlmNjk3Y2VmYjgyNzZiNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f9fvxVBOonvJW-tKILKSDKOa9j06JzAZAd3iGDdP9MU)
> 
> ![Image](https://private-user-images.githubusercontent.com/69896204/289821669-aa9c9318-533c-41d1-ad43-61ca0310f6ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzQ1ODIsIm5iZiI6MTcwMjQ3NDI4MiwicGF0aCI6Ii82OTg5NjIwNC8yODk4MjE2NjktYWE5YzkzMTgtNTMzYy00MWQxLWFkNDMtNjFjYTAzMTBmNmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDEzMzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZjVhNjQ0YjFlMjk1ZDQ5MjI5ZjZiMThlZmNhYzMxNTk0MzJiNjBlOGU0YTllNjk1NTM2NTcyMWJiMmI5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J1iWgNlDm68mPuKR5e1qAWvpio38A0xYwFURyyFw8Pc)

The same issue with scanner QR code is reproducible on dev branch. I will register it separately.
