### ISSUE TITLE
Opening Send ETH modal is causing error in console

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2536]
**Describe the bug**
Opening Send ETH modal is causing error in console. Also I can see many other errors that may slow the wallet.

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/d2635f01-0f63-4524-8520-a9f44783f84c)
![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/6a814f1e-cca8-43c5-a4c1-f4d5f3cf6e03)

**To Reproduce**
1. Go to ETH account
2. Click on Send ETH modal
3. Open console

**Expected behavior**
Should act without errors 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, FF
 - Version 119

**Additional context**
Reproducible on the dev ETH branch: https://feat-eth-support.wallet.z52da5wt.xyz/account

**Comment by martinkaintas** [comment]
Errors from the second screenshot are caused by the backend being down

**Comment by Liubov-crypto** [comment]
Not reproducible for me on eth dev branch.
