### ISSUE TITLE
TypeError: `target` argument of Reflect.get must be an object, got (void 0)

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2540]
**Describe the bug**
When I'm switching between different accounts in my wallet ae--> btc--> eth, I'm getting this error in console: TypeError: `target` argument of Reflect.get must be an object, got (void 0) 

**To Reproduce**
1. Open the wallet
2. Swipe between accounts 
3. Open console

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version 119

**Additional context**
Reproducible on the current dev branch: https://develop.wallet.z52da5wt.xyz/ and in some ETH support related prs. 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/ab7afcfd-90c8-4724-bdd3-82d241a47c68)

**Comment by davidyuk** [comment]
the error message will be improved on sdk side after fixing https://github.com/aeternity/aepp-sdk-js/issues/1927
