### ISSUE TITLE
Deep link does not open normally if the app is running on Android

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2554]
**Describe the bug**
Deep link does not open normally if the app is running on Android, ios apps. 

**To Reproduce**
1. Open app
2. Click on Dex link
3. try to connect app with dex

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android, ios 
 - OS: Android, ios

**Additional context**
Reproducible on dev branch.

**Comment by CedrikNikita** [comment]
Also if the user have an app opened on Settings, for example, the header will break.
![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/b197565e-d984-434d-93ad-1e0fdc8e3cd9)
