### ISSUE TITLE
Fix restoring the networks when reopening the extension popup

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2557]
The isse is well described here:
[Fixes #2541](https://github.com/superhero-com/superhero-wallet/issues/2541)

Easy way to test the issue is to monitor the balances. If we open the extension on the mainnet we should see the balance equal to X. If we switch the network to testnet the balance should update to Y. Then if we close the extension and reopen it the balance will be displaying X (mainnet value) but the network indicator would display "Testnet".

This task fixes this.

**Comment by Liubov-crypto** [comment]
LGTM
