### ISSUE TITLE
Header is missing after sending Tx within the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2563]
**Describe the bug**
if user send tokens from the 1st account to the 2nd one inside the wallet, and then open the transaction details, the header disappears

**To Reproduce**
1. Send ae coin from 1st acc to 2nd acc
2. Check tx details
3. Go back

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version 119

**Additional context**
reproducible on the dev branch. 

https://github.com/superhero-com/superhero-wallet/assets/69896204/92562a07-54ac-449d-b11e-5cc0a7ae9357

**Comment by CedrikNikita** [comment]
I cannot reproduce this issue. Now instead of missing header, for a millisecond header appears on clicking back button.

**Comment by Liubov-crypto** [comment]
Reproducible for me in FF extension dev branch a194bd8 
![rep](https://github.com/superhero-com/superhero-wallet/assets/69896204/37e2375a-4db1-416e-9952-43a7d04e8ecc)

https://github.com/superhero-com/superhero-wallet/assets/69896204/317a5804-358f-4fac-bb92-70c85f7d6f88
