### ISSUE TITLE
In-app browser stop responding after performing a transaction

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2571]
**Describe the bug**
In-app browser stop responding after performing a transaction, for example swap on DEX, the screen is becoming black

**To Reproduce**
1. Go to DEX in-app browser and connect the wallet
2. Click on Swap
3. Choose the pair and click on Confirm

**Expected behavior**
Should work normally

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  iPhone13
 - OS:  iOS 17.1.2

**Additional context**
Reproducible on iOS app 2.1.3(1)

https://github.com/superhero-com/superhero-wallet/assets/69896204/a9011e1b-3af5-40e7-9775-95ffe90b8587

**Comment by martinkaintas** [comment]
We can fix this issue on our side by initializing the CompilerHTTP but the CompilerHttp has been deprecated.
Same functionalities available using the JS lib https://github.com/aeternity/aepp-calldata-js
This issue should probably be fixed in the DEX

**Comment by Liubov-crypto** [comment]
I tried to do a swap a couple of times. It was successful except 1 attempt. 
I think this issue can be closed.
