### ISSUE TITLE
Bitcoin transactions from the testnet are visible in the mainnet

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2573]
**Describe the bug**
Bitcoin transactions from the testnet are visible in the mainnet.  After click on it the screen becomes black and wallet stop responding. 

Also, the connection to the test network is very slow and after connecting I can see information from the main network (names, balances) in the test network. After some time, it is updated correctly.

**To Reproduce**
1. Perform BTC transaction in the testnet
2. Switch to mainnet
3. Click on BTC transaction on the latest Tx widget

**Expected behavior**
Transactions from the testnet shouldn't be visible in the mainnet

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS:  iOS 17.1.2

**Additional context**
Reproducible on iOS app 2.1.3

https://github.com/superhero-com/superhero-wallet/assets/69896204/3a575d09-4421-4717-a3ce-9baccff4a669

**Comment by CedrikNikita** [comment]
Unable to reproduce it on Android version 2.1.2 of the app.

**Comment by dvdbak** [comment]
@Liubov-crypto Plz recheck the bug

**Comment by Liubov-crypto** [comment]
Not reproducible for me on iOS app v.2.1.2 commit 18bc1d6. Can be closed.
