### ISSUE TITLE
QR scanner doesn't work normally in Safari browser (mobile and web)

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2576]
**Describe the bug**
I've found that QR scanner doesn't work normally in Safari browser (mobile and web) it shows broken screen in mob browser and grey screen in web.

**To Reproduce**
1. Go to Send modal
2. Click on Scan QR 
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari 
 - Version 17.1 (17616.2.9.11.9, 17616)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 17.1.2
 - Browser  safari
 - Version 17.1.2

**Additional context**
Reproducible on dev branch. 

https://github.com/superhero-com/superhero-wallet/assets/69896204/7f722638-6c79-4974-b237-bd5844129cdc

**Comment by smaroudasunicorn** [comment]
May you help since this is a mac issue?

**Comment by smaroudasunicorn** [comment]
@Liubov-crypto may you test it again?

**Comment by Liubov-crypto** [comment]
@smaroudasunicorn I finally found the root of this issue: user need to give full access to the camera in the settings, if access is set to Ask - and the user confirms the use of the camera, then nothing will happen, there will only be an endless loading of the screen
but if user set full access then everything is working as expected.

**Comment by peronczyk** [comment]
I did big refactoring of the QR scanner modal and the logic that allows to scan the QR codes on mobile, extension and web. I suggest to perform testing for each of the cases @Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM
