### ISSUE TITLE
Unify protocol and token icon sizes

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2578]
Currently the icons displayed on the account details asset list are not equal. The protocol icon used as the coin icon has different size (smaller) than the token sizes:

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/308a8d2b-9f53-4ad4-b00e-928cd37774ce)

The icon sizes should be the same and match the figma designs: **18px**.

**Comment by Liubov-crypto** [comment]
I think there is still a difference in icon sizes, protocol icon size is looking smaller than token icon size, even circle diameter is different 20x20 for protocol icon, and 24x24 for token icon: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/06c03544-64fd-444d-905d-1c75d7a2c0a4


but correct me if I'm wrong.

**Comment by martinkaintas** [comment]
The issue was here, it was that the icon for AE Coin was smaller than the icons of the tokens
![image](https://github.com/superhero-com/superhero-wallet/assets/49337371/1b590d99-94ad-475b-a3c9-3a68d5d9475a)

**Comment by Liubov-crypto** [comment]
In that case LGTM

**Comment by martinkaintas** [comment]
closed in #2619
