### ISSUE TITLE
ETH / BTC icon is displaying wrong in Tx details page

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2579]
**Describe the bug**
ETH / BTC icon is displaying wrong in Tx details page

**To Reproduce**
1. Open Tx details page
2. Check ETH / BTC icon 
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser FF
 - Version 119

**Additional context**
Reproducible on ETH dev branch.

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/ac255103-3f32-4930-a45d-1b137d3ed8fb)

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/bfa1963c-4be6-4474-b2b3-8ecd7e88d2fa)

**Comment by Liubov-crypto** [comment]
I'm still seeing wrong BTC/ETH icons on eth dev branch, commit b182d50 :

https://github.com/superhero-com/superhero-wallet/assets/69896204/d87605ef-9c10-4971-91a3-bed4be217447

**Comment by martinkaintas** [comment]
I PR was not linked correctly, please check it here #2610

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
