### ISSUE TITLE
Fallback names for AE transaction tokens

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2582]
In case the API (middleware) returns transactions without  the transaction `function` field the tokens displayed for the transactions are often bugged and the "AE Coin" name is displayed instead.

The task is about using the token `contractId` to find the fungible token and display its name in this case.

**Comment by peronczyk** [comment]
The best way to test this task is to to view the transaction list and transaction details for "WAE/WTT" transfer.

IMPORTANT: This task does not fix issues with disappearing amount. This will be fixed within separate task.

@Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM
