### ISSUE TITLE
ui: support ERC-20 assets details

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2586]
This task covers following topics:
1. Displaying the list of top 50 ERC-20 tokens on the ETH account details => Assets page. The balance is not properly calculated so there will be another task that would cover the balances. Please note that the API we use for fetching is free and is limited to certain amount of calls per minute. If this amount is exceeded next call to API will cause the list to disappear and leave only the ETH coin. I created a task for this: https://github.com/superhero-com/superhero-wallet/issues/2591. But for now this is an "issue" we agree to have for the sake of the MVP.
2. Displaying the ETH coin details
3. Displaying the ERC-20 token details

During the tests please take a look on the AE asset list and details as there was a lot of changes that also affects different protocols.

**Comment by peronczyk** [comment]
Task is ready to test @Liubov-crypto

**Comment by Liubov-crypto** [comment]
During my testing I was able to see ETH coin details and also AE asset list and details. In general LGTM. 

But I was not able to get and see any ERC-20 tokens. I tried a couple faucets to get them, but without a result. maybe you can send me some ERC-20 tokens for testing? 
0x6e503e467AE5A50A135AECBf03e93E97D7B25461

**Comment by Liubov-crypto** [comment]
Finally I have managed to transfer ERC-20 token to my wallet address: https://sepolia.etherscan.io/tx/0x23bdcbe3187d406497eb941c4d3c48056f99a6363b31f85134ad8a9d809c0318
but still can't see it in my assets list. Maybe it has to take more time to be shown in the wallet...

**Comment by Liubov-crypto** [comment]
I can see list of ERC-20 tokens in my wallet and details. In general LGTM. 

I have a question about redirection from token details page, for example the first token OKB in my list: https://sepolia.etherscan.io/tx/0x3f4b6664338f23d2397c953f2ab4ce8031663f80 

I will get an error: Oops! An invalid Txn hash has been entered:

0x3f4b6664338f23d2397c953f2ab4ce8031663f80 
but I assume this is 3rd party service...

**Comment by peronczyk** [comment]
Regarding opening the explorer link I found it was a bug. I fixed it. Please check again @Liubov-crypto
