### ISSUE TITLE
Same balance is used for next/previous account card when swiping

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2587]
Currently when user is swiping the account cards on the dashboard the amount of token displayed on the active card is duplicated on the next and previous card. So if half of the next/previous card is visible it displays wrong balance. The reason is that the account card balances are all equal to the balance of the active account balance.

The goal is to display the balance of the card's account, not the active account balance.

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/0f2a735d-f45c-4c07-8006-5d1216c8f40f)

**Comment by Liubov-crypto** [comment]
LGTM
