### ISSUE TITLE
Display only owned ERC-20 tokens on the assets list

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2596]
The list of ETH assets should be narrowed to the tokens that user owns (has the balance greater than 0).

**Comment by peronczyk** [comment]
I also added new field in the token details: the name of the token:


![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/4c45f78f-c029-4ec1-bf1e-a6260ac65517)

@onvisions what do you think about this?

**Comment by onvisions** [comment]
Good improvement. Approved on my side. Other wallets also display the full token name. We should apply the same for coins as well.

**Comment by Liubov-crypto** [comment]
LGTM
