### ISSUE TITLE
Easy way of switching between accounts and account counter

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2602]
The goal of this task is:
1. making it easier to switch between dozens of accounts,
2. displaying the amount of available accounts,
3. displaying the number of the active account.

My idea is to have a button that displays the `X / Y` (eg.: 6 / 23) somewhere in the dashboard. Clicking this button would open a list of accounts. This button should be visible only if user has more than 6 accounts. See following screens:

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/6e956a1d-f4f5-4946-87da-43e8aab15a10)

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/6897d052-411d-4729-b6ec-5d5cb2bb0533)

Future idea (not implemented within this task):
We can go even further with this and change the way how we switch between regular accounts and the multisig:

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/7e0086af-2448-4536-8e31-ba7b1cb288cd)

@paolomolo @smaroudas @onvisions

**Comment by peronczyk** [comment]
The demo is available here: https://feat-dashboard-account-counter-and-switcher.wallet.z52da5wt.xyz/

**Comment by peronczyk** [comment]
I had a conversation with @onvisions regarding the final visual tweaks. All his suggestions were implemented.

This task is ready to be tested @Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM. 

I found one issue, but it's reproducible on dev branch too, will add it to our backlog.
