### ISSUE TITLE
Can't fully delete a custom permission, they will stay in the wallet history

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#2621]
https://aeternity-blockchain.atlassian.net/browse/SW-1355

Describe the bug

if I add a custom permission then delete it, then click on Add custom permission again I will see previous deleted permission. 

Reproducible on the dev branch. 

Expected result

Steps to reproduce
1. Add custom permission
2. Delete it

3. Click on add custom permission

Reproducible on the [Merge pull request #2458 from superhero-com/feature/update-dependencies · superhero-com/superhero-wallet@edf9b61](https://github.com/aeternity/superhero-wallet/commit/edf9b6171e96aca793bfb54902396e388f3b24aa)

Environment selector

Chrome
Extension
Firefox
MacOS
Web wallet

https://github.com/superhero-com/superhero-wallet/assets/147718725/8ace4888-f690-4f6f-8648-c2404e5b852d

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
