### ISSUE TITLE
Search transaction by contract address is not working

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#2630]
https://aeternity-blockchain.atlassian.net/browse/SW-1122

Describe the bug

Search transaction by contract address is not working on dev and product

Expected result

Should match search results

Steps to reproduce
1. Enter contract address in the search line in Transaction section
2. Observe an issue 

Environment selector
Extension
Firefox
MacOS
Web wallet

https://github.com/superhero-com/superhero-wallet/assets/147718725/dd9571aa-58a9-4757-8b84-f7d1959eae27

**Comment by Liubov-crypto** [comment]
Fixed, can be closed.
