### ISSUE TITLE
Fix input field value when it has over 40 symbols

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#2638]
https://aeternity-blockchain.atlassian.net/browse/SW-367

*Describe the bug*
When I enter 40 symbols into the input field (Send, Receive, Invite) then the value will be 0$.

*Expected result*
The amount must match the input.

*Steps to reproduce*
1. Open the wallet
2. Enter 40 or more symbols into the input field (Send, Receive, Invite)
3. See the result

Environment

Reproducible on the development branch in Safari browser ver. 12.6, FF, Chrome, on web wallet, and extension as well. 

**Comment**
Liubov Sharga 
November 28, 2022 at 6:03 PM

 @Marcin Olszewski  I retested this issue on the current development branch and found that: 

If I enter more than 23 symbols on Receive modal in the Input field then the value will become 0$. Reproducible on web wallet and extension in FF, Chrome, and Safari browsers. 

2.  If I enter more than 40 symbols on Send modal in the Input field then the value will become 0$. Reproducible on web wallet and extension in FF, Chrome, and Safari browsers.

3. If I enter more than 40 symbols on the Invite modal in the Input field then the value will become 0$. Reproducible on web wallet and extension in FF, Chrome, and Safari browsers.

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/e021cc4f-b883-4769-840f-748e79bf429d)

**Comment by Liubov-crypto** [comment]
Not reproducible for me as well on dev branch
