### ISSUE TITLE
Incorrect AE amounts are being displayed for non-classified contract calls

### ISSUE THREAD

**Issue by dvdbak** [superhero-com/superhero-wallet#2642]
https://aeternity-blockchain.atlassian.net/browse/SW-1113

If there is a token transfer with an unlisted contract entry point like in this case distribute [æScan - æternity Blockchain Explorer](https://aescan.io/transactions/th_rwE51Ven8MXwBfyhi37a4y5QNYosfuZzSL3FPz7HcKPQ17uKi) 

The wallet shows the token amount as an AE transfer.

Expected result: Wallet shall display the correct AE value in the transfer
(Feature request: Wallet shall display the actual token transfer amount just like DEX transactions)

**Comments**

Subhod Iranthabettu 
August 7, 2023 at 6:54 PM

Just to clarify, the title unlisted refers to the endpoint, not the contract. The listed ones are here https://github.com/aeternity/superhero-wallet/blob/dbc6b8270805112ee14b902471a7cbdab600c600/src/popup/utils/constants.ts#L49

method distribute is not listed here. So for any such methods, SH wallet shouldn’t assume it’s AE.

Marco Walz 
August 7, 2023 at 5:09 PM

I am not sure if this is related to an “unlisted” (non-standard) entrypoint.

one issue we currently have is that the contract for which this issue has been reported, is not classified as AEX-9 token contract yet. this should be solved soon and you can check with by this URL:

https://mainnet.aeternity.io/mdw/v2/aex9/ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt

not found should disappear then.

I will also ask the reporter of the issue to check the tx history again after contract is classified as AEX-9

**Comment by CedrikNikita** [comment]
Currently our wallet supports only AEX-9 token to be shown as token. As far as i know this contact is already classified  as AEX-9 token. I think we can close this issue for now. Feel free to reopen this issue, if something else is missing.
