### ISSUE TITLE
V3 transactions error

### ISSUE THREAD

**Issue by dvdbak** [superhero-com/superhero-wallet#2643]
https://aeternity-blockchain.atlassian.net/browse/SW-1006

Describe the bug

I approved a multisig transaction in one wallet and sent it from the second one.

But in the first one I got this error: V3 transactions error.

However transaction went well.

Expected result

Should work smoothly 

Steps to reproduce
1. Create vault
2. Initiate Tx
3. Top up vault
4. Sign Tx in second wallet 
5. Send Tx from the 1st wallet 
6. Observe an issue

Environment selector
- Firefox
- MacOS
- iOS
- Web wallet

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/7d222ca4-9f50-41ea-bb1b-1e47e710e701)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/14aad54e-b672-4eff-889b-962158a860eb)

**Comment by dvdbak** [comment]
@Liubov-crypto  can you check again at which point the issue appears

**Comment by Liubov-crypto** [comment]
Not reproducible for me on the latest dev branch. Can be closed.
