### ISSUE TITLE
After refreshing Tx details page transaction is changing its direction

### ISSUE THREAD

**Issue by dvdbak** [superhero-com/superhero-wallet#2646]
https://aeternity-blockchain.atlassian.net/browse/SW-1117

Describe the bug

After refreshing Tx details page transaction is changing its direction from wrong to normal. Reproducible on dev branch and product. 

Expected result

Steps to reproduce
1. Send tokens from acc1 to acc2 in your wallet
2. Go to Latest Tx page 

3. Choose Tx, click on details and refresh

Environment selector

- Extension
- Firefox
- MacOS
- Web wallet

**Comment by Liubov-crypto** [comment]
The transaction is changing it's labels: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/0b9ee5c2-6421-499b-a350-909a90856b4a

Idk, if it's critical and if user will do refreshing a page after submitting Tx.

**Comment by Liubov-crypto** [comment]
Now it's not reproducible on the current dev branch for me. Can be closed.
