### ISSUE TITLE
AENS Bid history page is broken

### ISSUE THREAD

**Issue by dvdbak** [superhero-com/superhero-wallet#2651]
https://aeternity-blockchain.atlassian.net/browse/SW-1257

**Describe the bug**

On Bid history page are not displaying the full history of bids. Example: https://develop.wallet.z52da5wt.xyz/account-details/names/auctions/coolname.chain/history 

 

**Steps to reproduce**
1. Choose a name
2. Check Bid history page

**Environment selector**

Chrome
Extension
Firefox
MacOS
iOS
Web wallet

**Comment by dvdbak** [comment]
@CedrikNikita To recheck with MDW team about the status.

**Comment by CedrikNikita** [comment]
https://github.com/aeternity/ae_mdw/issues/1666
