### ISSUE TITLE
Wrong labels on multisig Tx details page

### ISSUE THREAD

**Issue by dvdbak** [superhero-com/superhero-wallet#2652]
https://aeternity-blockchain.atlassian.net/browse/SW-1338

**Describe the bug**

Incoming multisig Tx is marked as Spend Out in details. 

hash: th_Xj9WegpmAcfHzC3wtbGjhLHPRHzRQJeuXKLeUZMPE7Z8fZRr6

**Expected result**

Should be marked as Spend In. 

Steps to reproduce
1. Open incoming Tx
2. Compare labels

**Environment selector**

- Firefox
- MacOS
- Web wallet

https://github.com/superhero-com/superhero-wallet/assets/147718725/0fba28df-99c7-4a22-9cf4-9bbf36fc2e19

**Comment by Liubov-crypto** [comment]
Not reproducible for me on the current dev branch. Can be closed.
