### ISSUE TITLE
An error with displaying the multisig transaction amount on development branch

### ISSUE THREAD

**Issue by dvdbak** [superhero-com/superhero-wallet#2653]
https://aeternity-blockchain.atlassian.net/browse/SW-1302

Describe the bug

The proposed multisig Tx is displaying as received, however it should display as Sent.

Expected result

it should display as Sent with minus amount. 

Steps to reproduce
1. Propose multisig Tx
2. Check the details

Environment selector

Extension
Firefox
MacOS
Web wallet

https://github.com/superhero-com/superhero-wallet/assets/147718725/023d58c7-3474-4aeb-b9e9-9b342a4cc19f

**Comment by Liubov-crypto** [comment]
Not reproducible for me on the current dev branch. Can be closed.
