### ISSUE TITLE
Add a meta description

### ISSUE THREAD

**Issue by CedrikNikita** [superhero-com/superhero-wallet#2661]
https://developer.chrome.com/docs/lighthouse/seo/meta-description?hl=en

**Comment by onvisions** [comment]
> "Superhero is a multi-blockchain wallet to manage crypto assets and navigate the web3 and DeFi space. Powered by æternity."

Right. I agree although my idea was to emphasize that our product is not just "a wallet" (one of many) but "THE wallet" ... :)
