### ISSUE TITLE
Ethereum Dapps Support (MVP)

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#2664]
We would like to be able to integrate SH Wallet with Ethereum dapps through Wallet Connect.

Sample https://app.uniswap.org/swap

We want to have the same UI as it is with inapp browser existing capability.

**Comment by Liubov-crypto** [comment]
Connection is working fine for me , except FF ext/web (but this is known issue with scan qr and present on dev). The rest LGTM
