### ISSUE TITLE
Immediately add pending ETH transaction after sending

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#2670]

**Comment by Liubov-crypto** [comment]
Tested in testnet: I can see immediately ETH Tx that I send in my sender wallet. But I can't see the same tx in pending status in my recipient's wallet, to see it I have to refresh the page. Is this expected?

**Comment by Liubov-crypto** [comment]
The Transaction appears with some delay in Recipients wallet, but in general LGTM. I assume that delay is connected to fetching Txs using free Eth API (correct me if I'm wrong). But I think we can proceed with this pr.

**Comment by martinkaintas** [comment]
closed in #2695
