### ISSUE TITLE
Display unrecognized token if the transaction uses unrecognized token contract ID

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2673]

**Comment by onvisions** [comment]
**Design:**
![unrecognized](https://github.com/superhero-com/superhero-wallet/assets/12225410/b352ac05-9ba0-4d77-94d0-02eee982df6e)

**Figma reference:** https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=28590-156936&mode=design&t=lXbRSLBHz4SWNV8j-0

**Comment by peronczyk** [comment]
The list of the applied changes is available here: https://github.com/superhero-com/superhero-wallet/pull/2746#issue-2151403611

**Comment by peronczyk** [comment]
I have applied fix for the issue by creating new component that takes care of displaying the rounded cards with dark background. It is now used on following screens:

1. Dashboard Latest Transactions
2. Multisig Dashboard latest Transactions
3. More / About page - displaying the table. Please test if it looks the same as on dev.

**Comment by Liubov-crypto** [comment]
I found a couple of differences here, @peronczyk please check it: 

1. WAE symbol is different for this token, but in 1st case it's sent Tx and in 2nd - allow token:

https://github.com/superhero-com/superhero-wallet/assets/69896204/c24c065a-9a3c-4e46-8494-f04366f007fb


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/c7163044-6a11-40a5-aefd-0550169805bd)


2. Assets are not visible in assets selector list (they are visible on dev branch): 


https://github.com/superhero-com/superhero-wallet/assets/69896204/b5f32dd4-5adc-4e08-b34f-d0da8c08916f


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/d5b60d0b-c4e2-4c3f-9047-f33892ce3cf9)


3. Proposed Tx are not visible in the latest Tx list (on dev it's visible): 

https://github.com/superhero-com/superhero-wallet/assets/69896204/f8d9be3f-33ec-4fc2-ac77-b8ce6037bd6f

**Comment by peronczyk** [comment]
I have pushed some updates and fixes. Please retest @Liubov-crypto 
Please also focus on the token icons - the sizes and if correct icons are displayed next to the token name.
Also there is a fix for this task: https://github.com/superhero-com/superhero-wallet/issues/2781

**Comment by Liubov-crypto** [comment]
1  and 2 issues have been fixed. 

Now issues with visibility of multisig pending Tx are reproducible also on dev branch, I will log it separately. 

I've found a new issue on multisig tx details page, there is absent sum and coin (it's visible on dev): 



https://github.com/superhero-com/superhero-wallet/assets/69896204/5be1df0a-3ae3-4352-b357-74685df64205



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/ace963ce-cb59-45af-ab95-91d689302cf5)

@peronczyk please check it

**Comment by peronczyk** [comment]
@Liubov-crypto fixed. Please retest.

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
