### ISSUE TITLE
The total sum of ERC-20 tokens is displaying wrong in Tx details

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2674]
**Describe the bug**
The total sum is displaying wrong in Tx details. I was sending 0,01 Link, but I see in Tx details only fee 0.002522833 ETH and no total amount. 

**To Reproduce**
1. Go to Eth account
2. Send Erc-20 token
3. Check the Tx details

**Expected behavior**
The total amount should be shown as sent sum + fee

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF, Chrome
 - Version 122

**Additional context**

https://github.com/superhero-com/superhero-wallet/assets/69896204/37918635-2d3e-46fa-aa5c-2b083e4deac9

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/718ddad1-543f-4b67-94ef-36cdf26a4cd9)

**Comment by onvisions** [comment]
1. As basics we should display Amount, Gas price, Gas used, Transaction fee...
+ Total (what we are currently missing).

2. For ETH it might have sense to display all the info that Metamask shows (see Liubov's screenshot above). It depends how easy it is to implement it. 

3. From the average user perspective all this info (displayed in Metamask) is obsolete IMO. Furthermore you can always use the link to transaction in blockchain explorer where you will have all the details. My suggestion will be to stick to the info we currently display for token transactions on aeternity but add the **Total** at the end.

**By the way, don't you think it will be better to have the total for ALL transactions? It just makes sense:**
- Amount
- Fee
- Total. 

Furthermore we now display additionally **Gas price** and **Gas used** for contract calls and for tokens but we don't show it for AE coin transactions. Why? Shouldn't we just stick to the same template for all transactions for consistency.

**Comment by CedrikNikita** [comment]
> Furthermore we now display additionally **Gas price** and **Gas used** for contract calls and for tokens but we don't show it for AE coin transactions. Why? 

Because there is no such thing as `Gas` for the `spendTx`

**Comment by onvisions** [comment]
> > Furthermore we now display additionally **Gas price** and **Gas used** for contract calls and for tokens but we don't show it for AE coin transactions. Why?
> 
> Because there is no such thing as `Gas` for the `spendTx`. `Gas` is used only for the contracts.

Isn't it different then for Ethereum transactions as you pay gas for sending too?

**Comment by onvisions** [comment]
> > Furthermore we now display additionally **Gas price** and **Gas used** for contract calls and for tokens but we don't show it for AE coin transactions. Why?
> 
> Because there is no such thing as `Gas` for the `spendTx`. `Gas` is used only for the contracts.

What about the screenshot above? User is sending 0.10 Davidyuk tokens. Details include "Gas used" for the transaction.

**Comment by CedrikNikita** [comment]
This is technically  a `ContractCallTx`. And user is calling `transfer` method of a fungible contract.
