### ISSUE TITLE
Consider set black background in Android 34 API splashscreen

### ISSUE THREAD

**Issue by davidyuk** [superhero-com/superhero-wallet#2686]
<img width="50%" src="https://github.com/superhero-com/superhero-wallet/assets/9007851/545e03b9-c2a6-4957-a113-d4771e1fc23b" />

Also the logo can be a bit bigger.

**Comment by davidyuk** [comment]
The status bar and navigation bar can be colored as well.

<img src="https://github.com/superhero-com/superhero-wallet/assets/9007851/70ccaad7-db47-42c6-8f84-eb7d3eb27c4b" width="50%" />

**Comment by martinkaintas** [comment]
Splash screen is now black, see #2656

**Comment by davidyuk** [comment]
You also can make it the same black as logo background to hide the circle around logo 🤷‍♀️

**Comment by CedrikNikita** [comment]
fixed in #2656
