### ISSUE TITLE
Background page synchronization bug

### ISSUE THREAD

**Issue by CedrikNikita** [superhero-com/superhero-wallet#2713]
**On develop**
It seems that background page unaware of the current mnemonic (or maybe the whole state). This results in popup being unauthorized, and trying to authorize itself. 
![extension Synchonization bug](https://github.com/superhero-com/superhero-wallet/assets/9008074/b0a4ed2b-9696-4a23-a7bd-d07d9cd8503c)

**Comment by Liubov-crypto** [comment]
Got the same bug on develop too.
