### ISSUE TITLE
Stop using placeholder methods and set methods as not required on the BaseProtocolAdapter

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#2721]

**Comment by Liubov-crypto** [comment]
In general LGTM. 

I have a question: 

why pending BTC tx is appearing in Tx list with delay?  it has been showing in latest tx list immediately, but I see it in BTC account tx list with delay in 2-3 min. 


https://github.com/superhero-com/superhero-wallet/assets/69896204/26e50261-51bf-4868-9ee6-d200f23162cb

and in recipients wallet it shows this Tx as pending in BTC acc Tx list, however it's received 11 min ago...


https://github.com/superhero-com/superhero-wallet/assets/69896204/c00fbb4e-0c0d-41d3-9f67-a4adaf1def60
