### ISSUE TITLE
Watcher in `PendingMultisigTransaction` composable is not working

### ISSUE THREAD

**Issue by CedrikNikita** [superhero-com/superhero-wallet#2743]
Reproducible at `feat/eth-support`

In order to reproduce:
1) Create a proposal
2) Go to the proposal details
3) Refresh the page
4) Return to the multisig dashboard
5) Observe that proposal card would be active for every multisig account

This line will not allow the composable to set the watcher, when user will leave the proposal details page
https://github.com/superhero-com/superhero-wallet/blob/feat/eth-support/src/composables/pendingMultisigTransaction.ts#L192

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/5b9a731c-d1a2-43d9-9e8f-88f418b24c9e)

**Comment by peronczyk** [comment]
Additional bug that I found is that if two neighboring account has open transaction the amount displayed on the latest multisig transaction widget is not updating when switching between those accounts.

The task is now open for review and QA @Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM
