### ISSUE TITLE
After revoking multisig Tx, pending Tx is still visible in vault

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2751]
**Describe the bug**
After I revoke multisig Tx, pending Tx is still visible in vault

**To Reproduce**
1. Propose multisig Tx
2. Revoke it
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version 122

**Additional context**

https://github.com/superhero-com/superhero-wallet/assets/69896204/d54958eb-971b-469b-9752-e9740fe3c8b3

![cval](https://github.com/superhero-com/superhero-wallet/assets/69896204/514f873e-61e7-49fe-a6da-850054c1d007)
![scan](https://github.com/superhero-com/superhero-wallet/assets/69896204/545de5f0-7025-4cd0-992f-d13e97813bae)

**Comment by CedrikNikita** [comment]
Most likely, this problem arises due to the huge load we put on our node in `dryRuns` equivalent, in case the user has many `> 30` multisigs.. That result in slow multisig info update, that is why the vault remain visible. This issue is actually a consequence of the following problem
https://github.com/superhero-com/superhero-wallet/issues/2707

**Comment by Liubov-crypto** [comment]
> Most likely, this problem arises due to the huge load we put on our node in `dryRuns` equivalent, in case the user has many `> 30` multisigs. This causes the multisig information to update slowly, so the vault remains visible This issue is actually a consequence of the following problem #2707

You are correct. 

if I make a proposal Tx, the pending transaction will not be visible in the transaction feed, but only on the account card.
and if I revoke it later, it will not disappear after revoke. Only in this case it is reproduced.
but it's hard to catch.
I tried several times, it only worked once. 

Feel free to close it and reopen when it will rise again. 

![multi1](https://github.com/superhero-com/superhero-wallet/assets/69896204/6a4334f8-437d-4e1c-8ad8-cc9206a0b7c3)

**Comment by Liubov-crypto** [comment]
Not reproducible for me on dev branch.

**Comment by CedrikNikita** [comment]
fixed by #2898
