### ISSUE TITLE
Multisig latest transaction on the dashboard should take full width of the card

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2757]
Currently the latest transaction on the dashboard of Multisig Accounts is displayed with some additional margins. Here's the screen: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/1a229719-7245-4abd-b3ae-c8dab625fc57)

But should take full width same as latest transactions on regular dashboard:

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/2886a295-1642-41bf-ab5f-c3e12e426e22)

**Comment by Liubov-crypto** [comment]
LGTM
