### ISSUE TITLE
Fungible Tokens icons are shifted on Token details page

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2781]
**Describe the bug**
Fungible Tokens icons are shifted on Token details page.

**To Reproduce**
1. Go to FTs details page
2. Open Token details page
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF, Chrome
 - Version 122

**Additional context**
Reproducible on dev branch. 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/104b04db-168b-4f6c-8dd2-568fdae3054f)

**Comment by peronczyk** [comment]
Fixed here: https://github.com/superhero-com/superhero-wallet/issues/2673

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
