### ISSUE TITLE
After user revoke multisig proposal Tx it will be still visible in the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2787]
**Describe the bug**
 I was created a new multisig, proposed Tx and after revoked it, go back to my accounts and go again to multisigs I got an issue.

**To Reproduce**
1. Create new multisig vault
2. Create multisig proposal Tx
3. Revoke Tx
4. Go back to regular account and return to multisigs
5. See error

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iphone 13
 - OS:  iOS 17.2.1

**Additional context**
Reproducible on ios app ver. 2.1.6

https://github.com/superhero-com/superhero-wallet/assets/69896204/4d7b35b7-d858-4581-8122-7c0e0c1613a9

**Comment by CedrikNikita** [comment]
fixed by #2872
