### ISSUE TITLE
Transactions list are not displaying completely

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2795]
**Describe the bug**
Transactions / Assets list are not displaying completely. It could happens from time to time. 

**To Reproduce**
1. Open account details 
2. Go to Transaction list
3. See error - Txs list will be cropped

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  iPhone 13
 - OS:  iOS 17..2.1

**Additional context**
Reproducible on the ios app ver. 2.6.1

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/95c5ed40-2157-4457-a470-8b5babedc319)

**Comment by smaroudasunicorn** [comment]
I will create the major release 2.2.0 or 3.0.0
