### ISSUE TITLE
Avoid cutting off bottom part of names

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2803]
The names displayed on the dashboard account cards are partially cutted off. See here small letters "g":

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/12db73df-2aa7-45a4-819d-632833284732)

**Comment by CedrikNikita** [comment]
fixed by https://github.com/superhero-com/superhero-wallet/pull/2928
