### ISSUE TITLE
ETH Tx details are broken

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2821]
**Describe the bug**
ETH Tx details are broken. After I click on ETH Tx to see the details it becomes broken. I've received this Tx 16 days ago

**To Reproduce**
1. Go to Eth acc
2. Click on Eth tx
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser  chrome
 - Version 122

**Additional context**
Reproducible on the dev branch

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/d074e8b3-b2b5-4134-9071-7d0106ca99ac)

**Comment by Liubov-crypto** [comment]
Reproducible for me on the current dev branch.

**Comment by Liubov-crypto** [comment]
Now it's fixed, LGTM

**Comment by CedrikNikita** [comment]
fixed by #2898
