### ISSUE TITLE
`aeActiveNetworkSettings` sometimes is not updated on network change

### ISSUE THREAD

**Issue by CedrikNikita** [superhero-com/superhero-wallet#2822]
![aeActiveNetworkSettingsBug](https://github.com/superhero-com/superhero-wallet/assets/9008074/36d70a87-1a82-4be0-8982-16853a33c5d1)

Steps to reproduce:
1. Add new aeternity account in Mainnet (for example)
2. Change network to Testnet

**Comment by peronczyk** [comment]
This is ready to be tested @Liubov-crypto 
Probably to test this you need to monitor the account names if they are changed correctly after network change. The network change should happen after creating new empty account.

**Comment by Liubov-crypto** [comment]
If I switch between networks, the names from the main network are visible on the test network about 1-2 seconds, but are updated to match the test network after that.

LGTM.
