### ISSUE TITLE
PIN/Biometric Login Screens

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#2824]
- User shall be able to enable PIN/Biometric Login when creating/restoring a wallet.
- User shall be to enable/disable PIN/Biometric Login from Settings Page.
- A lock screen shall be prompted to the user according to X time of app inactivity.
- User shall be set the time that is required for locking application during inactivity app.

**Comment by onvisions** [comment]
**Acceptance criteria:**

1. Following the design provided implement the initial secure login screen (2 states depending on whether user has device authentication enabled or not).

2. Implement Secure login tab on the Superhero wallet settings page. Tab has 2 states (on/off) depending on whether secure login is enabled or not. The tab opens the Secure login settings page if the user has secure authentication enabled on the device. If not the tab opens Secure login screen (case B): ![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/52a1fb66-2c9d-4577-bd84-f235fa0c0e2d)

3. Implement Secure login page in the Superhero wallet settings. The use should be able to enable/disable the feature. The user should be able to set lock time after which the wallet is locked. 
If the secure login feature is disabled the Lock time block is also disabled. See design for reference.

4. Lock screen.

5. Authentication failed screen. 


**Design:**

**1. Initial Secure login screen.**

**Case A: Device doesn't have security authentication enabled. The user is asked whether they would like to enable it for the mobile device first. Button leads to device settings.**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/89275a3b-b590-469d-84de-c0957858097d)


**Case B: Device has security authentication enabled. The user is asked whether to enable it for the wallet.**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/52a1fb66-2c9d-4577-bd84-f235fa0c0e2d)



**2. Superhero wallet settings:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/58728557-8222-428e-b111-98cd0a029089)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/732bba44-9a9b-4967-ad85-7935f9d0058f)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/be66c25a-5fe3-4969-831d-8db3f6517f6e)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/e546fbb4-8eb9-462f-8558-5a0a5bcd666c)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/c01f77b1-3709-45e1-941b-168ba8569144)

3. Lock screen, Authentication failed screen. 

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/fe8b7394-ce9c-4687-8b9d-cdbdf3acc6ef)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/ed351428-c1e5-4791-9b10-d10d293d47c3)


**User flow recording:**

https://github.com/superhero-com/superhero-wallet/assets/12225410/44887e3c-3f26-4a84-985f-04526923f134

**Prototype:** https://www.figma.com/proto/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=31015-181433&t=dpJAqwViNjfbNmxI-1&scaling=min-zoom&page-id=10439%3A144915&starting-point-node-id=31015%3A181433&mode=design

**Figma reference:** https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=31015-181690&mode=design&t=hclQ54UFVNC1obte-0

**Comment by smaroudasunicorn** [comment]
I am ok with the proposal. A minor comment is that I propose to add a description in settings page for Auto lock. 

"The wallet is locked for further actions after configured time interval. User has to unlock the screen in order to proceed to further actions."

**Comment by onvisions** [comment]
Ok. We can add the description but I suggest:
"Superhero wallet is locked after the preset time interval of inactivity. You have to authenticate in order to unlock the screen and continue using the wallet."

**Comment by smaroudasunicorn** [comment]
I am ok. thanks

**Comment by Liubov-crypto** [comment]
@onvisions I have a question: is this screen should look like this? I saw it a little different on the record. Or it depends on the device? 

![2024-04-02 1 16 56 пп](https://github.com/superhero-com/superhero-wallet/assets/69896204/13d0fd84-aed4-4ef4-b99b-c14753112019)

**Comment by martinkaintas** [comment]
> @onvisions I have a question: is this screen should look like this? I saw it a little different on the record. Or it depends on the device?

It depends on the device

**Comment by onvisions** [comment]
@Liubov-crypto The feature relies on the native authentication method available on the device.

On the screenshot provided we don't provide the layout nor the styling or even the icon but as far as I got we can modify the text strings like "Authenticate to access your wallet".

**Comment by Liubov-crypto** [comment]
I found an issue: if I'm enable secure login immediately after login or new wallet creation and then try to enter my pin code it will not work. I will be not able to enter my wallet. The same behaviour if I'm set security login in Settings with option - immediately. If I will choose other options it will work. 



https://github.com/superhero-com/superhero-wallet/assets/69896204/b17a44ff-563e-4b32-a52c-00cf7c3d1cc6

@martinkaintas please check it.

**Comment by Liubov-crypto** [comment]
Finally it's working for me with immediately option :) LGTM
