### ISSUE TITLE
After send a multisig tx, Tx is visible some time in vault

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2832]
**Describe the bug**
After send a multisig tx, Tx is visible some time in vault 

**To Reproduce**
1. Propose multisig Tx
2. Send it 
3. See error

**Expected behavior**
Tx should disappear after sending 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS
 - Browser chrome,
 - Version 122

**Additional context**
Reproducible on dev branch 

https://github.com/superhero-com/superhero-wallet/assets/69896204/3b376fc2-c15c-4344-a1e6-69d254c974ea

https://aescan.io/contracts/ct_DKjSsiDtYjcfs92oydQ1bfvKqXz8Zd36s37NhvjfwxFJipotB?type=call-transactions

https://aescan.io/transactions/th_vmPfP3zQuB8Jj4Tt6QTFag5GT3HidebMTJBbEbLJtQbY6pH1P

https://aescan.io/transactions/th_28UZug2fKXFYJpqP4Ys6LppXVUikjDuF58icgFgYncdKZtL9tf

**Comment by Liubov-crypto** [comment]
Not reproducible for me on the current dev branch.

**Comment by CedrikNikita** [comment]
fixed by #2872
