### ISSUE TITLE
Aligning is broken in multisig acc selector

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2835]
**Describe the bug**
Aligning is broken in multisig acc selector

**To Reproduce**
1. Go to multisig acc
2. Try to create multisig
3. Select account 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 122

**Additional context**
Reproducible on dev branch extension and web

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/9ef89b3d-5cf4-4a06-b333-30d8635e23b7)

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/5e1624d8-f380-48a5-b6a1-0c527eadf1fe)
![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/e5c5b9ed-a3b2-4c1b-9c0d-272a7b63a022)

https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=25165-340590&mode=design&t=1Zw9Vjby8vcPEwYf-0

**Comment by peronczyk** [comment]
Fixed. Please take a look @Liubov-crypto

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
