### ISSUE TITLE
Transactions belonging to other accounts are displayed in newly created wallet account.

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#2841]
I reset my wallet extension and created a new wallet.
I noticed on the wallet dashboard that I have 3 transactions listed although in my newly created account I have none. I think these happen to be transactions I have made between other accounts of mine before resetting the wallet so I assume it might be some cache stored in the browser. 
Even stranger behaviour: when I tried to see each transaction details screen the transactions appeared in the Transactions list on the Account details page. 
All is shown in the recording below:

https://github.com/superhero-com/superhero-wallet/assets/12225410/55c47ae4-3f1d-4857-afec-4acb6205f7e1

Observed in the wallet extension v.2.1.6, 
Browser: Firefox
OS: Windows 10

**Comment by Liubov-crypto** [comment]
Reproducible on product.
