### ISSUE TITLE
Ambiguous nonce information

### ISSUE THREAD

**Issue by nikita-fuchs** [superhero-com/superhero-wallet#2850]
If there is already an issue regarding the fetching of wrong nonces please feel free to close this one, but as this one appeared also to me today I wanted to report it:

![nonce1](https://github.com/superhero-com/superhero-wallet/assets/11761828/6b1b43fa-4d2c-40a8-b28a-be6956830829)

What is the exact reason why the nonce `1` is being proposed for an account that has countless transactions already and what do we need to prevent this from happening?

**Comment by CedrikNikita** [comment]
It looks like you are trying to sign a transaction via deeplink. This method was created with the assumption that this transaction was prepared by the Dapp. The transaction you are trying to sign has a `nonce` 1.

Current tool of deeplink signing is pretty simple, wallet is trying to validate the transaction before signing, signs and sends it. We are realign on the dapp to provide us a valid transaction to sign. This was 100% of our use cases previously. 
Wallet will notify the user if transaction is invalid.
1) In the case of contract calls, wallet is trying to prevent user from wasting his money on calling the invalid contract call by dry running it first.
2) In case of spend we just checking that balance is enough.

As i understood, you are suggesting to have a possibility to unpack the transaction and change certain fields in it.
This doesn't seem to be a common case for the average user. We can still implement this feature if it is considered needed for community.

Also as one more improvement, we can allow user to sign anything, even invalid transaction, but with the explanation what could happen in this case (potential money lost, etc).

**Comment by nikita-fuchs** [comment]
Hey @CedrikNikita , no, this appeared when I tried to do a regular contract call, no deep linking.

From the smell of it, some call probably returned `null` or so and the wallet or something else treated this as a new account, thus setting the nonce to 1.

**Comment by CedrikNikita** [comment]
Screenshot looks like you are trying to sign transaction that is prepared by the Dapp. Correct me if I'm wrong.

**Comment by CedrikNikita** [comment]
I wasn't trying to move from the topic. I'm trying to collect the data. Current master is not fetching any nonce in this screen. We just  `dryRun` the transaction wallet was asked to sign.
https://github.com/superhero-com/superhero-wallet/blob/a5d2c995895222a5a88aa8e507a732b610629153/src/popup/components/Modals/ConfirmTransactionSign.vue#L443
But the develop is now working differently https://github.com/superhero-com/superhero-wallet/pull/2782.

**Comment by nikita-fuchs** [comment]
Looking at the PR, I'm a bit puzzled by how this would have worked before then. anyways, thanks @CedrikNikita ! one question about the implementation details though: It is the wallet that sets the nonce in a regular contract call, right ? or is it handed to the wallet by the SDK?

**Comment by davidyuk** [comment]
As I understand, the contract call transaction generated on aepp side in this case. Aepp generates it using sdk. Sdk's transaction builder uses a nonce returned by `/next-nonce` endpoint by default.

Wallet signs transaction as is, with the nonce provided by aepp. But wallet replaces nonce with the current one to do dry-run.

**Comment by nikita-fuchs** [comment]
> But wallet replaces nonce with the current one to do dry-run.

But if the wallet does that, why do we end up with a wrong nonce?

**Comment by nikita-fuchs** [comment]
As discussed with @CedrikNikita , the issue should be fixed. Closing the issue for now. To be reopened, if the problem appears again.

**Comment by davidyuk** [comment]
> why do we end up with a wrong nonce?

It meant to be fixed in #2782
