### ISSUE TITLE
Do not show the multisig account address to the user until it is confirmed that it has been created successfully.

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#2859]
@smaroudasunicorn @peronczyk 
**Acceptance criteria:**
- Implement "Adding vault..." state to the Dashboard card;
- Disable the dashboard card link to Multisig vault details and both "Receive" and "Propose Tx" buttons while the vault is in "being added" state. 
- Modify the "Creating vault progress" wizard accordingly: Remove the button until vault is being added; Update the text on the last 2 screens (seemockups and Figma); The button leads to Dashboard with the newly created Vault as current card (it might be still in "Adding vault state...");

**Design:**

Multisig vault card ("Adding vault..." state):

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/fb9fa693-d0cf-448a-8102-321ac4eff418)

Multisig vault creation progress modal (create vault wizard):

![Creating vault wizard-1](https://github.com/superhero-com/superhero-wallet/assets/12225410/d714daa8-40c7-46ca-abe9-b1f4ee000e36)

![Creating vault wizard-2](https://github.com/superhero-com/superhero-wallet/assets/12225410/30fba6ca-6e2e-45b9-ad14-d763b341daef)

![Creating vault wizard-3](https://github.com/superhero-com/superhero-wallet/assets/12225410/1bb4deec-224a-4d01-a6b1-5d9d9a07d2f5)

![Creating vault wizard-4](https://github.com/superhero-com/superhero-wallet/assets/12225410/0b49ff5d-d14f-493f-bb7a-ae7ea5a8e43f)

![Creating vault wizard-5](https://github.com/superhero-com/superhero-wallet/assets/12225410/d9ed7880-2a17-4437-8d23-ceaa412dfd15)

**Prototype recording:**

https://github.com/superhero-com/superhero-wallet/assets/12225410/e51016fa-2ac7-42e5-9c14-d1faead26dec

**Figma reference:**
1. https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=24727-334240&mode=design&t=tM6Zr7XhZxq5o7Sa-0
2. https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=24728-334748&mode=design&t=tM6Zr7XhZxq5o7Sa-0

**Comment by peronczyk** [comment]
Please confirm on which screens I need to hide the address? I guess the following ones:

1. Vault creation progress:
![image](https://github.com/superhero-com/superhero-wallet/assets/8217670/e1ffc2b5-9537-4ff8-9f32-2aaa2a852168)

2. Dashboard card

@smaroudasunicorn

**Comment by peronczyk** [comment]
Additional change approved by @onvisions is making the account card arrows to be fixed to screen position instead having them on each cards separately.
This requires testing both on multisig and regular dashboard.

**Comment by Liubov-crypto** [comment]
LGTM
