### ISSUE TITLE
After approving a multisig Tx info on accounts card and in Tx list is mismatching

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2860]
**Describe the bug**
After approving a multisig Tx info on accounts card and in Tx list is mismatching (due to slow multisig updating ?):

**To Reproduce**
1. Go to multisig
2. Propose Tx 
3. Approve it by both accs

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF, chrome, FF extension
 - Version 123

**Additional context**
Reproducible on the release branch. 

https://github.com/superhero-com/superhero-wallet/assets/69896204/2447a0cc-9a6d-493a-9bed-26d013459cec

**Comment by CedrikNikita** [comment]
I think it was missed in https://github.com/superhero-com/superhero-wallet/pull/2776
