### ISSUE TITLE
BTC is displaying as unrecognized in Tx details

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2864]
**Describe the bug**
BTC is displaying as unrecognized in Tx details

**To Reproduce**
1. Go to BTC acc
2. Click on BTC Tx
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, FF
 - Version 123

**Additional context**
Reproducible on release branch. 

https://github.com/superhero-com/superhero-wallet/assets/69896204/99b4302b-742b-4c45-9db4-4d54afe890c9

**Comment by smaroudasunicorn** [comment]
This is happening also for AE fungible Tokens

**Comment by peronczyk** [comment]
One line fix. Ready to test @Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM
