### ISSUE TITLE
When I'm choosing Signer's acc when creating multisig it adds wrong info

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2874]
**Describe the bug**
When I'm choosing Signer's acc when creating multisig it adds wrong info. The information is visually superimposed on another account and the result is a mismatch 

**To Reproduce**
1. Try to create multisig
2. Choose acc signer
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, FF
 - Version 123

**Additional context**
Reproducible on release/dev branch, web and extension. 

https://github.com/superhero-com/superhero-wallet/assets/69896204/84a6f065-4c8e-4761-b95c-d55ceedd3600

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/17c83c37-95e3-4e01-a9fa-c383c4ee88d3)

**Comment by peronczyk** [comment]
Related: https://github.com/superhero-com/superhero-wallet/issues/2847
