### ISSUE TITLE
Color of the asset name is too dark on the transaction lists

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2877]
During the work on the asset symbols and names I have introduced regression that causes the asset names to be too dark when displaying the transaction lists. This task is about changing the color of the asset from gray to white.

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/8e49d612-7877-41fa-8c78-1509486fff67)

**Comment by peronczyk** [comment]
Ready to be tested @Liubov-crypto 
The PR is actually one-liner.

**Comment by Liubov-crypto** [comment]
LGTM
