### ISSUE TITLE
Fix transaction details avatar size and color

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2881]
Currently the avatars displayed in the transaction details does not match the designs. What needs to be fixed:

1. Designed avatar size is 48 but developed is 56.
2. The avatar with geometrical shapes and the avatar with custom generated faces has additional padding which makes the image smaller.
3. Additional change: the avatar borders now matches the avatar primary color so it looks the same as the one displayed in the account details home page (@onvisions).

**Initial design:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/37600dea-5dba-432a-9853-bceeaee36f95)

**Current version:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/21792903-5ecf-4c96-8ea3-aa93a5a7cb7c)
![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/2eb13c16-0ac9-44d1-ba5f-e810b2674d51)

**Fixed version:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/ffa6120c-7e9a-43eb-9863-3ef52ea531c9)
![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/3fc5c244-2465-405b-b98f-21f004766a7a)

**The avatar now matches this header design:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/09ee32a2-5381-4c71-b95b-134a960283d8)

**Comment by onvisions** [comment]
Approved on my side with the suggested color change of the border.

**Comment by Liubov-crypto** [comment]
LGTM
