### ISSUE TITLE
Wrong redirection from multisig Tx details to main account not to the previous page

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2883]
**Describe the bug**
There is wrong redirection from multisig Tx details to main account not to the previous page 

**To Reproduce**
1. Go to multisig 
2. Check multisig tx details
3. Click on back button

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 123

**Smartphone (please complete the following information):**
 - Device: iphone 13
 - Version 2.2.0(1)

**Additional context**
release branch

https://github.com/superhero-com/superhero-wallet/assets/69896204/2bdb8016-053b-441f-a01f-0601c932b03c

**Comment by CedrikNikita** [comment]
fixed by #2871
