### ISSUE TITLE
Dex visual discrepancies on ios app

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2890]
**Describe the bug**
Dex visual discrepancies on ios app

**Smartphone (please complete the following information):**
 - Device: iPhone13

 - Version 2.2.0(1)

**Additional context**

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/4c164f04-3e98-4372-b7a1-6a398cef6417)

**Comment by CedrikNikita** [comment]
This is a dex problem.

**Comment by smaroudasunicorn** [comment]
@Liubov-crypto can you report it to DEX team

**Comment by Liubov-crypto** [comment]
> @Liubov-crypto can you report it to DEX team

reported
