### ISSUE TITLE
Some contract calls that are not connected to AEX9 tokens are shown with `Unrecognized` name

### ISSUE THREAD

**Issue by CedrikNikita** [superhero-com/superhero-wallet#2893]
|develop|master|
|---|---|
|![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/a285d9ad-1455-49b9-9043-dc9008c16f9e)|![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/b22fce6b-af03-4564-8265-07574f77b71c)|

These transactions are actually chat connection contract calls. They have nothing to do with tokens. They should not be threated as such.

https://aescan.io/transactions/th_4heSKDFTLYx321iZDUWUrdyvXfaJm9TiNoGxfaDNdgpiV3UEB

**Comment by Liubov-crypto** [comment]
LGTM
