### ISSUE TITLE
Transactions with FT are displaying differently

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2900]
**Describe the bug**
Transactions with FT are displaying differently for Spend In and Spend Out Txs 

**To Reproduce**
1. Go to Tx list
2. Compare Txs for FT - Spend In and Spend Out 
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser  chrome, safari, FF
 - Version 123, 122

**Additional context**
reproducible on product.

https://github.com/superhero-com/superhero-wallet/assets/69896204/61c6a7af-dff8-4cd3-8a68-728805e31af6

**Comment by CedrikNikita** [comment]
fixed by #2895
