### ISSUE TITLE
Max amount button is stop working if ETH balance is less than fee

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2909]
**Describe the bug**
Max amount button is stop working if ETH balance is less than fee

**To Reproduce**
1. Go to Send ETH, your ETH balance should be lower than fee
2. Click on Max button
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, FF
 - Version 123

**Additional context**

![ьфч](https://github.com/superhero-com/superhero-wallet/assets/69896204/b5598026-223d-46e4-a179-1a689722a880)

**Comment by onvisions** [comment]
Regarding our team discussion related to this bug and possible improvement of current state UX: @martinkaintas please implement auto-update of the amount field value (when MAX is selected) according to the update of transaction fee. 
Further, let's sync together any UI design related issues if there will be such.

**Comment by Liubov-crypto** [comment]
LGTM. 

In some cases when I'm switching between fee options it shows additional warning (It looks like this is how the information is updated when the fee is changed):


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/a7c85735-8e8b-48f1-bce1-ae00ff288c4b)
