### ISSUE TITLE
Fix browser actions menu buttons appearance

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2931]
The look of the browser action menu buttons are different than designed: different colors, spacings, font weights. The reason is that for this menu items new component was created instead of reusing existing button created for such menus (eg.: used in account create menu).

**Current look:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/1edd9fd0-af84-4358-a77c-831e616d32b2)

**Developed add account buttons:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/dfdee54a-a26f-404a-95db-e2962dc5e96c)

**Comment by Liubov-crypto** [comment]
LGTM
