### ISSUE TITLE
Prevent highlighting the more header button after closing account details

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2936]
Reproduction:
1. In mobile app open the account details
2. Use (x) button on top right to close the account details (try to hold it little longer)
3. When the account details is closed there is a chance that the three dots header icon will be highlighted

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/be951c11-1399-4158-9a93-71f9931945b9)

**Comment by Liubov-crypto** [comment]
LGTM
