### ISSUE TITLE
Some of the modals seem to be blurred in Chrome extension.

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2944]
https://aeternity-blockchain.atlassian.net/browse/SW-511

Description

Some of the wallet modals seem to be blurred as if they are scaled. It is not only bad from design point of view but also makes the text less readable  especially in the info modals.
At first I thought it might be related to blurred background effect behind the modals but then I noticed that this bug is not observable in the “Send funds” modal.

Bug Description

*Describe the bug*
Some of the wallet modals seem to be blurred as if they are scaled. (See attached screenshots)
At first I thought it might be related to blurred background effect behind the modals but then I noticed that this bug is not observable in the “Send funds” modal.

*Expected result*
Modal contents should not be blurred but sharp and clearly readable.

*Steps to reproduce*
1. Navigate to any info modal.
2. Observe how it looks blurred. 

Environment

Windows, Chrome extension (not present in Firefox, not sure about other browsers and devices)

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/31a8dc9b-b8dd-4d6f-a008-e948c7aee4c2)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/cbe07f54-fde2-4642-9694-3a371683a34f)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/d4c2f46c-07a1-42d3-aecf-1aa6d0fde40c)

**Comment by peronczyk** [comment]
The issue was caused by the `will-change: transform;` CSS rule applied to modal windows. I removed this rule.

**The modal before removing it looked like this:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/4186420c-5544-4d1b-878f-453ade4e6d63)


**After removing it:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/db6b444e-3b5a-455c-9952-0f0cdd56f240)

**Comment by onvisions** [comment]
Thanks @peronczyk it seems this months old issue has been fixed with 1 line of CSS.

**Comment by Liubov-crypto** [comment]
The blurred modals have been fixed.
