### ISSUE TITLE
Fiat value not properly fetched (possibly 3rd party API fault). Suggestion for workaround.

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#2961]
The Fiat value of Coins/Tokens is not properly fetched by third party API (CoinGecko) which leads to following bugs observed in the wallet extension:
1. The **Total** portfolio value of all accounts is displayed as "0" although the user has tokens and coins in various accounts.
2. Fiat values are displayed as "0" in the transactions list.
3. Fiat values of token amounts in the token selector (Sending or Receiving flow) are not displayed.

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/e2ed054e-e9c6-4d8b-b9e5-dd9cc2abf204)
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/5107d9e2-2aea-4732-a84d-29345ff88da2)

**Suggestion:** if the problem is with CoinGecko API we may implement logic to display the latest successfully fetched data about the asset price if it's no older than 10 mins (the exact period to be determined).  In case data is older we should hide the fiat value until we can fetch properly. IMO It's more frustrating and confusing to see balance $0.00 instead of not seeing any value at all.

**Comment by peronczyk** [comment]
As we don't have any control if CoinGecko API call fails I agree that the only solution is to cache the previous values.
I have implemented the local storage caching. The task is ready to review and test @Liubov-crypto .

In order to test it you can try to block the CoinGecko url in your browser after opening the app for the 1st time and then try to opn/close it again.

**Comment by Liubov-crypto** [comment]
After I blocked the CoinGecko URL and reloaded the app, it will show the total amount, but will not show the amount for each transaction, such as ETH. I don't know if this is correct, but the same is on product. 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/eda24fe6-b602-4312-bf4c-8fa10bce2851)

the rest is LGTM
