### ISSUE TITLE
Can't login to superhero.chat

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2975]
**Describe the bug**
Can't login to superhero.chat

**To Reproduce**
1. Go to chat.superhero.chat
2. Click on login with wallet
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : chrome
 - Version 123

**Additional context**
reproducible on commit [f644ad1](https://github.com/superhero-com/superhero-wallet/pull/2974/commits/f644ad1d971053f0cb732f878560e39dabd1b39d)

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/89f25b52-bd01-476c-b855-3ef072fef26a)

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/caaa7090-9715-47ae-980a-f25f67ddfda9)

{"nativeError":{"code":"ERR_JWS_INVALID","name":"JWSInvalid"},"name":"JWSInvalid","message":"Invalid Compact JWS","stack":[{"fullFilePath":"file:///src/node_modules/jose/dist/node/esm/jws/compact/verify.js:13:15","fileName":"verify.js","fileNameWithLine":"verify.js:13","fileColumn":"15","fileLine":"13","filePath":"/node_modules/jose/dist/node/esm/jws/compact/verify.js","filePathWithLine":"/node_modules/jose/dist/node/esm/jws/compact/verify.js:13","method":"compactVerify"},{"fullFilePath":"file:///src/node_modules/jose/dist/node/esm/jwt/verify.js:5:28","fileName":"verify.js","fileNameWithLine":"verify.js:5","fileColumn":"28","fileLine":"5","filePath":"/node_modules/jose/dist/node/esm/jwt/verify.js","filePathWithLine":"/node_modules/jose/dist/node/esm/jwt/verify.js:5","method":"jwtVerify"},{"fullFilePath":"/src/src/support/jwt.ts:23:9","fileName":"jwt.ts","fileNameWithLine":"jwt.ts:23","fileColumn":"9","fileLine":"23","filePath":"/src/support/jwt.ts","filePathWithLine":"/src/support/jwt.ts:23","method":"verifyJWT"},{"fullFilePath":"node:internal/process/task_queues:95:5","fileName":"task_queues","fileNameWithLine":"task_queues:95","fileColumn":"5","fileLine":"95","filePath":"internal/process/task_queues","filePathWithLine":"internal/process/task_queues:95","method":"process.processTicksAndRejections"},{"fullFilePath":"/src/src/routes/express.ts:176:11","fileName":"express.ts","fileNameWithLine":"express.ts:176","fileColumn":"11","fileLine":"176","filePath":"/src/routes/express.ts","filePathWithLine":"/src/routes/express.ts:176","method":"<anonymous>"}],"_meta":{"runtime":"Nodejs","runtimeVersion":"v20.12.2","hostname":"c9629746170b","date":"2024-04-16T10:34:00.922Z","logLevelId":5,"logLevelName":"ERROR","path":{"fullFilePath":"/src/src/routes/express.ts:188:15","fileName":"express.ts","fileNameWithLine":"express.ts:188","fileColumn":"15","fileLine":"188","filePath":"/src/routes/express.ts","filePathWithLine":"/src/routes/express.ts:188","method":"<anonymous>"}}}
{"nativeError":{},"name":"Error","message":"jwt signature verification error","stack":[{"fullFilePath":"/src/src/routes/express.ts:189:17","fileName":"express.ts","fileNameWithLine":"express.ts:189","fileColumn":"17","fileLine":"189","filePath":"/src/routes/express.ts","filePathWithLine":"/src/routes/express.ts:189","method":"<anonymous>"},{"fullFilePath":"node:internal/process/task_queues:95:5","fileName":"task_queues","fileNameWithLine":"task_queues:95","fileColumn":"5","fileLine":"95","filePath":"internal/process/task_queues","filePathWithLine":"internal/process/task_queues:95","method":"process.processTicksAndRejections"}],"_meta":{"runtime":"Nodejs","runtimeVersion":"v20.12.2","hostname":"c9629746170b","date":"2024-04-16T10:34:00.924Z","logLevelId":5,"logLevelName":"ERROR","path":{"fullFilePath":"/src/src/support/ejs.ts:71:7","fileName":"ejs.ts","fileNameWithLine":"ejs.ts:71","fileColumn":"7","fileLine":"71","filePath":"/src/support/ejs.ts","filePathWithLine":"/src/support/ejs.ts:71","method":"renderError"}}}

**Comment by thepiwo** [comment]
its a fault in the oidc provider, will track it here: https://github.com/superhero-com/oidc-provider/issues/24#event-12487712944
