### ISSUE TITLE
Investigate Confirmation on User's Demand, currently relies on SDK request

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#2981]

**Comment by smaroudasunicorn** [comment]
An external source is requesting to connect with our wallet, sign a transaction/message. We should always display the modal and the origin of the request or that the origin URL is unknown.

**Comment by onvisions** [comment]
@smaroudasunicorn 

1. We always display the confirmation modal, there is no question about it.
2. In the case of **Unknown URL** an unknown source is asking for access and most probably this means that the user is being scammed or there is high probability of loss of funds and other undesired consequences. Only in this case we should display the checkbox to make sure user is aware of the risks and not proceeding without reading the warning (all the other templates that can be seen in Figma do not have a checkbox). So my suggestion is to keep the checkbox for this case that will be rarely experienced.

**Comment by onvisions** [comment]
@smaroudasunicorn Updated design and wording:

![Tx Access, Sign, Raw tx](https://github.com/user-attachments/assets/6b734e89-df8c-4dc5-a678-5c18d7d38065)


**What do you think about that (from my previous comment):**

> Other than that I think it's high time to implement the updated version of all these templates for signing messages, allowing access, RAW transactions, with errors and warnings, etc. I have designed (and synced with Nikita) pretty neat templates which require only minor modifications of our existing template but will bring more consistency and professional look and feel of the UI as currently it's a bit messed up. Also it creates confusion for QA team while testing as the Figma reference is different from implementation.
> May be we can include it as task in the next sprint. I don't see huge amount of work needed but rather more attention to details such as colors, opacity, labels, wording, external linking with proper icons, updated button labels etc.

**Comment by smaroudasunicorn** [comment]
Kindly ensure that you are aware of the request origin. Allowing access might cause undesired results, including loss of your funds.

**Comment by onvisions** [comment]
![Tx Access, Sign, Raw tx](https://github.com/user-attachments/assets/884eb838-aa8f-4389-aa80-b90cf12dde57)
