### ISSUE TITLE
WalletConnect design references

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2982]
This task needs some designs: https://github.com/superhero-com/superhero-wallet/issues/2664 - you can open the PR and use the deployed test version. Please use only the web (not the extension).

The demo app is available here: https://feat-eth-dapps-support.wallet.z52da5wt.xyz/

**Here is the list of required elements & screens:**
1. App header icon design - connected and not connected
2. Modal window that opens up after clicking on the header WalletConnect icon
    a. With an error if user has no ETH accounts
    b When not connected
    c. When connected
    d. When connection failed
3. Transaction approval modal that pops up when we try to propose transaction in the Uniswap.

**Comment by onvisions** [comment]
Wallet Connect

**Acceptance criteria:** 
... (to be listed here);
... error states to be added:
- With an error if user has no ETH accounts 
- When connection failed


**Prototype flow recording:** 

https://github.com/superhero-com/superhero-wallet/assets/12225410/bf43a443-c8de-470a-875b-49120c3761bd

**Figma Design Reference:**  

https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=31639-178033&mode=design&t=Rug7hN48z30wOfvK-0

**Comment by smaroudasunicorn** [comment]
I am ok with updated Proposals

**Comment by onvisions** [comment]
**WalletConnect** feature

@smaroudasunicorn updated design after syncing with @peronczyk.
**Design update after updated technical requirements:**


**Acceptance criteria:** 
1. Wallet connect icon for the top bar:
- not connected state;
- connected state.

2. WalletConnect modal with options to scan QR and input/paste URI link:
- State: Scan QR or use input URI;
- State: Connecting;
- State: "Unable to connect";
- State: Connected to dapp (disconnect?).

**Prototype recording:** 


**Design:** 

_Not connected icon:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/30e4419b-8c44-4b69-8ada-4e7d6d2d675e)



_Connected icon:_



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/6da417b2-22c8-4905-9763-05680366866e)




_Scan QR or use input URI:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/8360a50b-62dd-4242-b7e0-7b317c7caa98)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b219781b-75d3-4375-baf9-6019113997a6)



_Connecting:_



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/5f449410-3a99-4b97-b975-ed7af71073a0)



_Unable to connect:_



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/a12d7374-b41b-4c0a-89f7-70bfbe6cdf99)



_Connected to dapp modal (disconnect?):_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/a58a5197-3788-4dba-be4b-f8f19604c0f6)




**Figma Design Reference:**  

https://www.figma.com/file/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?type=design&node-id=31639-178033&mode=design&t=gMamfsyUU0oNkHkt-0

**Comment by onvisions** [comment]
**Following issues should be addressed:**

1. Case: SH wallet has been connected to WC but there is no Internet connection at the moment. 
 
![1 4 Wallet Connected, No Internet](https://github.com/superhero-com/superhero-wallet/assets/12225410/697906df-b643-43a1-a9ea-3dc08b909e49)

![Blurred overlay](https://github.com/superhero-com/superhero-wallet/assets/12225410/0d62f24a-8557-44c0-a231-399006258183)

2. Case: No Ethereum account found.

![Wallet Connect modal](https://github.com/superhero-com/superhero-wallet/assets/12225410/f5114164-1052-4c01-9eaa-3ac4a93f7485)


3. Update icon used and text of Connection failed modal according to design.

![Info Modal](https://github.com/superhero-com/superhero-wallet/assets/12225410/241325a3-897f-4502-8575-2a00a08c65ac)

![Info Modal (1)](https://github.com/superhero-com/superhero-wallet/assets/12225410/dbacc1c1-9265-449e-b060-144b861daa8a)



4. Discrepancies with design:

![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/06a72b5b-a770-44de-966d-0311e1057286)

![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/cf89279e-6369-403a-919c-3361a3ba440d)


**_! 5. Unknown connection error observed:_**

![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/3591de9a-3d81-41ec-b916-bd3a79fd5152)

**Comment by peronczyk** [comment]
@onvisions this task can be reviewed now.

**Comment by onvisions** [comment]
@peronczyk unfortunately there are still a lot of issues.

I am listing all issues I have found here and I will not make another review. Just fix what's needed.

![Screenshot_1](https://github.com/user-attachments/assets/ddce52be-c928-48a9-b5f8-64c546717ea0)
![Screenshot_2](https://github.com/user-attachments/assets/79f803e3-ef76-418a-b8ee-fe4d25a1077b)
![Screenshot_3](https://github.com/user-attachments/assets/2fd9d5de-2c3f-453a-a60c-f5943b9cc136)
![Screenshot_4](https://github.com/user-attachments/assets/58264030-e358-4717-b662-6929c969d3bb)
![Screenshot_5](https://github.com/user-attachments/assets/c1c75049-f74d-46e3-9011-9fb20f42d205)
![Screenshot_6](https://github.com/user-attachments/assets/682ef144-7dfc-4893-8833-2195b0921c1b)
![Screenshot_7](https://github.com/user-attachments/assets/c235f0f2-5580-456b-b345-fa2b39efba33)

**Comment by onvisions** [comment]
@peronczyk by the way, this is my mistake but let's update it for consistency. 
![image](https://github.com/user-attachments/assets/5ba0efcc-4ec7-4ec0-8409-3eccf4de55b5)

**Comment by peronczyk** [comment]
1. "Dapp" replaced with "dapp"
2. The visual difference between text labels ("Connecting as") and the input labels ("WaleltConnect URI") is fixed within different PR: https://github.com/superhero-com/superhero-wallet/issues/3154
3. The way how multiline fields works is something that was developed long time ago by Konrad Odo and was approved back then. If we wan't to change this behavior I suggest to create separate task to avoid making this PR too big.
4. ![Image](https://github.com/user-attachments/assets/54646574-1892-4365-9171-8d512af04686)

I just used component that we have. It was created 17 months ago and if you feel we need to update it please create separate task.

5. I updated the hover color styling for URL row.
6. The error message "No Ethereum account found..." is centered because the `InfoBox` component was developed this way. We use it in several other places. I can change the alignment globally, provide the ability to left-align only for selected places or leaver it as it is. Which option should I choose?
7. Updated the modal buttons to not hide the connect button in case there are no eth accounts. Only disabling it.
