### ISSUE TITLE
AE balances displayed as 0.

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#2985]
Issue: AE balances displayed as 0. Fiat values also missing from all UI elements.
SH wallet status is "Connected" to Mainnet.
Observed: browser extension both Chrome and Firefox.

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/3836a8d2-9ac7-42b8-8a1a-dd1d59886b86)

**Comment by Liubov-crypto** [comment]
![node](https://github.com/superhero-com/superhero-wallet/assets/69896204/54ba1492-0264-4e1a-aab7-f83defd2fac5)
![t](https://github.com/superhero-com/superhero-wallet/assets/69896204/502d870b-c1e9-4430-93e8-0efa5b4f289f)
