### ISSUE TITLE
User can add a bid to a name that shouldn't be in auction

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2990]
**Describe the bug**
User can add a bid to a name that shouldn't be in auction 

**To Reproduce**
1. Go to Auctions page on testnet
2. Click on yusufseyrek.chain
3. Add bid

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser  chrome
 - Version 123

**Additional context**
reproducible on dev branch

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/ef25561d-2061-4169-a428-07e14d8b0007)

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/345ec0d4-6eba-4b91-b4ef-260087618b23)

https://github.com/superhero-com/superhero-wallet/assets/69896204/16ce12dd-e983-43a9-8abb-7d94631a0a49

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/07e73a56-4ca4-4ae9-add2-0dfd4fe1625f)

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/1152f4ec-7ba3-4057-abbd-70ac67f3a382)

**Comment by CedrikNikita** [comment]
Connected to this iusse https://github.com/aeternity/ae_mdw/issues/509

**Comment by Liubov-crypto** [comment]
Fixed. LGTM
