### ISSUE TITLE
Example aepp can't iteract with SW on iOS

### ISSUE THREAD

**Issue by davidyuk** [superhero-com/superhero-wallet#2993]
**Describe the bug**
When Example aepp requests wallet to sign something, wallet receives the request. Then it shows me confirmation modal. If I approve the modal closes, but aepp gets a RpcNotAuthorizeError (actually, before showing confirmation modal).

**To Reproduce**
1. Create a new account
1. Click on Globe icon
2. Navigate to https://docs.aeternity.com/aepp-sdk-js/v13.3.2/examples/browser/aepp/
3. Press "Connect"
4. Confirm connection an aepp, and wallet sides
1. Open "Basic functionality"
1. Enter a message to sign
1. Confirm message signing
1. See "RpcNotAuthorizeError: You are not connected to the wallet"

**Expected behavior**
The same as on Android and web, it should show signature, like
```
Message sign result
{
  "type": "Buffer",
  "data": [
    167,
    245,
```

**Screenshots**
<img src="https://github.com/superhero-com/superhero-wallet/assets/9007851/ff673178-6537-4121-8a64-52e92d9d5565" width="50%" />

**Smartphone**
 - OS: iOS@17.4.1
 - SW app@2.2.3 (439f0a745bfaf78d6e771e0f320e850994335cae)

**Comment by Liubov-crypto** [comment]
Also reproducible on v.2.2.5
