### ISSUE TITLE
After creating a gift card, amount field error appears

### ISSUE THREAD

**Issue by dvdbak** [superhero-com/superhero-wallet#2999]
**Describe the bug**
After user is generating a gift card and it is shown on bottom. Under the gift card amount field will appear "This field must be more than 0" error message

**To Reproduce**
1. Go to more
2. Click on Gift Card
3. Enter amount
4. Select generate gift card

**Expected behavior**
Amount field error msg should appear

**Screenshots**
![image](https://github.com/superhero-com/superhero-wallet/assets/119422781/98e0c83b-c417-4bff-843f-0a8941260211)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser brave
 - Version 1.65.114 Chromium: 124.0.6367.60]

**Additional context**

**Comment by Liubov-crypto** [comment]
LGTM
