### ISSUE TITLE
Backend and Dust UTXO error templates

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#3026]
@CedrikNikita please review and let me know if there is something to be added or updated.

**Acceptance criteria:**
- Implement error modals for cases of backend failure and dust UTXO error.
- Update the texts of different connection/network status modals and wallet bottom status bar according to suggested design and wording.
- For the question mark icon use the same component as for info popups above the input fields (recently updated by Bart to have a hover effect applied).

**Design for dust UTXO error template:**

![Image](https://github.com/user-attachments/assets/ea56ec0b-5442-4710-a199-70f48539f3fd)

**Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=31920-206931&t=KHqeIfjPkOOoqorB-0

...............................................................................................

**Consider 3 cases of backend failure:**

- _Superhero backend is down (Multisig backend is OK):_ Status: "Temporary backend failure." + question mark button opening "Backend failure" modal. Wording and design:

![Image](https://github.com/user-attachments/assets/7e3ed78b-ffcd-4bb7-9302-5edbfd604bcb)

![Image](https://github.com/user-attachments/assets/3ad42020-e139-47da-8316-3f8aded0ff87)

- _Both backends are down (Superhero and Multisig are DOWN):_ Status: "Temporary backend failure." + question mark button opening "Backend failure" modal. Wording and design:

![Image](https://github.com/user-attachments/assets/902a04c8-5f1a-4e8b-8003-b76df8b4ecc3)

![Image](https://github.com/user-attachments/assets/68801e8d-b7d6-4fc5-a9cd-fc53d09ce104)

![Image](https://github.com/user-attachments/assets/e6155569-fa7c-4719-bbb4-aeab3341612f)

- _Multisig backend is down:_ Status: "Temporary backend failure." + question mark button opening "Multisig backend failure" modal. Other features such as sending, transactions, names etc. will not be affected so the status message should be displayed **only on the Superhero Wallet dashboard**. Wording and design:

![Image](https://github.com/user-attachments/assets/7dd69b9d-e737-4426-aeea-05aef640a84a)
![Image](https://github.com/user-attachments/assets/0cda4d54-ebac-4464-967a-63776b6d8e5a)

**Design for different connection/network statuses and modals:**

![Image](https://github.com/user-attachments/assets/7cf0a035-9b81-4228-9248-a6fca0567cca)

![Image](https://github.com/user-attachments/assets/6dddb646-1157-4d5c-8767-05bba5502b0c)

**Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=21484-310195&t=KHqeIfjPkOOoqorB-0

**Prototype:**

https://github.com/user-attachments/assets/9e8d02ca-4c6f-449b-9ea9-ae7062dd92af

**Comment by Liubov-crypto** [comment]
I was not able to get UTXO error to check this modal. 

Also I'm getting a little bit different text about backend error: "Temporary aeternity backend failure" instead of "Temporary  backend failure". Is it acceptable @onvisions ? 

![Image](https://github.com/user-attachments/assets/a6adecb4-0596-4eb0-9d9e-ee19abd02641)
