### ISSUE TITLE
Networks page items misalignment

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#3030]
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/7c5bc00a-2171-43dc-ad34-55692b3ec217)

**I suggest** implementing shortening and the horizontal animation for displaying long URLs here. We have this feature ready and we use it at several places such as the dashboard Latest transactions widget.

**Comment by peronczyk** [comment]
We agreed with @onvisions that the URLs won't be scrolling. I updated the spacing between the node urls so now it's easier to read them.

Tsvetan requested to not apply the opacity change to action buttons (edit/remove) when the network is not activated (checked).

The task is ready to be reviewed @Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM

**Comment by onvisions** [comment]
> We agreed with @onvisions that the URLs won't be scrolling. I updated the spacing between the node urls so now it's easier to read them.
> 
> Tsvetan requested to not apply the opacity change to action buttons (edit/remove) when the network is not activated (checked).
> 
> The task is ready to be reviewed @Liubov-crypto

Yes, because even if radio button is not active the user can click on Edit/Delete and edit or remove Network. So the buttons are active and shouldn't look disabled.
