### ISSUE TITLE
Improve UX/UI of Send funds flow for AirGap accounts

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#3033]
**AirGap Send funds flow UX improvement**

**Prototype:**

https://github.com/superhero-com/superhero-wallet/assets/12225410/d7dab748-4ecc-4380-a414-746d21474ad2

**Figma reference:**
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=31920-199519&t=tx5uY0HU532wuFoQ-0

**Comment by smaroudasunicorn** [comment]
I am ok
