### ISSUE TITLE
Improve error message under amount input field when user's ETH balance is too low to pay for the tx fee.

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3037]
**Story:** When the users's ETH balance is too low to pay for the transaction fee we currently display "Not enough ETH balance" error.

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/df35e5ce-e006-4ea5-a9e0-86c21a80daab)

Users reported confusion when they are sending some token on Ethereum (different from ETH) about why they see such a message if their token balance is enough. The reason is that the user may not be aware the tx fees are paid in ETH.

**Suggested improvement:** update error texts for this field for all blockchains. As follows:

"AE balance is not enough to pay for transaction fee"
"ETH balance is not enough to pay for transaction fee"
"BTC balance is not enough to pay for transaction fee"

**Comment by Liubov-crypto** [comment]
LGTM
