### ISSUE TITLE
Improve logging of sent signed transactions, and allow exporting logs as JSON for support

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3039]
We would like to keep a log in the device of signed transactions. (timestamp, source, transaction information). Also in case there is an exception during signing of a transaction then this should be logged too (error timestamp, error code, error description). User shall be available through settings to export logs and use them for troubleshooting.

**Comment by peronczyk** [comment]
@smaroudasunicorn can you add some description here?

@onvisions do you have any designs for this?

**Comment by smaroudasunicorn** [comment]
@peronczyk  @CedrikNikita @onvisions  updated the story, kindly check

**Comment by onvisions** [comment]
@smaroudasunicorn @peronczyk  **Based on the user story described above**

**ACCEPTANCE CRITERIA:**
- Rename "Save error log" button to "Error log" in Dashboard/More/Wallet settings/;
- Error log screen (../More/Wallet settings/Error log/) - update wording and design;
- Add "Export and disable error log" modal;
- Add "Export error log" button to all error templates.

**Functionality:**
- error log is disabled by default but the user can enable it on the Error log screen;
- the button "Export error log" is enabled only if there is already some saved error data;
- if the user choses to disable the feature a modal is displayed informing them that Error log will be exported and feature disabled. All collected error data will be deleted from storage.
- "The export error log" button in all Error modal templates should export not only log of the specific error but the whole Error log saved by Superhero wallet. So functionality is the same as the export button on Error log screen.

**DESIGN:**

![Image](https://github.com/user-attachments/assets/1dcc4460-ebae-4e27-8afc-d65d0bffbc93)
![Image](https://github.com/user-attachments/assets/6fa920be-3df6-4d84-9d8b-4f7f757bba66)
![Image](https://github.com/user-attachments/assets/4ec20ca6-3c03-4a6f-8725-32c5408a59db)
![Image](https://github.com/user-attachments/assets/f5c3a983-26af-4739-b011-42d0791bd487)
![Image](https://github.com/user-attachments/assets/a3ab671f-3300-420f-bcb0-ac0944483c4c)
![Image](https://github.com/user-attachments/assets/bd30a307-474b-4dc5-8404-c8a7386e5251)

Examples of error modals integration:

![Image](https://github.com/user-attachments/assets/c33950d9-f921-424a-8471-b0e3701ce49a)
![Image](https://github.com/user-attachments/assets/c56b4a45-1e14-4516-8b53-a06690089cc4)
![Image](https://github.com/user-attachments/assets/ab89268a-82cf-4f7b-abf3-817b9f675583)
![Image](https://github.com/user-attachments/assets/04a85f70-9a3f-46e1-997c-396b555530e3)


**FIGMA REFERENCE:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=34473-242489&node-type=frame&t=Ci7dWQbVH2IkkvxC-0

**Comment by smaroudasunicorn** [comment]
About the Error Log Description

Superhero Wallet logs errors, when encountered in a log file in device storage (with maximum size?). File can be exported in json format for debugging or support from Superhero Wallet team.

When keep error log is enabled below, error log can be exported in .json format.

Also the export error log button shall be visible to modals only if keep error log is enabled. Besides that I am ok. Thanks

**Comment by onvisions** [comment]
@smaroudasunicorn Wording update for Keep Error log. 

![3 1 Error Log - not keeping](https://github.com/user-attachments/assets/15f8514a-652d-48db-a2de-dcc4b910173c)
![3 2 Error Log - Keeping](https://github.com/user-attachments/assets/b355c1dd-2eca-440e-b687-b01f047687c4)

**Comment by smaroudasunicorn** [comment]
I am ok thanks

**Comment by Liubov-crypto** [comment]
1. I was able to download error logs, but not able to get any error modals this time. 

2. I found that there is  different wording compared to Figma. ![Image](https://github.com/user-attachments/assets/2bd52e54-fc13-48d4-8511-dc1eed8f97bd)

3.  I enabled "Keep error log" but "Export error log" button is muted. I assume it's expected because wallet doesn't have any error logs yet. Correct?

**Comment by alex-k8** [comment]
@Liubov-crypto 
2. I think the one I have is the newer one but it hasn't been updated on Figma @onvisions 
3. Correct. If there are no logs, the button is disabled
