### ISSUE TITLE
Improve UX/UI of Import AirGap Account(s)

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#3045]
**Prototype:** 
Importing multiple accounts:

https://github.com/superhero-com/superhero-wallet/assets/12225410/77c5f226-f621-4078-af97-a5db57eb8497

**_Sub-case:_ Import a single AirGap account ->** 

https://github.com/superhero-com/superhero-wallet/assets/12225410/caabc1d9-ce0f-48f8-bc06-254ac20f27d3

Mockups:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/21a03706-11fb-4db9-b61b-8ce814a66f53)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/00cc0ded-144f-4e8e-ba14-43a26117bee6)

**Figma reference link:** 
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=31920-199513&t=Jx02TBkFDOXYIgxj-0

**Comment by smaroudasunicorn** [comment]
how do we treat if an account is already added in the wallet. Do we show it here? @martinkaintas  @onvisions

**Comment by martinkaintas** [comment]
> how do we treat if an account is already added in the wallet. Do we show it here?

It is shown but it is disabled

**Comment by smaroudasunicorn** [comment]
great, I am ok.
