### ISSUE TITLE
Generic template for AirGap sign&broadcast transaction

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#3048]
**User story:** we need to have a generic template apart of the "Send funds" flow to be used for all other cases of signing and broadcasting a transaction with AirGap. 

**Designs:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/e4aac024-bebc-4952-9895-ab94b2708000)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/a2c4dd66-605e-47e6-b2d5-c56b4f94e585)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/9d962adc-5b7b-405e-819e-9688f24718e5)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/cf89924b-5c4c-48d0-880f-bb15abd61731)

**Comment by smaroudasunicorn** [comment]
I am ok
