### ISSUE TITLE
Display QR code scanner messages in the scanner box

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3051]
This task is about refactoring the **QR Code Scanner modal** so the messages informing about the lack of camera access would be displayed in the camera box instead above it.
This allows to:
- have the modal title to be visible no matter if user has the camera access - useful since we use this modal for scanning different QR codes.
- not show the spinner all the time.

Also the side spaces are now smaller to allow the scanner to be bigger.

**Before:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/52481867-a5a6-46af-ab0e-2eac580b52ec)

**After:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/d52437d2-a29b-40b7-8a63-85a64e1d9254)

@onvisions

**Comment by Liubov-crypto** [comment]
LGTM. 
I managed to disable the camera in Chrome extension and got a proper modal for a second (screen from a video recording): 



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/31b6d0c6-f609-439a-9b71-515ed080a533)



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/4abc0338-0c0f-4a6e-9002-1c88de62bde8)

**Comment by onvisions** [comment]
@peronczyk @Liubov-crypto

1. Styling of text and warning icon updated for consistency.
2. Top Scan icon appearance updated to match similar items.
![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/2a871543-7fc6-43ae-af13-a2d880205849)

**Designs:**
![Scan QR modal-2](https://github.com/superhero-com/superhero-wallet/assets/12225410/30c93ddc-bf7a-4df2-b9c9-3b34735b213d)
![Scan QR modal](https://github.com/superhero-com/superhero-wallet/assets/12225410/5579a470-2a02-40ff-944d-9c9a704e1750)
![Scan QR modal-1](https://github.com/superhero-com/superhero-wallet/assets/12225410/3f26820e-2196-44d5-b419-018b00a0221c)


**Figma reference link:**
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=31920-189838&t=Q3Abg2TTxChnOcj6-0

**Comment by peronczyk** [comment]
I've updated the messages colors.

Regarding the icon background color it's not that easy. Right now we can set 2 predefined variants to icon: `danger` and `success` which adds corresponding background color. But we are not able to set any BG color.

Also those success/danger variants changes the border color for the icon. I suggest to create separate task for this and create some kind of list of variants or options so it would be easier to develop it.

@onvisions
