### ISSUE TITLE
Update display of Tx amount, gas, fee, total. Sub-case: multisig tx proposal template.

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#3057]
@CedrikNikita @smaroudas 

**Story:** We need design update of the display of transaction **Amount + Gas used cost + Fee = Total.**

**Acceptance criteria:**
- implement the feature following design below. Recheck margins between elements and update where needed;
- implement the design for sub-case of multisig transaction proposal where user should see the Proposed transaction amount and fee + Proposal gas cost, fee and Total. See design below;
- Update the template for Multisig Tx Proposal details accordingly. See design below.

**Design:**

**_Send Funds flow:_**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/5179214b-2445-4e39-bf31-13f868e02593)
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/56c4af59-a75f-469e-82e0-f12b92340dcc)
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/cbe1d523-aff4-4ee1-9942-2cd9aa567d25)

.................................................................................

**_Multisig tx proposal:_**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/086b8095-2a63-433f-b4e8-5502e1dcecb6)
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/632f8bd6-0f97-42af-84bf-6e8d3e8e8183)
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/09a24f18-8898-40ae-a999-0905acb5e9d2)
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/9164cadc-0925-47d0-bbcc-3636a0e22fcc)

**Figma reference:**

1. _**Send Funds Flow:**_ 

https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=32135-195480&t=4Ghuxw4IqUzgRRKi-0

2. _**Multisig Transaction Proposal, Review, Details:**_ 

https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=32135-202575&t=VkSNKnzv1XJGXQ1H-0

**Comment by smaroudasunicorn** [comment]
Screen Review Transaction
Do we need to display 90504 @000000.....

Screen Transaction details

why do we say minus in the 10.10? I see it in other screens too.


Multisig Proposal Details

Maybe to change the wording of Proposal to Proposal Used gas cost (and the below labels) to something like Approval Gas Cost?

**Comment by onvisions** [comment]
1. We don't need to but it shows how much gas is spent, at what price and what's the total cost of gas used for the transaction.
So 
![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/896ee1af-7731-47db-9a57-9e6707ffb5f4)
can be also presented in three different lines but it will take much more space (scrolling) and it won't make it more readable IMO.

Alternative version comparison side by side:
![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/dadb99d3-158d-4b86-8af8-6041c3b68d73)

2. **-10.10 AE** means the amount is going out of your wallet (being sent or spent). So it's deducted of your balance. It's an SPEND OUT transaction, fee, gas etc. The minus is a way of showing this without using red color or something like that.

On the contrary, when you are receiving some amount we show it in green (without plus sign because it makes everything more visually cluttered and "busy" and it's clear enough because of the color).

This visualization was suggested by me and Paolo. Implemented 2 years ago I think.

**Comment by smaroudasunicorn** [comment]
I prefer the alternative about gas info, Regarding the -minus and colouring it makes sense IMO in the transaction list (along with the colours). In transaction details I am fine (although I believe just the number would be ok).

**Comment by onvisions** [comment]
@CedrikNikita  **Updated designs:**

_Send Flow:_

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/114777ce-43fc-44a6-9142-55bef4f47104)
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/49131059-0169-4e1b-b01c-d3a1b7e8d95d)
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/61bf5c25-c6bc-4fed-b275-3eba6fd1d8d5)


_Multisig FLow:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/a13d72ff-d453-4dd9-9f81-9755a2d51ef4)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/1f71582a-1be7-40e2-a2eb-0f722e2d6d8d)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/e6d8b94a-3cba-4275-8a9c-2f55db5ae2d5)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/cfe3ae84-8555-4bd2-a4d1-b087265c4c5d)

Figma reference:

Send Funds Flow:
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=32135-195480&t=4Ghuxw4IqUzgRRKi-0

Multisig Transaction Proposal, Review, Details:
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=32135-202575&t=VkSNKnzv1XJGXQ1H-0
