### ISSUE TITLE
Streamline the logic of transactionData composable

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3060]
This task is about changing the way how we pass the transaction informations to `transactionData` composable.  Those changes are required to proceed with WalletConnect task: https://github.com/superhero-com/superhero-wallet/issues/2664

**List of changes:**

1. Passing the `transaction` reference to the `transactionData` composable instead using `setActiveTransaction` method.
2. Updating the dex related states in the `transactionData` composable.

**Affected places:**

1. **ConfirmTransactionSign** modal - establishing the type of swap method
2. **SwapRates** modal - establishing the tokens involved
3. **SwapRoute** modal - same as above
4. **TransactionDetails** page - establishing the tokens when swapping/pool on DEX, establishing the tags at the top of the page
5. **TransactionListItem** - establishing the transaction direction
6. **MultisigProposalDetails** - small tweaks on how the `transactionData` composable is used here (check if nothing is broken)

As this task is about refactoring logic no visual change was done. Tests should check if there are differences between this branch and the develop within mentioned places.

**Comment by Liubov-crypto** [comment]
LGTM
