### ISSUE TITLE
Update Transactions blockchain description - æternity is the blockchain and AE is the coin

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3063]
Sample 

![Image](https://github.com/superhero-com/superhero-wallet/assets/103504859/dea973aa-aeb8-4d32-be59-29768ab73789)

**Comment by peronczyk** [comment]
This also affects the asset details page:

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/00f236bf-8d29-4931-989e-429dc73a74ef)

Task is ready to be tested @Liubov-crypto

**Comment by Liubov-crypto** [comment]
is this correct displaying of tx? 

![tx](https://github.com/superhero-com/superhero-wallet/assets/69896204/156978b9-4e13-4aa0-80a6-2b228cd19d84)

https://aescan.io/transactions/th_2YkBzEuhUt5wyBQ64fvrDFW8mqBPcLnUF5h28AbmuWTmTJxuYF

**Comment by peronczyk** [comment]
I have updated the PR. Please take a look again @Liubov-crypto 

Regarding DEX filter: this was not a part of the task. Let's discuss this in the chat.

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
