### ISSUE TITLE
Panel Table Item component

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3066]
This task is about splitting out the code responsible for displaying the Card Table Items in the "About" page into separate component:
![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/ded10644-c2a4-4de2-8024-d2a2114cedf9)

This component is required by the **WalletConnect** modal.

@Liubov-crypto please check if the "About" page didn't broke after my changes.

**Comment by Liubov-crypto** [comment]
there should be node version: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/1972f0af-554b-4e1a-959f-cebd2caacdf9)

**Comment by peronczyk** [comment]
Fixed, please see now.

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
