### ISSUE TITLE
ETH chain ID set as regular number instead of hex

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3068]
Right now when creating new wallet network we need to provide the Chain ID for ethereum protocol. Required format is HEX, but actually it is more common to use regular numbers when interacting with user. Then convert the number to HEX when doing any blockchain activity.

See here: https://docs.simplehash.com/reference/supported-chains-testnets - the Chain IDs are thumbers located after `eip155:`.

This task is about using the **INTegers** instead of **HEXadecimals** values.

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/903d6045-5d56-48f9-a98a-ad6cfb5327f9)

So instead of ETH Mainnet `0x1` we need just use `1`.
ETH Sepolia Testnet: `0xaa36a7` => `11155111`

This change affects connecting to ETH networks, so tests should also cover sending some ETH/ERC-20 funds on any network.

**Comment by peronczyk** [comment]
Yes, previously the testnet Chain ID was also used as the default value when adding custom network. The only difference is that it was using hex value instead of numerical.

**Comment by Liubov-crypto** [comment]
On testnet it looks fine, so could be approved I think.
