### ISSUE TITLE
Ultra slow response for transaction history, incomplete information displayed

### ISSUE THREAD

**Issue by nikita-fuchs** [superhero-com/superhero-wallet#3072]
Although this might have to do with the mdw performance, but the SH wallet users are directly affected. I actually wanted to record the TX list missing recent transactions, but then found out the most likely reason for that: The fetching of the latest transactions (which is probably ran in the background and the user doesn't notice) is slow beyond reason. What could be the cause for this? Do we agree we want to work on improving this?

Video: https://youtu.be/odKTb80ltpY

**Comment by CedrikNikita** [comment]
Hi, @nikita-fuchs.
We experienced some problems with the backend endpoint that we are using to receive tip withdrawn transactions.
`https://superhero-backend-mainnet.prd.service.aepps.com/cache/events/?address={address}&event=TipWithdrawn&limit=5`
The time needed to get the response from this endpoint was in minutes. It was fixed on the backend side.

**Comment by nikita-fuchs** [comment]
Cool, it works fine now, thanks!
