### ISSUE TITLE
Display coin transactions for paid fees in coin transaction list

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#3081]
User should be able to navigate to Coin transaction list and see coin transactions for fee paid.
e.g. User transfers 10 LINK and pays 0.1 ETH for fee: 
- user should see one transaction in the "All transactions" list (`value=10LINK`)
- user should see the same transaction in the "LINK transactions" list (`value=10LINK`)
- user should see an ETH transaction for the fee he paid in ETH in the "Ethereum transactions" list (`value=0.1ETH`)

Clicking on any of those transactions takes the user to the same transaction details page _(showing both the value and the fee)_
The ETH transaction (fee transaction) should be differentiated from regular send transactions. It should be clear to the user that this is just the fee that was paid for the transaction.

This applies to all blockchains with tokens

**Comment by onvisions** [comment]
@martinkaintas 

1. Labeling for the specific case of transaction fee item: "Transaction fee paid" (see mockups below).
**Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=31920-204697&t=xkxejuN2HvrwbOfy-0

**Design:** 
![image](https://github.com/superhero-com/superhero-wallet/assets/12225410/99dc165a-683a-4564-b25c-4ce3912c37f9)

2. **IMO** when the user goes from Asset/Transactions to Transaction details the back arrow button should lead back to previous screen and not to the all transactions list of Dashboard/Account details/ 
As a user I'd expect this behavior when clicking on back. I'd suggest an exception from implemented routing rules in this case.

**Comment by smaroudasunicorn** [comment]
This can be closed, we will treat it in another way
