### ISSUE TITLE
Enrich Transactions - Display Tokens Exchange

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3083]
When a transaction takes place through token swap we need to display the token exchange in a similar format like DEX Transactions. 

We need to display additionally the fee incurred in the transaction.

**Comment by smaroudasunicorn** [comment]
Sample Screenshot 



![Image](https://github.com/superhero-com/superhero-wallet/assets/103504859/140cb7c4-be45-4de7-b918-ef2ebf3debad)

**Comment by smaroudasunicorn** [comment]
We need to check the contract type to define this

**Comment by smaroudasunicorn** [comment]
@davidyuk any update with the callData Library issue communicated by @martinkaintas  to support this implementation? Thanks,

**Comment by davidyuk** [comment]
It is implemented in https://github.com/aeternity/aepp-calldata-js/pull/279 , it needs to be merged by @dincho and released after that.

**Comment by smaroudasunicorn** [comment]
On hold until dev.tokaen.org is working for this feature
