### ISSUE TITLE
Share my address as a QR Code to another wallet

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3085]

**Comment by onvisions** [comment]
Add "Share your public address" feature to Account Details to easily share user's currently active account address. Thus another user can scan it in order to add address to the Address Book.
The focus is only on sharing the QR code VS existing feature of Receive modal.

**Design:**

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/453db48f-7fe4-465f-9bde-c8598f946524)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/094058d9-d5d0-4623-809f-66217ea865d1)

"Share your public address" prototype:

https://github.com/superhero-com/superhero-wallet/assets/12225410/7a993f23-9cf5-4a3a-88a4-fec254023103

**Figma reference:**
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=32318-214776&t=A0CnfnkVwVvR6YBF-0

**Comment by smaroudasunicorn** [comment]
In receive/send area add a button share and then make the modal.

**Comment by onvisions** [comment]
**Latest design update of the feature:**

DESIGN:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/826969d4-5cd8-4e04-8f0d-dda57d1878b3)



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/d4363003-a836-44a0-8310-ed928b14a330)



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/dfca0b52-5a53-43f6-9174-a145e7e1d0fa)



**Other UI spots where the "Share" button should be/should be not displayed:**


**_Multisig vault (button is displayed):



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b4bbd4a8-8959-451e-9518-2f02a1266ffb)




Coin/Token Details screen(button is not displayed):



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b55dc53c-c22d-4b1d-8326-6c72b3744c98)




Not connected status (some buttons are disabled, this one remains among the active buttons):



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/6abe9fcd-d936-4b98-aaf9-b5e480a35171)



Testnet (button is displayed):_** 



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b6ce01ea-2e39-445b-a60e-ac5216c97a4d)


PROTOTYPE RECORDING:

https://github.com/superhero-com/superhero-wallet/assets/12225410/ae474032-46f5-498d-906c-eed72e5141b8



FIGMA REFERENCE: https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=32458-208036&t=Z3E7qGnY5G7fUnbv-0

**Comment by smaroudasunicorn** [comment]
there are cases we might have 5 buttons as we are now?

**Comment by onvisions** [comment]
@smaroudasunicorn **Latest design update (14.06.24)**


**PROTOTYPE:**

https://github.com/superhero-com/superhero-wallet/assets/12225410/f72f49b3-9f4f-42aa-b93d-e37e0d5b85bd

**DESIGN:**

_Share public address modal:_

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/af4a091a-be28-44fa-81a1-66b963a5a56e)

_Share public address modal:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/1b9ba5ac-b76f-4106-a940-0292dd57fbf9)


_Mainnet - Account Details - 3 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/73f7d688-4a8a-4038-9140-f945d0d2a39f)


_Mainnet - Account Details - 4 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/cde3487c-0373-4db2-af98-c19cb374db74)


_Testnet - Account Details - 5 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/3950c7fc-37b2-4d67-a97f-e080d0ebb8f6)



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/3b324a42-d3db-41ef-8473-ed07a381fb18)




_Mainnet - Single Asset - 3 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/478ccafb-e741-457d-a862-fe740ef5e5f0)


_Testnet - Single Asset - 4 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/88224c5b-8f4c-46aa-835c-c4945046f422)


_Multisig vault - 3 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/24327930-1139-4aa2-b62f-42fa33b7691a)


_Mainnet - not connected - 3 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b87ccfcc-e806-4c22-8bcb-3d87ed38313c)


_Mainnet - not connected - 4 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/c3b1ab9d-338d-489e-926c-f4436fd911f7)


_Testnet - not connected - 5 buttons:_


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/f1826b07-aee6-4961-88cd-21b96e741b5b)



![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/ba47a17d-b5d3-4588-835f-cf886e898e16)




**FIGMA REFERENCE:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=32458-208036&t=ZOSrxOrFVgnQ8L6R-0

**Comment by onvisions** [comment]
**Alternative design version without horizontal scroll for the case of 5 buttons:**


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/dbca41b3-7f2a-460f-bc3b-01321ebd9517)

**Comment by smaroudasunicorn** [comment]
I believe 2 option seems to be the best fit. option 1 would be great but I think the buttons would be very small in small devices. What do you think @martinkaintas ? @onvisions

**Comment by onvisions** [comment]
> I believe 2 option seems to be the best fit. option 1 would be great but I think the buttons would be very small in small devices. What do you think @martinkaintas ? @onvisions

We can use V1 (with 5 visible buttons) for viewport width down to 360px and make it scrollable horizontally for smaller device screens.
However I think most neat solution is 
![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/cef4c701-e25c-415b-8ab5-b9058d513cd6)

**Comment by Liubov-crypto** [comment]
I have a question @onvisions @martinkaintas , is here supposed to be 3 buttons on Coin details page? according to the design it should be 4 buttons: 


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/0277b302-ee55-42dd-82b2-6ae545c5ef35)

the rest LGTM (haven't tested ios app)

**Comment by martinkaintas** [comment]
The Swap button was removed from the AE asset page some time ago in https://github.com/superhero-com/superhero-wallet/commit/a0405e2b6ef9d841502d5fe475ec4b854d3bc9a0
