### ISSUE TITLE
Remove unused prop value calculations from Transaction Overview component

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3088]
Right now the `TransactionOverview` is passing following props to `TransactionInfo` component:

1. `title`
2. `sender`
3. `recipient`
4. `transaction-function`
5. `transaction`
6. `additional-tag`

Unfortunately `TransactionInfo` does not support the `transaction-function` and `sender` props.

This task is about removing the logic that calculates these unused props. This is the affected area of the app (transaction details top):

![Image](https://github.com/superhero-com/superhero-wallet/assets/8217670/45dfbf2e-6c48-4b8b-9578-9f19d9ba2fe2)

As this is a refactoring task the UI should not differ from the dev version of the app.

**Comment by Liubov-crypto** [comment]
LGTM
