### ISSUE TITLE
Show full amount for wrapped tokens in Tx details

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3097]
**Describe the bug**

I made swap from WETH to ETH with  tags on confirmation modal: App.Uniswap.org and Contract call: 
 

![weth](https://github.com/superhero-com/superhero-wallet/assets/69896204/6b1ae89a-72bc-4bd7-9932-994c1f293396)

when Tx will be fetched I will see it with Spend Out tags and only with ETH fee amount (agree that we can't display full amount atm): 

![weth2](https://github.com/superhero-com/superhero-wallet/assets/69896204/3cb5e6b7-22e6-4e18-825b-adcf8da39516)

Also WETH Tx will be not available on WETH assets details page in Incoming Tx list. 

**To Reproduce**
1. Go to uniswap
2. Connect the wallet
3. Swap WETH to ETH
4. Check tx details

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 123

**Additional context**

**Comment by smaroudasunicorn** [comment]
@CedrikNikita  please help to close.
