### ISSUE TITLE
Address Book -  Select Recipient from addressbook by typing his name when sending funds

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3102]
**STORY:** As a user I'd like to be able to get a dropdown list of suggestions while typing recipient's name in the Recipient's address input on Send Funds screen. 

**ACCEPTANCE CRITERIA:**

- Add a dropdown list of recipient's address suggestions while the user is typing. The user gets suggestions in real time listed in the dropdown below the input.

- The dropdown is triggered _**only**_ if and when the user writes 2 or more characters in the input and there are valid suggestions containing the written combination; 

- Characters allowed are any valid symbol that can be used in a blockchain address or custom Address book name;

- All blockchain addresses OR address book names containing the given combination of symbols. For example "ak_d" returns:

**ak_d**VSngpKu2Q4QxTpKmC9cJYTgdjp2ok5HdcdwocLAmwNqSCzDf (shortened)
Contact01 **ak_d**xyz
Contact02 abc**ak_d**

and **"JYTg"** returns:

ak_dVSngpKu2Q4QxTpKmC9c**JYTg**djp2ok5HdcdwocLAmwNqSCzDf (shortened)
contactname**JYTg**
**JYTg** accounting
**JYTg**xyz
Contact 5**JYTg**
etc.

- Suggestions list ordering: last 5 addresses (from "Recent"), bookmarked, own, address book, the rest of the "Recent". There should be no duplicates. 

- Dropdown has max height of 240 px and then its content is scrollable;

**DESIGN:**

![Image](https://github.com/user-attachments/assets/5a03164e-3668-4f83-a623-e6d321783afc)

![Image](https://github.com/user-attachments/assets/33b917ed-c63a-4fb1-ad18-07d87d414400)

![Image](https://github.com/user-attachments/assets/e050ee33-2c50-421d-8c2c-b66f948122de)

![Image](https://github.com/user-attachments/assets/9e52f591-df86-4139-9a1c-eb602fdd90b2)

![Image](https://github.com/user-attachments/assets/4bf4fa28-41f1-465a-8349-9c871838b958)

![Image](https://github.com/user-attachments/assets/aac193ea-0e52-423c-a791-41f9d615cad4)

![Image](https://github.com/user-attachments/assets/43ed84df-3fc4-41a8-bad1-db643a78d97d)

**Places to implement:**
- Recipient's address input on Send Funds screen;
- Recipient's address input on Propose transaction screen (Multisig);
- Signer's address input on Create new multisig vault screen (Multisig).

**FIGMA REFERENCE:**
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=36720-246626&node-type=frame&t=0qFKMBlk9a6bxjM3-0

**Comment by smaroudasunicorn** [comment]
I am ok

**Comment by Liubov-crypto** [comment]
I have a question: is dropdown searching only include accounts from address book? 
Because I have imported accounts via private key and they are not included into search in dropdown menu. Is it correct? 
As I understood from Figma design they should be included. 

https://github.com/user-attachments/assets/c31773e2-fd30-4e47-9491-a219b0cb496c

**Comment by alex-k8** [comment]
> I have a question: is dropdown searching only include accounts from address book? Because I have imported accounts via private key and they are not included into search in dropdown menu. Is it correct? As I understood from Figma design they should be included.
> 
>  2024-10-29.1.23.34.mov

Only addresses from the Address Book are shown. The figma is not up to date, @smaroudasunicorn please verify, I think this is how it was decided in the end. For the imported accounts, they will be visible in the Address Book modal, which will be added on issue #3168
