### ISSUE TITLE
Address Book: Send to address book record

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#3104]
> **Address Book Design ** _(updated after feedback 31.05)_ @smaroudasunicorn @martinkaintas 
> **4. Select address from Address Book modal (Send funds flow):**
> 
> 
> 
> ![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/c9774781-b736-44d7-89fa-3f4ef59bdefe)
> 
> 
> 
> ![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/39b06e11-d343-4a37-a0ad-53434b48fb0a)
> 
> 
> 
> Select account address from address book modal:
> 
> 
> 
> ![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b9d866d3-28b5-44f7-91e4-8198ca7c0f7f)
> 
> 
> 
> ![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/4db4f8ce-2f95-470b-a892-5b03eb4f8a65)
> 
> 
> 
> ![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/c8b121f3-fae9-4de9-a4ee-3e5037e0ba92)
> 
> 
> 
> ![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/b6ca5153-cc2b-4a76-aa07-8ff571872b68)
> 
> 
> 
> ![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/08b302b0-48d8-48a6-b03e-618b152e720f)
> 
> 
> 
> 
> 
> 6. Send funds using Address book prototype recording: 
> 
> 
> 
> https://github.com/superhero-com/superhero-wallet/assets/12225410/a2b96955-fe12-4e49-9bbf-b78d5fcbdd0e
> 
> 
> 
> 
> 
> 
> **Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=31935-180432&t=gZlJbeKQFrjFsfqj-0 

 _Originally posted by @onvisions in [#3036](https://github.com/superhero-com/superhero-wallet/issues/3036#issuecomment-2142124204)_

**Comment by onvisions** [comment]
@smaroudasunicorn 
After discussion with @martinkaintas we agreed that the design of Select recipient address from Address Book modal can be improved. The thing is we don't need any blockchain filters and we should display _only_ the addresses for the blockchain of the current active account. It totally makes sense as the Send flow is initiated from a specific active account and therefore we already have the given blockchain preselected. 

ACCEPTANCE CRITERIA:
1. Within the Select recipient's address modal remove blockchain filters and leave only All and Bookmarked; 
2. The initially preselected filter is Bookmarked (as it's like a "favorite address list");
3. The Search is displayed on both All and Bookmarked tabs if the address records in All addresses list are more than 9;
4. If the user is on "Bookmarked" (star icon tab) and the address being typed is not bookmarked the active tab is auto-changed to "All". See design below.

Updated DESIGN: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/c615af23-651a-4a1a-bcc4-e9f74f0f7b2f)


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/90baa974-6c0c-4927-9afb-428c81e296a7)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/e4bea6e6-0b91-48c7-9fd1-7ea3116e7a59)

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/af2a8ca2-48b7-44c2-89d1-a89b7c342a58)
