### ISSUE TITLE
QR related to airgap vault is blinking in FF

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3117]
**Describe the bug**
QR related to airgap vault is blinking in FF and it's hard to scan it

**To Reproduce**
1. Create multisig with airgap vault account
2. Try to propose tx
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version 127.1.0

**Additional context**

![qr code ff](https://github.com/superhero-com/superhero-wallet/assets/69896204/b0e8441b-fc76-4945-815d-b02b21c0cdbb)
![qrc](https://github.com/superhero-com/superhero-wallet/assets/69896204/689b4437-bdb0-4074-8703-f42c91076224)

**Comment by smaroudasunicorn** [comment]
kindly check it

**Comment by Liubov-crypto** [comment]
@smaroudasunicorn  reproducible for me in FF with web wallet on dev branch. 


https://github.com/user-attachments/assets/71d208c7-8807-41aa-9589-cd7a1d9ac0c5
![qr err](https://github.com/user-attachments/assets/228ef3fa-c9b1-49c0-af64-85360bd37cc1)
![sc wr](https://github.com/user-attachments/assets/25e91dcc-9f8d-424e-bf32-e95a9253ebfe)

https://github.com/user-attachments/assets/02acb64e-06b1-49fd-b830-cf2c9accb645


![vuejerr](https://github.com/user-attachments/assets/44175616-daf1-4a5f-8273-75276aa70429)



https://github.com/user-attachments/assets/4dcd1c43-0d1c-4e83-8eda-a351943c7ca8

**Comment by martinkaintas** [comment]
> @smaroudasunicorn reproducible for me in FF with web wallet on dev branch.

In the first video the QR code (**generator**) seems to be working as expected. It is slow and shows the white screen in-between QR codes but this is the fix right now for FF. 

> I started to scan QR code from airgap vault and after some time wallet qr scanner is stop working:

This is unrelated to this issue. I suggest to create a separate task as this related to the QR Code **Scanner**

**Comment by Liubov-crypto** [comment]
@martinkaintas agree. Created a separate issue.

**Comment by smaroudasunicorn** [comment]
Just to be checked in the future.
