### ISSUE TITLE
Global font definitions and typography tweaks

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3154]
Currently if we don't explicitly set the font family on each of the screens the text will be displayed with default system font (in most cases Helvetica). The task is about setting up the app's default font in one place and remove duplicated styles/font definitions.

Also after discussing this with @onvisions we agreed that all texts displayed with "Bold" as the `font-weight` will be now displayed as "Semi Bold" (little bit lighter variant). So we won't have any reference to "Bold" in the styles.

Final thing is to decrease the font variants (size+weight) in the system and trying to stick with typical styles. See for example here: https://vuetifyjs.com/en/styles/text-and-typography/#typography

**Comment by peronczyk** [comment]
@onvisions it would be great to have these font variant names mirrored in the Figma. So instead of having to check the size+weight+line-height we could base on some general naming, like `heading-1`, `caption`, `description`...

**Comment by peronczyk** [comment]
This task is ready to be tested.
As this task is strictly about visual tweaks in many cases agreed on private conversations with @onvisions I suggest that this task needs to be tested & approved by him.

**Comment by onvisions** [comment]
@peronczyk approved
