### ISSUE TITLE
Add address book functionality to multisig vault creation

### ISSUE THREAD

**Issue by martinkaintas** [superhero-com/superhero-wallet#3163]
Include the address book functionality here

![Image](https://github.com/superhero-com/superhero-wallet/assets/49337371/39266c6b-0f8c-4aaf-9b9a-5d52152f9026)

like it is here

![Image](https://github.com/superhero-com/superhero-wallet/assets/49337371/80ebb98b-01e9-48a5-8c93-8e9956304944)

**Comment by Liubov-crypto** [comment]
LGTM
