### ISSUE TITLE
`LinkButton` color update

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3175]
This task is about changing the text link buttons color and hover color from green (success) to blue (primary) one.
Also the link button should inherit the font size and weight from the text that surrounds it. Right now the size was forced to 14px.

**Before:**

![Image](https://github.com/user-attachments/assets/1c3a6a92-07e8-46b2-b21c-60c6bc58040b)

**After:**

![Image](https://github.com/user-attachments/assets/af34863e-ed64-4d86-a91a-f52129da251f)

Affected pages:
1. Permission manager
2. More > About page (link entries)
3. Terms & Privacy pages
4. Multisig vault > Details (explorer link)
5. Transaction details pool (explorer link)

**Comment by peronczyk** [comment]
@onvisions can you test the changes?

**Comment by onvisions** [comment]
@peronczyk I agree with the suggested changes. @Liubov-crypto can test it across UI as listed above.

**Comment by Liubov-crypto** [comment]
LGTM
