### ISSUE TITLE
Align input disabled, focus and hover state with figma designs

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3185]
This task is related to recent WalletConnect modal feature. If user didn't have any ETH account the WalletConnect URI input should be disabled. But the disabled state does not match the  figma designs: https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=28292-295974&t=24HwgckDPVQi67PS-4

Also @onvisions noticed that if user clicked (focus in) any icon placed in the input's label section without clicking out (focus out) and then move the mouse in any direction the input looks focused but it shouldn't.

This is the current bad behavior:

https://github.com/user-attachments/assets/0828374a-0331-44a7-8aeb-837d1752e649

**Comment by Liubov-crypto** [comment]
A little bit different design compared to Figma: 

![Image](https://github.com/user-attachments/assets/8475cc35-04ad-448d-b2bf-9d67451f5508)

@peronczyk please check it

**Comment by peronczyk** [comment]
> A little bit different design compared to Figma:
> 
> ![Image](https://private-user-images.githubusercontent.com/69896204/355133184-8475cc35-04ad-448d-b2bf-9d67451f5508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzM1NzIsIm5iZiI6MTcyMzAzMzI3MiwicGF0aCI6Ii82OTg5NjIwNC8zNTUxMzMxODQtODQ3NWNjMzUtMDRhZC00NDhkLWIyYmYtOWQ2NzQ1MWY1NTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEyMjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZWNmNmFlZGU4NmEyOGRjMWIwZmE3MjZjNDQ1ODBlMTVhOTU3ZWEzNDY3NWIxYjA2NzU2NmE0NWI4ZjRlN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iSuiM5n99UquoiG0gStYyC8Yf1oz6247Z84--J71bZw)
> 
> [@peronczyk](https://github.com/peronczyk) please check it

Regarding the header: this task was anly about the **input** styling. If you established that we have an issue in the current dev please create separate task. But I can say that it is not possible to display the connected app in the WalletConnect modal if user has no ETH account as he was not able to connect. So I guess the design is bad.

> Also I have a question about hovering: Is the correct pattern recorded in the attached video?

No, the attached recording is about the current state. It shows the situation where the user hovers the icon but the input hovers also. And when the icon is clicked but the cursor moves up the field has darker background - like its active, but it shouldn't.

**Comment by Liubov-crypto** [comment]
@peronczyk  LGTM. 

I will create a separate task for wallet connect modal top part. But I agree that it is not possible to display the connected app in the WalletConnect modal if user has no ETH account as he was not able to connect
