### ISSUE TITLE
Encrypt storage of mnemonic

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3189]
**STORY:** Superhero Wallet mnemonic storage should be securely encrypted on user's device both for the browser extension and for the mobile apps.

**Research and suggestion (by @onvisions )** As far as I have researched several other crypto wallets they usually have password option for accessing web and browser extension and biometric/PIN authentication to access the mobile apps.

Based on that I think that introducing both password and biometric/PIN authentication (on mobile) will be an overkill and it will require more complex logic on mobile. Instead I suggest to have:

1. Secure login with Password for web wallet and browser extension.
- Setting a password will be required during creation of new wallet or import of existing one;
- Users who already have installed the wallet will be informed about the wallet being updated to a new version with upgraded security and that they need to set a password (modal to set pass before proceeding to Dashboard);
- For security reasons the password is mandatory. It cannot be turned off; 
- The user will be able also to set lock up inactivity period; Default is 5 mins. 

2. Secure login via default mobile device authentication method (biometric/PIN). This one we should already have implemented. I think **we don't need anything else on mobile** unless I'm missing something here. 
The user is able to set different lock up intervals for the wallet and the device screen so that for example the Superhero wallet is locked immediately and the device screen after 15 mins. which gives good control over the desired behavior. 

**DESIGN:**

_1. Set Password_

![Image](https://github.com/user-attachments/assets/a5f834d4-6f28-4a78-8fb3-75b8e017026f)
![Image](https://github.com/user-attachments/assets/634914cb-d713-4c44-8792-581fc187895a)
![Image](https://github.com/user-attachments/assets/5ec323d2-8d73-4973-acfc-b49d5e03b2ac)
![Image](https://github.com/user-attachments/assets/148a4cd6-a977-4290-8771-40c218a555b2)
![Image](https://github.com/user-attachments/assets/28f2710e-a37c-46da-b70e-503956741b93)
![Image](https://github.com/user-attachments/assets/79ba75aa-478b-4381-80d2-002e1e24eec4)
![Image](https://github.com/user-attachments/assets/f57e1704-fc3a-4281-b8de-8d07654d7b0c)
![Image](https://github.com/user-attachments/assets/16f55a50-69c2-4b99-8327-7f8226ea2659)
![Image](https://github.com/user-attachments/assets/34dbf944-18ce-43cf-b0a6-f005551f8746)
![Image](https://github.com/user-attachments/assets/2908640d-c058-47b2-a520-f051e07f038e)
![Image](https://github.com/user-attachments/assets/1fd6a392-36ab-4728-9994-88dbcaa51920)

..........................................................................................

_2. Upgraded Security Modal. Set password._

![Image](https://github.com/user-attachments/assets/af31cd78-661e-47a5-a0c4-5821136a89fa)
![Image](https://github.com/user-attachments/assets/d989ac42-9140-402b-9c07-33e7539a8676)
Recording: https://github.com/user-attachments/assets/80ba40ce-f1d8-4de6-8613-b0eba742e0ad

..........................................................................................

_3. Unlock with password_

![Image](https://github.com/user-attachments/assets/4913ef1f-46d3-42b0-bb4a-8ca15b00174b)
![Image](https://github.com/user-attachments/assets/57a4c9de-d00b-4330-9f08-3e4a9ff33a3a)
![Image](https://github.com/user-attachments/assets/ebd351d0-f2ce-4717-882c-c06f2836c378)
![Image](https://github.com/user-attachments/assets/5d09a883-93af-49f2-9641-75bdc37937c2)
![Image](https://github.com/user-attachments/assets/27f20fd1-11b2-4d32-bc7a-c210e626725a)
![Image](https://github.com/user-attachments/assets/6a1bfeaf-a22f-4dd2-91e3-a1f13887e033)
![Image](https://github.com/user-attachments/assets/80e41c12-8ada-457a-a45d-1279b93b7c44)

..........................................................................................

_4. Seetings: lock time interval, reset password_

Auto-lock Interval:

![Image](https://github.com/user-attachments/assets/d13a4094-c34d-4b48-84fe-139c60444aa7)
![Image](https://github.com/user-attachments/assets/0d6fece2-3af9-4da2-b3e7-9e44a9401111)
![Image](https://github.com/user-attachments/assets/01bec4ba-c0cc-4f9c-a0ed-ba98da81ad40)
![Image](https://github.com/user-attachments/assets/1a3d1f65-df23-49fe-862d-4709cb62a31e)

Change your password:

![Image](https://github.com/user-attachments/assets/920b1dda-1225-4f64-a764-3aba2f8d30cf)
![Image](https://github.com/user-attachments/assets/4cd04ac8-5c78-4600-8276-b41448fc3d0e)
![Image](https://github.com/user-attachments/assets/6fb15bcb-4ce2-428b-b871-48989468b773)
![Image](https://github.com/user-attachments/assets/a88a70d0-def0-49d7-a34e-7f0860ac1c1c)
![Image](https://github.com/user-attachments/assets/c5a6f8d8-3a52-4572-a2ef-ec5409e9d940)
![Image](https://github.com/user-attachments/assets/37a3619f-7de9-4637-a815-221059ace0dc)
![Image](https://github.com/user-attachments/assets/564c29ee-8dfb-4f11-ab90-49fdbb15e6e4)

..........................................................................................

_5. Update of wording needed:_

![Image](https://github.com/user-attachments/assets/922ef52d-0ecf-4a49-9452-94c2a4e84a09)

![Image](https://github.com/user-attachments/assets/3471d9fb-3961-47d0-8c6f-df9cba8a9450)

![Image](https://github.com/user-attachments/assets/5c0a40da-a714-43c3-b848-1bd77a69f438)

![Image](https://github.com/user-attachments/assets/aeb6121c-02ff-4c3f-aa93-c39a67904764)

**FIGMA REFERENCE:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33455-217248&t=yNhx5Cr7FQ1SiG9h-0

**Comment by smaroudasunicorn** [comment]
In the seed phrase screen we need to write that seed phrase is store encrypted.

**Comment by smaroudasunicorn** [comment]
We set the password only for web and extension, it will be mandatory option. 

We keep lock timer but we cannot disable Secure Login.

**Comment by smaroudasunicorn** [comment]
For users upgrading the app they have to be prompted to set a password.

**Comment by onvisions** [comment]
@peronczyk @smaroudasunicorn 
As discussed adding manual "Lock wallet" feature allowing the user to lock the wallet immediately from the "More" screen.

**Design:**

![Image](https://github.com/user-attachments/assets/a357d635-75d5-4df6-9631-40d088dd184e)

**Comment by smaroudasunicorn** [comment]
I am ok with the proposal

**Comment by Liubov-crypto** [comment]
1. Terms page is empty: 

![terms](https://github.com/user-attachments/assets/5b8c2508-3da8-4dbd-9ac5-7f69a396f517)

2. Haven't we added Pair Airgap on the login page? 

![f](https://github.com/user-attachments/assets/bd08ace4-f844-42f9-be6a-0a74f37cc1c1)

3. A little bit smaller pic inside an icon compared to design: 

![ic](https://github.com/user-attachments/assets/07ba520d-e1cd-409c-86ae-d11c40f5d81b)

4. Probably not our issue but I'm wondering, why there are white fields after I saved my password in Chrome? 

![white fields](https://github.com/user-attachments/assets/d2a2c67e-3f19-476b-9812-e1673063b5e8)
![pas](https://github.com/user-attachments/assets/e841b4d1-1307-401c-b729-abe9f80c80d9)

5. Caps lock feature is missing: 

![CAPS](https://github.com/user-attachments/assets/9d09dcb8-b38e-4395-9bfe-1144082b48e8)

6. According to Figma password must be at least 8 characters long, but we have 4. Is it correct? 

![4](https://github.com/user-attachments/assets/4df2d89b-3401-4bd2-904a-fbed6be8dab1)

7. After I changed my old password to the new one the header is missing and it seems that both passwords are not working when I'm trying to enter the wallet: 

https://github.com/user-attachments/assets/8e4e18b3-e81c-44dc-a388-987167409591

![inc pass](https://github.com/user-attachments/assets/71c101b2-b7d5-4d42-8839-467670600709)

**Comment by Liubov-crypto** [comment]
8. The icon is different compared to Figma design: 

![lock](https://github.com/user-attachments/assets/29eb8d25-d62e-4e65-bfc5-0fe7f9853ecd)

**Comment by CedrikNikita** [comment]
> 6. According to Figma password must be at least 8 characters long, but we have 4. Is it correct?

4 characters is correct.

**Comment by peronczyk** [comment]
> 1. Terms page is empty

Fixed

> 3. A little bit smaller pic inside an icon compared to design: (ICON)

We have a common icon used everywhere in the app and it was aligned with Tsvetan's design some time ago. @onvisions do you think we need to update it again? If yes I suggest to create separate task for this as the icon was not changed within this PR.

> 4. Probably not our issue but I'm wondering, why there are white fields after I saved my password in Chrome?

That's a chrome's thing and unfortunately not much can be done here :/ I added one tweak to this form to prevent the white background to happen, but besides this we don;t have any control on this.

> 7. After I changed my old password to the new one the header is missing and it seems that both passwords are not working when I'm trying to enter the wallet:

Fixed by @CedrikNikita

**Comment by Liubov-crypto** [comment]
1. For web, screen lock does not work by timer, only forced: 

https://github.com/user-attachments/assets/dada5adb-ad4e-40d4-ba4e-e777bf7fe48a

2. Saved Password Background remains white, and I suggest leave it as it is for now: 
![white](https://github.com/user-attachments/assets/3980ce24-bba1-478a-b608-9588ebc43a3e)

The rest is LGTM, considering your comments above

**Comment by Liubov-crypto** [comment]
secure storage on iOS app is working fine for me.
