### ISSUE TITLE
User is not able to move the account details buttons left/right on the desktop.

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3199]
**Describe the bug**
User is not able to move the account details buttons left/right on the desktop.

**To Reproduce**
1. Go to Account details page
2. Try to swipe buttons
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome,
 - Version 126

**Additional context**

![Image](https://github.com/user-attachments/assets/28d2e141-ed6a-49f3-979d-959511e4023e)

**Comment by Liubov-crypto** [comment]
I'm still seeing only 3 buttons on mainnet: 


![Image](https://github.com/user-attachments/assets/50ecb912-8285-41e6-a1a7-0841b6795253)

and 4 buttons on testnet:



![Image](https://github.com/user-attachments/assets/8133c1a5-ce31-4d14-b70d-714ca9b38b4f)

**Comment by smaroudasunicorn** [comment]
It requires drag and scroll gesture.

**Comment by Liubov-crypto** [comment]
> It requires drag and scroll gesture.

@smaroudasunicorn  correct, I've tried, but it's not working. This issue is not reproducible for me. @peronczyk  asked me to open this. Initial attached screen looks like mobile version for me. 

There is no more buttons that I see on the screen using web wallet:  3 buttons on mainnet and 4 buttons on testnet. As far as I remember the Buy button was hidden long time ago... @onvisions correct me if I'm wrong.

https://github.com/user-attachments/assets/d65ed873-dcc5-4df1-b6cb-268f30e93f45

I can see 5 buttons only on ios/android app on testnet and there is no hint that they should be scrollable and 5th button is hidden from the user, probably this should be improved somehow: 
https://github.com/user-attachments/assets/b094d422-fab5-4f72-bc4c-1fdc9ac39bbc

**Comment by Liubov-crypto** [comment]
LGTM, tested on test version.
