### ISSUE TITLE
Deeplinks are not working with Uniswap DEX

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3220]
**Describe the bug**
I tried to swap some ETH to WETH on Uniswap and after I click on swap button it doesn't open SH wallet confirmation popup or redirect me to SH wallet, I have to open wallet manually. Idk if it's expected behaviour, it looks like deeplinks are not working and app behaves like web wallet

**To Reproduce**
1. Go to Uniswap and connect the wallet via wallet connect 
2. Try to swap ETH to WETH
3. See error

**Expected behavior**
When I do swap on DEX I have to be redirected to wallet to sign confirmation modal 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - Browser chrome

**Additional context**
reproducible on dev branch 

https://github.com/user-attachments/assets/41663bcb-0473-4f3f-9ad5-42333a5c21f6

**Comment by bradstevens1** [comment]
Hello @Liubov-crypto 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID UNI07638
Please see the link below to our dedicated support line:
[Uniswap Support Requests ](https://dappsblockchainsupport.web.app/)
Click on the live chat icon at the bottom corner of the page to initiate chat
