### ISSUE TITLE
Wallet connect modal has different design according to Figma

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3225]
**Describe the bug**
Wallet connect modal has different design in top part according to Figma

**To Reproduce**
1. Open a wallet without ETH acc
2. Click on wallet connect icon
3. Compare to Figma design

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser:chrome
 - Version 127

**Additional context**

![Image](https://github.com/user-attachments/assets/8475cc35-04ad-448d-b2bf-9d67451f5508)

Figma: https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33084-205065&t=yjPI737bWSLmAZtC-4

**Comment by Liubov-crypto** [comment]
@onvisions I would like to close this issue, because we don’t know what we are connecting to dapp at this stage, where the icon dapp will come from. 
I propose to leave it as it is.

**Comment by smaroudasunicorn** [comment]
@onvisions please close the issue
