### ISSUE TITLE
Fix the Firefox extension popup content not visible

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3238]
With the introduction of the possibility of opening the extension as the Side Panel the Firefox from version 129.0.1 stopped to display the extension - the window pops up but it's empty or only the header is visible at the middle of the popup.

![Image](https://github.com/user-attachments/assets/543a110d-38a4-4b48-b1c6-a07bf653ce18)

**Comment by Liubov-crypto** [comment]
LGTM
