### ISSUE TITLE
Simple Transaction - Shorten User Confirmation

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3254]
Every action from the wallet could be auto signed by user shortening the user journey. 

We should have the option for the user to sign automatically transactions/messages originated from the wallet

**Comment by onvisions** [comment]
@CedrikNikita @smaroudasunicorn 

**We currently have the option to set permissions in the wallet: Dashboard/More/Wallet settings/**

![Image](https://github.com/user-attachments/assets/dddeaf01-c4db-45a9-902c-76199c4fe549)

Wording needs to be updated. Suggestion: _"Manage confirmation popups and daily spending limits. For security reasons use this feature with caution only for trusted platforms such as [superhero.com](https://superhero.com/) and your localhost environment."_ ----> 

Manage transaction confirmations, signing messages and daily spending limits. For security reasons use this feature with caution only for trusted platforms and dapps and your localhost environment.

**DESIGN:**

1. **Allow Access** (Initial) - first time user allows access to an app they can set auto confirm actions. Later these can be edited and managed in the wallet settings.

![Image](https://github.com/user-attachments/assets/6122223c-9639-4a2b-ab34-6140295d67f3)

2. **Sign Message**

![Image](https://github.com/user-attachments/assets/d8ea904f-4ab4-4e69-b6de-af021ae8ff76)

3. **Sign Raw Data** 

![Image](https://github.com/user-attachments/assets/0a1e9302-2b3e-406d-b2db-3ac9c399747a)

4. **Confirm transaction (from any source)** 

![Image](https://github.com/user-attachments/assets/0ecdb8cb-a6df-4a06-ad3e-ae93cafd0f42)

5. **Confirm transaction (with trusted origin)**

![Image](https://github.com/user-attachments/assets/46ca667f-bf91-452c-9897-29b7508424cd)

6. **Confirm any transactions / sign any messages originating from Superhero Wallet** (not sure about actual use case of such a transaction/message)

Add same functionality to the modals but update the wording accordingly (with no warnings):

_"You can choose to auto confirm transactions originating from Superhero Wallet. You can edit granted permissions at any later moment in your wallet settings."_

_"You can choose to auto sign messages originating from Superhero Wallet. You can edit granted permissions at any later moment in your wallet settings."_


**FIGMA REFERENCE:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=34503-248639&node-type=frame&t=Ci7dWQbVH2IkkvxC-0

**Comment by smaroudasunicorn** [comment]
Maybe we could have an action in the previous screen like Send & Confirm and do the auto sign at will. This would not make it simpler in terms of implementation? I feel that this permission system might prove too "expensive" and complicated for the users.

**Comment by smaroudasunicorn** [comment]
Skip the sign messages for transactions originated within the wallet
