### ISSUE TITLE
Buying AE with ETH

### ISSUE THREAD

**Issue by nikita-fuchs** [superhero-com/superhero-wallet#3265]
Hey @smaroudas, it was requested by the toplevel management to be able to buy AE with ETH easily 
from the wallet, and later from a dApp which can be used with Ethereum wallets like MetaMask. The first case has priority now, the second case just keep in mind for later, it will be easy to implement for another team even.

It was requested to use gate.io and it will be necessary in order to swap the two native crypto currencies. Although I am not opinionated about the implementation, here is one proposal that would make sense:

0.  Use the [flash swap](https://www.gate.io/docs/developers/apiv4/#create-a-flash-swap-order) of gate.io to quickly swap ETH to AE.
1.  Use the [preview](https://www.gate.io/docs/developers/apiv4/#initiate-a-flash-swap-order-preview) to display to the user how much AE he will approximately get for an entered amount of ETH.
2. Have a small backend that tracks all sender's addresses and ETH amount deposits to your gate.io trading account, so they can be swapped for AE. The user would also call the backend with an AE address, signed with the ETH wallet used for the deposit, to prove that the provided AE recipient address is legit. 
3. As soon as the deposit transfer is done, the backend initiates a swap and withdraws the resulting amount to the provided AE address.

To rephrase it in simple terms:

0. User enters 1 ETH, sees he gets XXX amount of AE.
1. The user transfers that ETH to the superhero's gate.io deposit wallet.
2. The user sends a REST API call to the backend with the signed AE address where he wants to receive his swapped AE. The signing is done with the ETH account that was used in 2.
3. The backend waits for the ETH to arrive in their wallet, 
3.1 checks the signature for the provided AE address to ensure it is the legitimate recipient
3.2 calls the swap API on gate io
3.3 transfers the result of the swap to the provided AE address

**Comment by CedrikNikita** [comment]
I think the idea of centralized swap between ETH and AE is against the vision of the whole project. Our goal was for anyone to deploy their own Superhero Wallet and not to depend on centralized services. Also the user will be asked to transfer his money to _ETH Superhero Wallet account_ and in exchange we will **promise** that he will get AE, for the user it may look like a potential scam. But the whole proposed feature is promising. I think from Superhero Wallet team side, we should investigate potential way of making it work in a less centralized way.

**Comment by smaroudasunicorn** [comment]
@nikita-fuchs https://aeternity-blockchain.atlassian.net/wiki/spaces/AID/pages/643203073/ETH+to+AE+Coins+Exchange+-+SH+Wallet+Integration+Approach page created. Kindly your input

**Comment by smaroudasunicorn** [comment]
@nikita-fuchs can we close this, or is there something that has to be done from our side?

**Comment by nikita-fuchs** [comment]
Hey, yes, this is paused for now. We could have to unbury this one day though, just put it somewhere in the back for now.
