### ISSUE TITLE
Explore logout capability

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3267]
**Story:** Apart from existing auto-lock timer the user would like to be able to lock wallet "manually" at any moment. 

**Acceptance criteria:** 

- Add "Lock wallet" button on the "More" screen allowing the user to lock the wallet immediately.
- Add background and proper animation to the locked screen where Enter password modal is displayed.

**Design:**

![Image](https://github.com/user-attachments/assets/8a68b2f8-0fe8-4961-b6fe-d42a5305587c)

![Image](https://github.com/user-attachments/assets/3671a7f3-26da-4834-8383-b70715d41327)

![Image](https://github.com/user-attachments/assets/2019564f-5987-4e38-849a-8450003049d9)

![Image](https://github.com/user-attachments/assets/9a0d2222-5dd8-4d27-ac54-6d1cc9852345)

![Image](https://github.com/user-attachments/assets/cdd29dc9-9b89-4468-908b-710acc4665d5)

**Figma reference:**

**1. Lock wallet button:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33640-210784&node-type=frame&t=9seIxZoOgv2mi7mz-0

**2. Wallet locked screen:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33640-210784&node-type=frame&t=UNcaZ9aV8hZClTbt-0

**3. Wallet locked screen diamond vector:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=34559-245117&node-type=frame&t=UNcaZ9aV8hZClTbt-0

**Comment by peronczyk** [comment]
This is resolved within separate PR already merged to the password protection PR.
