### ISSUE TITLE
QR code is broken in Address book

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3274]
**Describe the bug**
QR code is broken in Address book

**To Reproduce**
1. Go to Address book
2. Add an address
3. Save it

**Expected behavior**
Should not be broken

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version 130.0.1

**Additional context**
reproducible on dev branch in FF browser extension

![Image](https://github.com/user-attachments/assets/c8a5da55-85e6-4ce0-a0ea-4896237e570d)

**Comment by Kami-prog** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)
