### ISSUE TITLE
If Enable secure login is off, Lock Wallet btn is enabled

### ISSUE THREAD

**Issue by dvdbak** [superhero-com/superhero-wallet#3304]
**Describe the bug**
When the user does not enable the secure login feature on mobile, the Lock Wallet button is clickable but nothing happens

**To Reproduce**
Got to Settings
Secure login
turn off Secure login
Check the Lock Wallet btn

**Expected behavior**
Don't know

**Screenshots**

**Smartphone (please complete the following information):**
Android device

**Additional context**

**Comment by peronczyk** [comment]
As agreed in our chat we have 3 cases:

1. User has no access to biometric login on his device
2. User didn't set up biometric login
3. User (only developers) clicked "Skip" on the password set modal

For 1 and 2 the "Lock Wallet" button will be hidden.
For 3 the button will be visible but disabled.

@onvisions @smaroudas 

The task is ready to be tested @Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM

**Comment by dvdbak** [comment]
lgtm

**Comment by dvdbak** [comment]
close as fixed
