### ISSUE TITLE
Wallet Initialization - select blockchain account (remove aeternity default)

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3317]
**Story:** Following the new priority order of Bitcoin, Ethereum, æternity blockchains and the multi-blockchain approach, the default æternity account when creating a new wallet should be removed. Instead a new step is introduced into Create wallet flow - selection of blockchain to create user's first wallet account on.

**Acceptance criteria:** 
Initial screen/Create new wallet/Create wallet modal where the user is presented options with supported blockchains (currently Bitcoin, Ethereum, æternity) to select from in order to create the first account in the new wallet. 
Next step is **Set password** (optional, _seed phrase encryption with password will be optional, separate task to be created for this issue_).

**Design:**

![Image](https://github.com/user-attachments/assets/cdda6fa6-fbe6-42eb-bf87-0abec1028d4a)

![Image](https://github.com/user-attachments/assets/6cd1bd75-00c6-457e-9f84-d32cb1c3a910)

![Image](https://github.com/user-attachments/assets/62e0622e-a5cc-48da-8aee-255c21aa32c0)

![Image](https://github.com/user-attachments/assets/f3fa54ad-5f49-4d25-8ca6-2f072a27b0c7)

![Image](https://github.com/user-attachments/assets/f48a24dc-bfb0-4df2-abd3-4401faff2e92)

**Prototype REC:**

https://github.com/user-attachments/assets/0dd58728-146b-4fa9-be83-bff18a8b240c

**Figma reference:**
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33514-212196&node-type=frame&t=e7x73MSXRWA7VcpO-0

**Comment by smaroudasunicorn** [comment]
I am ok

**Comment by Liubov-crypto** [comment]
I've got the same issue as @CedrikNikita , when I'm creating a new wallet and choose BTC/ETH as 1st account, then logged out and login with seed phrase, my BTC/ETH account will be not available. I will see AE account by default and have to add BTC/ETH acc manually. 
@peronczyk  please check it. 

https://github.com/user-attachments/assets/a0d6ec20-bbff-414d-8943-6141ce7ba166

**Comment by peronczyk** [comment]
@onvisions & @smaroudasunicorn what should happen in the case described by Liubov? Restoring the accounts from the mnemonic is a process where the logic goes through the protocols and checks if there are any accounts that has any balance or transaction history. So if you take a mnemonic where there is no accounts with balance/history we are adding the AE account by default to have at least one account.
Should I change this behavior?

**Comment by peronczyk** [comment]
> @onvisions & @smaroudasunicorn what should happen in the case described by Liubov? Restoring the accounts from the mnemonic is a process where the logic goes through the protocols and checks if there are any accounts that has any balance or transaction history. So if you take a mnemonic where there is no accounts with balance/history we are adding the AE account by default to have at least one account. Should I change this behavior?

Decision made on the Daily Scrum meeting: user should be asked about account (potocol) he wants to use if no accounts was discovered on provided mnemonic.

**Comment by peronczyk** [comment]
@Liubov-crypto I updated my PR according to above agreements. Please retest.

**Comment by Liubov-crypto** [comment]
LGTM
