### ISSUE TITLE
It's not possible to scan QR code from AirGap vault when creating a multisig account

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3327]
**Describe the bug**
It's not possible to scan QR code from AirGap vault when creating a multisig account, scanner will stuck

**To Reproduce**
1. Import airgap account 
2. Click on create multisig vault
3. Choose airgap acc as 1st signer
4. choose 2nd signer regular ae acc
5. Scan qr from wallet and sign tx in vault
6. click on next
7. Scan qr from airgap vault using wallet scanner 
8. Scan progress will stuck 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, 
 - Version 129

Extension, web wallet. 

![br](https://github.com/user-attachments/assets/bf0a6e33-a7e1-48cb-b80c-55ebc2b728cd)
![Image](https://github.com/user-attachments/assets/537b2e15-5174-40cf-a19b-b5bb90e1babc)
![Image](https://github.com/user-attachments/assets/3887ad3d-c6d5-4bff-9e9e-568f56053a40)
![Image](https://github.com/user-attachments/assets/c77af0b9-7cf8-4836-bb29-7b60e1501e7f)

**Comment by dvdbak** [comment]
Does also apply for normal AirGap account. The scanner is loading ...
