### ISSUE TITLE
accounts from the dropdown list have different widths

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3339]
**Describe the bug**
Accounts from the dropdown list have different widths. if the imported account has a long name, then the width of the card in the drop-down list will be different

![Image](https://github.com/user-attachments/assets/f35e189f-1639-4b94-9416-39959e1af255)

**Comment by onvisions** [comment]
@smaroudasunicorn 
**Suggestion how to solve quickly:** Let's use for all account names the horizontal animation shortening if the name is longer than space available. Logic is already existing and used in several UI spots across Superhero Wallet.

**Comment by smaroudasunicorn** [comment]
I agree

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
