### ISSUE TITLE
Transaction Information - Set dollar sign to USD

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3342]
We would like to improve the display of tx fee in dollars.

i.e. 

Transaction fee
0.00001672 AE
<$0.01

should rather be " < 0.000001 USD" (we need to calculate)

Change $ sign to USD, since $ is the original Peso sign which can be misleading for many people.

**Comment by peronczyk** [comment]
The PR is ready to be tested. One important thing is the order of the amount and the currency. We are using automatic currency formatting based on users language. American/GB english assumes that the currency name goes before the amount. This is why we need to display all the amounts as `USD 123456`.

**Comment by Liubov-crypto** [comment]
LGTM
