### ISSUE TITLE
Wallet Initialisation or Security Settings - Disable Set wallet Password

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#3347]
**Story:** User shall have the ability to skip set wallet password if he desires to undertake security risks.

**Acceptance Criteria:**
 
- First time set password modal: update wording, add Skip password option. 2 Options: "Set password" and "Skip password";
 
- Initialization of wallet: add Skip password option. 2 Options: "Set password" and "Skip password";
 
- Update wording in the Set Password modal: see design below and comparison side by side of the old text and new updated wording suggestion.
 
- Add option to switch on/off the Secure login in More/Settings/Secure login;
 
- When Secure login is off the "Auto-lock wallet" and "Change password" blocks are disabled. The "Lock wallet" button on "More" screen is also disabled.

**DESIGN:**

**Initialization of wallet (Skip password)**
![Image](https://github.com/user-attachments/assets/a81209cf-8fbe-461b-8f32-71aa925be563)

![Image](https://github.com/user-attachments/assets/e0d2d287-8409-4692-8e53-7fbfce679336)

**REC:** https://github.com/user-attachments/assets/9508af2b-28d8-4bf2-a9ff-0a8aaa1dd8b5

**First time set password modal**

![Image](https://github.com/user-attachments/assets/917f0cf6-ab7e-4f8e-b474-bf20f7627548)

**More/Settings/Secure login:**

![Image](https://github.com/user-attachments/assets/847c643b-2a78-427f-9ff5-ba591e439878)

![Image](https://github.com/user-attachments/assets/d70506f5-9506-4e17-afe2-e6a6ed5343cc)

**More (disabled state of Lock wallet button):**

![Image](https://github.com/user-attachments/assets/e1d0ffc1-324f-49ba-8446-e5849c9701a7)

**Figma Reference:**https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33455-217248&node-type=frame&t=eELbU3K8u3GlJ8SW-0

**Comment by smaroudasunicorn** [comment]
I am ok

**Comment by Liubov-crypto** [comment]
During the testing I found some issues: 

1. It's not possible to skip set password on the first step, when creating/restoring a wallet. There is no skip password button. Also text is not updated according to Figma ref: 

![Image](https://github.com/user-attachments/assets/dac2ea52-e3b0-4c3d-980b-03b60bcf568b)

2. Set a password, I see some old text when click on "?"

![Image](https://github.com/user-attachments/assets/58f96cfe-68c5-4ce9-8681-b07516d1316e)
 
3. Settings --> Secure login - some text discrepancies: 

![Image](https://github.com/user-attachments/assets/ba519b52-0ae7-4570-a030-27fef23cb250)

4. After I disabled a secure login, closed a wallet and back again, I was blocked by Enter password page. I entered my password, but system doesn't recognise it, however the password is correct: 

https://github.com/user-attachments/assets/f2a4ea28-c71b-4c44-92aa-62212371239a

@peronczyk  please check it

**Comment by peronczyk** [comment]
I have updated my PR with the fixes.

Ad 3. We agreed with @onvisions that we will have one common wording for this feature: "You will be asked to authenticate in order to unlock the wallet and continue using it."

Can you retest @Liubov-crypto

**Comment by Liubov-crypto** [comment]
I found one difference on this screen: 
![зф](https://github.com/user-attachments/assets/d2f72ea2-52c4-4a63-93c7-0cca8f574ea8)

but there is similar screen when I want to login wallet without such text, so I'm not sure, should that text be present or not? 
@onvisions could you please help me here? 

the rest is fixed, LGTM

**Comment by onvisions** [comment]
@Liubov-crypto

1. both variants are used. The first one is displayed when the user has the wallet installed and it has been updated to latest version that gives the option for setting password.
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=37194-305712&node-type=frame&t=sV4EHRVeZV3bAYCg-0

The second is when you are creating a new wallet or restoring one with seed phrase.
https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=33514-212273&node-type=frame&t=sV4EHRVeZV3bAYCg-0

2. Both variants should not have closing button for the modal:
![image](https://github.com/user-attachments/assets/acd4db19-d30c-49be-bc95-62cd9db8946a)

**Comment by peronczyk** [comment]
@onvisions OK I removed the close buttons.
@Liubov-crypto is everything OK right now?
