### ISSUE TITLE
Address Book list should use PanelItem component instead of having duplicated styles

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3355]
Right now Address Book list has its own separate component to display each item. But these items has no "active" (click) effect and actually duplicates some common styles we have established in other components.
![Image](https://github.com/user-attachments/assets/aa3506eb-aecd-4f35-aa09-a46fd1b02e02)

My suggestion is to reuse `PanelItem` component (the one used in "More" page) to display Address Book list items.
![Image](https://github.com/user-attachments/assets/4d5120d5-1e9e-41d6-a017-fe00fa6a9f07)

@onvisions do you agree with this?

**Comment by onvisions** [comment]
If you mean to reuse the "on click" animated effect, yes sure!

**Comment by Liubov-crypto** [comment]
I see that spaces are bigger between Address Book list items than on prod. Is it correct? 
https://github.com/user-attachments/assets/f0fa63a5-42be-46eb-bd8d-3514bfa41c28

**Comment by onvisions** [comment]
The update implementation (tested at the link provided:https://refactor-address-book-items-use-panel-items.wallet.z52da5wt.xyz/) is approved on my side.

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
