### ISSUE TITLE
When user logout the wallet using the option 'forgot password" the last screen will be shown on the final step

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3360]
**Describe the bug**
When user logout the wallet using the option 'forgot password" the last screen will be shown on the final step

**To Reproduce**
1. Go to Security Settings and set timer 
2. Open Privacy Key page
3. Wait until wallet will be blocked 
4. Click on forgot password
5. See that last active screen will be shown after Reset screen

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 130

**Additional context**
reproducible on dev branch 

https://github.com/user-attachments/assets/17a397a5-39af-4d14-a25e-8f7859cd1f2a

**Comment by onvisions** [comment]
@smaroudasunicorn 
**1.** it's a clear bug to display the private key after resetting the wallet. And I don't even get how is this possible if the wallet is really reset.

**2.** It might be better to hide the "Forgot password link" when the user is required to enter password before exporting the Private Key. 
In this case the user is within the flow of exporting the Private key so it doesn't make sense to give the option to reset the wallet and end on the initial screen.

**Comment by Liubov-crypto** [comment]
fixed, LGTM
