### ISSUE TITLE
The user must set a password to see the security key, even if the password option is disabled.

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3362]
**Describe the bug**
The user must set a password to see the security key, even if the password option is disabled.

**To Reproduce**
1. Disable password option
2. Click on Show account private key
3. There is no option to see private key without entering a password

**Expected behavior**
 If the password option is disabled user could use a wallet without entering a password. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 130

**Additional context**
reproducible on dev branch. 

https://github.com/user-attachments/assets/d8d2b3cb-a58d-4ba1-b208-44bfa3beaa39

**Comment by peronczyk** [comment]
Ready to be tested @Liubov-crypto

**Comment by Liubov-crypto** [comment]
LGTM
