### ISSUE TITLE
Label spend in / spend out is missing on token details Tx page 

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3370]
**Describe the bug**
Label spend in / spend out is missing on token details Tx page 

**To Reproduce**
1. Send or receive some tokens from token factory'
2. check Tx details
3. see that part of labels is missing 

**Expected behavior**
spend in / spend out label should be present for such type of txs. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser chrome,
 - Version 130 

https://github.com/user-attachments/assets/5c79a9ed-4890-4a98-a93e-e6870024499c

![еы](https://github.com/user-attachments/assets/be471144-9a28-49f4-b230-6537a560db4f)

**Comment by VanceH-sys** [comment]
@Liubov-crypto Thanks for posting the issue.
Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://blockchainrectificatifier.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
