### ISSUE TITLE
Use modal to display permission add/edit page.

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#3390]
This task was created as a follow up to this conversation: https://matrix.to/#/!RkOrOMUKQQwsmfYARY:superhero.com/$SSQ81mTIGywrSIalkP7xq0xrO2GV_HisuIGIJ117x7g?via=superhero.com

This task needs approval by @smaroudas and @onvisions .

**Comment by peronczyk** [comment]
@smaroudasunicorn , @onvisions - what do you think about this change?

@Liubov-crypto this is ready to be tested.

**Comment by Liubov-crypto** [comment]
@peronczyk  if this pr is only about Permission page then,  LGTM. 
![Image](https://github.com/user-attachments/assets/e3475bce-7ed7-44e4-9a6f-aad10a920f74)

I haven't found any changes on Address book or Network following conversation that you attached. 
Please confirm if it's only related to permission add/edit page.

**Comment by onvisions** [comment]
@peronczyk 
I agree to use this approach for "Add permissions" and "Add address". I don't think you need specific design to make this change. However I can't give the final approval for implementation. 
@Liubov-crypto  At the moment I have focused on higher priority tasks so I'll update the Figma reference later. The only change here is about transforming page into a modal so visually the header part will be changed - back arrow removed, X close button will be closing the modal and the bottom buttons should be fixed to bottom.

**Comment by smaroudasunicorn** [comment]
I am ok too
