### ISSUE TITLE
There are no Txs for ETH account

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3403]
**Describe the bug**
Currently there are no Txs for ETH account 

**To Reproduce**
1. Go to ETH account 
2. Click on Tx list 
3. See that there are no Txs in Tx list 

**Expected behavior**
Txs list should be displayed. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser:  chrome
 - Version: 130.0.6723.119

**Additional context**
reproducible on prod branch. 

https://github.com/user-attachments/assets/db6170c0-7150-408a-8350-90a596bde73a

**Comment by CedrikNikita** [comment]
fixed by #3409
