### ISSUE TITLE
ETH Tx is in pending status a few minutes, however it's completed

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3405]
**Describe the bug**
ETH Tx is in pending status a few minutes, however it's completed long time ago. 

**To Reproduce**
1. Go to ETH 
2. Send some ETH
3. Check tx is in pending status 
4. Check Tx on Eth explorer 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome 
 - Version 130

**Additional context**
reproducible on dev branch 

https://sepolia.etherscan.io/tx/0x8c1ce9c2a69a40969fd15908a20ce196e3cfc9d8c40a562803a3320b0c4b8dba

![Image](https://github.com/user-attachments/assets/28808958-c3f9-4fe0-b25c-01250e02c3f7)

**Comment by CedrikNikita** [comment]
fixed by #3409
