### ISSUE TITLE
the locked wallet extension doesn't popup in chrome when trying to connect

### ISSUE THREAD

**Issue by thepiwo** [superhero-com/superhero-wallet#3414]
**Describe the bug**
The locked wallet extension doesn't popup in chrome when trying to connect, when having it unlocked it works as expected

**To Reproduce**
1. Ensure your wallet extension is locked, e.g. restart your browser before 
2. Open an aepp in chrome, e.g. https://contracts.aepps.com/, then click "Connect Wallet Extension"
3. Doesn't work
4. Open the wallet extension and unlock it, the connection popup works

**Expected behavior**
Trying to connect an aepp to the extension should open the popup, unlock, then connection confirmation

**Screenshots**
Sorry for the bad quality: https://github.com/user-attachments/assets/07a7605a-b1e5-4b95-aca1-b75ebf586d15

**Desktop (please complete the following information):**
 - OS: Linux with Wayland
 - Browser: Chrome
 - Version wallet v.2.3.1

**Comment by Liubov-crypto** [comment]
Reproducible for me too. 

OS: MacOS
Browser: Chrome
Version wallet v.2.3.1
