### ISSUE TITLE
Confirmation modal: dApp requesting permission to switch network

### ISSUE THREAD

**Issue by onvisions** [superhero-com/superhero-wallet#3429]
**Story:** design is needed for a confirmation modal in case dApp is requesting permission to switch the active network. Requested by @CedrikNikita 

**UX Suggestion:** @smaroudasunicorn @CedrikNikita  based on some research how other wallets are dealing with same scenario I am suggesting to grant the dApp permission to switch the network just once within the initial Connect to dApp modal instead of asking the user each time.

**Design:**

![Image](https://github.com/user-attachments/assets/07dcb3fe-24ff-4bac-93e6-ed1257240eb4)

**Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=38011-279097&node-type=instance&t=H26uNHOEsBqsmksW-0

**Comment by onvisions** [comment]
**Story:** the user has no account created on the blockchain the dApp is operating on. They need to see a message warning them they cannot use the dApp without such an account. The message is similar to what we show on the Wallet Connect modal when user has no Ethereum account.

**Design:**

**Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=38051-290048&node-type=frame&t=EhlxZVKaSHRf2pmR-0

**Comment by Liubov-crypto** [comment]
A little bit different design compared to Figma, it doesn't show a current account: 

![dap](https://github.com/user-attachments/assets/8af0d727-448d-42f1-81fe-4665a0e23d67)

![aa](https://github.com/user-attachments/assets/9ec1b504-0261-47f7-91cb-d8e60b68f21f)

**Comment by onvisions** [comment]
@Liubov-crypto @CedrikNikita @smaroudasunicorn 
Well, although my design suggestion was to show the current active account, I like this one too. 2 things to improve just visually:
- make the size of both greyed sections equal (dApp and Wallet with the loading animation);
- increase margin on top of the error message (like in design).

**Comment by Liubov-crypto** [comment]
@onvisions  Currently we are having this one: 

![Image](https://github.com/user-attachments/assets/91459a52-f3bb-4d7c-896e-6e1b1be8347e)

Probably design changes will be implemented later.

**Comment by onvisions** [comment]
@CedrikNikita @smaroudasunicorn 

Created a quick mockup for the skeleton UI implementation.

![Dapp Connection](https://github.com/user-attachments/assets/90fcbd65-3345-4c8a-9780-6a9c502e637e)

**Figma reference:** https://www.figma.com/design/3oGLWzSH0oJljo4RETZtur/Superhero-Wallet-UI-(%E2%9C%94%EF%B8%8FUpdated)?node-id=38050-279282&t=J4CK4zND00TQAiTZ-0
