### ISSUE TITLE
If user set daily spending limit without asking wallet will sign in Tx but will not redirect to the app 

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3430]
**Describe the bug**
I found that sometimes when I buy token or sell token on token org, confirmation popup (allow token) can be signed by wallet himself without my interaction  

**To Reproduce**
1. Go to token org
2. Try to buy or sell token 
3. Check Txs in wallet 

**Expected behavior**
User have to approve all Tx in wallet by himself 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  iPhone
 - ios
 - chrome, FF, safari

**Additional context**
Reproducible with current release branch app and token org.

**Comment by Liubov-crypto** [comment]
Retested with android app and chrome mob browser and it works as expected. 

Retested with iOS app and Safari browser. 
I set in permission settings daily limit without asking 1 ae, then I tried to sell 10 tokens that I bought before . First Tx (allow use of token ) was signed by wallet automatically. But I haven't received the second Tx in the wallet to sign it, to sell token actually.
[token.org](http://token.org/) is stuck and no sell Txs in the wallet

**Comment by Liubov-crypto** [comment]
Fixed, tested with Chrome extension. 

I have a question: it seems that incoming Txs are not displaying in our wallet Tx list and in this case Permission settings---> daily spending without limit will not calculate properly. 
For example I set 1 ae as spending limit without asking, then I sold a couple of tokens, but these Txs were not calculated in my total spending limit. Only buy Tx were calculated. Also I can't see the "proper income" Tx in my list that I have sold tokens, only approve allowance use of token. 

account: ak_cEjh5on5RvoBw8zqCGS4VWeY2bmNYNPjn3SCZutYyVLWKf7X1
Txs: https://testnet.aescan.io/transactions/th_BPnmsExHU4VwTSEXwBujUKGXxAuwy2ADn4iWtcPtvSzECLzRz
https://testnet.aescan.io/transactions/th_uXedCh13kXqqxDReWW14G7wzkTnAFPSFWSx1V4dynguVdneN8
https://testnet.aescan.io/transactions/th_2QQFgyzNNRE3DtMW4WQa5bEpRxbqfzaXeXHLLUzXGCVrPobiaC
https://testnet.aescan.io/transactions/th_mkCW37wfFsEXWDYNr2pe6KoAGwKZDQ6TPpzG3NwMgfzQSgBQV

and one more question: 

I sold 10 tokens but see them as 90 in the wallet Tx. Why is there such big difference? 

![10](https://github.com/user-attachments/assets/1a5ad015-73a2-45ea-a0f2-a128e75297ff)
https://testnet.aescan.io/transactions/th_mkCW37wfFsEXWDYNr2pe6KoAGwKZDQ6TPpzG3NwMgfzQSgBQV

Should I create bug tickets for these cases?

**Comment by CedrikNikita** [comment]
> and one more question:
> I sold 10 tokens but see them as 90 in the wallet Tx. Why is there such big difference?

It is not sending/selling it is `change_allowance` transaction, it means that allowance for this token has been changed. Dapp you were using have asked you to change the allowance for the token you are about to sell. And this is not a problem from both sides.
