### ISSUE TITLE
handle calldata not compiled by the wallet differently

### ISSUE THREAD

**Issue by nikita-fuchs** [superhero-com/superhero-wallet#367]
There is currently a way for setting the compiler URL for the wallet through the aepp, which we shoudl disallow and move to a setting in the wallet for security reasons. Also, when calling a contract, we can only guarantee the safety of the call data to the user if the Wallet generated it. as far as I see right now, you can feed the wallet arbitrary data to sign and send through the low-level, non-AEX6 api?  We should consider all calls than the one done the AEX6 way as unsafe, because the aepp could inject malicious call data here and the user wouldn't know. Only if the wallet compiles it and does the call (while during this ideally being out of scope of the aepp ! but I have no clue about browser addons), a contract call can be considered to be of integrity.

**Comment by CedrikNikita** [comment]
fixed in https://github.com/superhero-com/superhero-wallet/pull/2338

**Comment by nikita-fuchs** [comment]
hey @CedrikNikita , awesome, could you elaborate real quick how the fix solves this problem?

**Comment by CedrikNikita** [comment]
We are no longer depending on online compiler. And we are not compiling `calldata` on our side.
