### ISSUE TITLE
Don't expose selectedNode

### ISSUE THREAD

**Issue by nikita-fuchs** [superhero-com/superhero-wallet#371]
For privacy reasons, please do not expose the `selectedNode` attribute anymore, as this information could be misused by websites. It isn't / should not be necessary for the daepp to run :)

**Comment by mradkov** [comment]
related to #366?

**Comment by nikita-fuchs** [comment]
Well kind of, this one is a `getter`, the other one a `setter` so to say

**Comment by mradkov** [comment]
Expose network id.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
