### ISSUE TITLE
Sign-message method to return the address in param

### ISSUE THREAD

**Issue by shapkarin** [superhero-com/superhero-wallet#379]
Hello. It will be nice if `sign-message` method can forward with address too, in this case I don't need to back to jitsi and save address to local storage. Also for sign method already knows about address, so maybe it can back it with params. I use localStorage now, but in future it may be better use deeplinks in that way:

https://github.com/aeternity/jitsi-meet/blob/6dd366198dae07ee2ca912501addd51393e23880/react/features/conference/components/web/WebLoginButton.js#L5-L20

**Comment by shapkarin** [comment]
In example above there is issue => 'x-success': `${signLink}?address={address}`
But anyway it not resolve that problem. And it will be nice to get `address` from the `sign-message`

**Comment by CedrikNikita** [comment]
fixed by https://github.com/superhero-com/superhero-wallet/pull/2953
