### ISSUE TITLE
Don't copy English wording to other locale files

### ISSUE THREAD

**Issue by davidyuk** [superhero-com/superhero-wallet#452]
I'm considering this a bad practice because that wording may become outdated and a translator will waste his time working with that.

So, I'm proposing to remove untranslated content from locale files.

**Comment by mradkov** [comment]
How do you propose keeping track of all locale tokens?

e.g. If we remove let's say this from the Spanish translation:

https://github.com/aeternity/superhero-wallet/blob/6a4779c14450073c21e3892007793b92493ee2b1/src/popup/locales/es.json#L878

`vue-i18n` will fall back to the English version of the value for that token, but how is the translator later supposed to know where and how to translate this (keep in mind translators does not need to be aware of JSON and to be able to structure the locales JSON files properly).

**Comment by davidyuk** [comment]
I have two ideas regarding this:
- to write a script that will merge English translation to another one on demand
- to use third-party service to manage translations (I have seen once that is free for open-source projects)
