### ISSUE TITLE
Do not resolve names when sending tx to name on wallet side

### ISSUE THREAD

**Issue by mradkov** [superhero-com/superhero-wallet#510]
The name resolution should happen on the blockchain.

Steps to reproduce:

- use /meet
- tip some user with .chain name
-> the wallet resolves the .chain name and displays the ak_address of the user instead.

The behavior is misleading as the user is not able to verify whether they are sending to the correct address by comparing the name and ak_...

**Comment by subhod-i** [comment]
@CedrikNikita @ifaouibadi Are we still doing this?

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
