### ISSUE TITLE
Shortcut to Superhero.com Feed

### ISSUE THREAD

**Issue by thescientress** [superhero-com/superhero-wallet#712]
There should be a shortcut to the feed (Superhero.com) on the wallet for better access and to encourage use. I know it's accessible when users send tips via "View your tip on the feed"---although this button seems misleading since it just leads to the feed overall and not the specific tip sent. 
But for the long term, to encourage use of Superhero.com and other utilities there, a shortcut from the wallet could add some benefits. For your consideration. See space that could be allocated beside the buttons below.

![Screen Shot 2020-12-07 at 6 12 35 PM](https://user-images.githubusercontent.com/31926001/101339988-19a13580-38ba-11eb-971c-4c0a471eedd7.png)

**Comment by ErkanKanden** [comment]
Maybe even better to directly integrate the superhero feed into the mobile version instead of linking to a browser website, just like most other social media apps do :)
