### ISSUE TITLE
WordBazaar Mobile support via deepLink

### ISSUE THREAD

**Issue by AtanasKrondev** [superhero-com/superhero-wallet#803]
- Extract the WordBazaar token deployment, buy/sell, add to registry, voting functionality from Superhero-UI store to a module and add the module to the wallet.
- Create deeplinks for WordBazaar actions to be invokable from moblie. (something like 
`?tokenName=NAME&tokenDescription=DESCRIPTION&tokenAbbreviation=ABRVTN`)
- Adapt deeplink scheme
- Add tests to invoke it from mobile

**Comment by davidyuk** [comment]
Please, consider a more general approach, like creating a single deeplink for transaction signing on the wallet side. I don't think that it is necessary to introduce all WordBazaar related functionality on the wallet side.

**Comment by mradkov** [comment]
- generic signing deeplink with a callback
  - use the same approach we use for signing messages (comments) for superhero
- use the example wallet/app in the sdk for prototyping this [here](https://github.com/aeternity/aepp-sdk-js/tree/develop/examples/browser/vuejs/connect-two-ae)
- discuss later on specifying an AEX out of this or expanding [AEX2](https://github.com/aeternity/AEXs/blob/master/AEXS/aex-2.md)
